
/*==============================================================*/
/* View: VIEW_DOCUMENTOS_DIARIOS                                */
/*==============================================================*/
create view VIEW_DOCUMENTOS_DIARIOS as
SELECT documentos_diarios.ddi_codemp,   
         documentos_diarios.ddi_sucid,   
         documentos_diarios.ddi_anio,   
         documentos_diarios.ddi_numdoc,   
         documentos_diarios.ddi_tpcid,   
         documentos_diarios.ddi_tipmov,   
         documentos_diarios.ddi_pclid,   
         documentos_diarios.ddi_propio,   
         documentos_diarios.ddi_bcoid,   
         documentos_diarios.ddi_ctacte,   
         documentos_diarios.ddi_fecing,   
         documentos_diarios.ddi_fecdoc,   
         documentos_diarios.ddi_fecvenc,   
         documentos_diarios.ddi_edcid,   
         documentos_diarios.ddi_numcta,   
         documentos_diarios.ddi_monto,   
         documentos_diarios.ddi_saldo,   
         documentos_diarios.ddi_codmon,   
         documentos_diarios.ddi_tipcambio,   
         documentos_diarios.ddi_titular,   
         documentos_diarios.ddi_rutpag,   
         documentos_diarios.ddi_nompag,   
         documentos_diarios.ddi_ctcid,   
         documentos_diarios.ddi_empleado,   
         documentos_diarios.ddi_emplid,   
         documentos_diarios.ddi_custodia,   
         documentos_diarios.ddi_docemp,   
         documentos_diarios.ddi_pagdir,   
         documentos_diarios.ddi_vecesdep,   
         documentos_diarios.ddi_fechadep,   
         documentos_diarios.ddi_depositar,   
         documentos_diarios.ddi_rutdep,   
         documentos_diarios.ddi_nomdep,   
         documentos_diarios.ddi_nrodep,   
         documentos_diarios.ddi_fecdep,   
         documentos_diarios.ddi_pendiente,   
         tipos_cpbtdoc_idiomas.tci_idid,   
         tipos_cpbtdoc_idiomas.tci_nombre,   
         provcli.pcl_rut,   
         provcli.pcl_nomfant,   
         bancos.bco_rut,   
         bancos.bco_nombre,   
         estados_documentos_diarios_idiomas.edi_idiid,   
         estados_documentos_diarios_idiomas.edi_nombre,   
         monedas.mon_nombre,   
         deudores.ctc_rut,   
         deudores.ctc_nomfant,   
         empleados.epl_rut,   
         empleados.epl_nombre,   
         empleados.epl_apepat,
         ddi_anioneg,
         ddi_negid,
         deudores.ctc_numero,     
         deudores.ctc_digito,
         ddi_comentario 
    FROM {oj documentos_diarios LEFT OUTER JOIN provcli ON documentos_diarios.ddi_codemp = provcli.pcl_codemp AND documentos_diarios.ddi_pclid = provcli.pcl_pclid LEFT OUTER JOIN bancos ON documentos_diarios.ddi_codemp = bancos.bco_codemp AND documentos_diarios.ddi_bcoid = bancos.bco_bcoid LEFT OUTER JOIN estados_documentos_diarios_idiomas ON documentos_diarios.ddi_codemp = estados_documentos_diarios_idiomas.edi_codemp AND documentos_diarios.ddi_edcid = estados_documentos_diarios_idiomas.edi_edcid LEFT OUTER JOIN deudores ON documentos_diarios.ddi_codemp = deudores.ctc_codemp AND documentos_diarios.ddi_ctcid = deudores.ctc_ctcid LEFT OUTER JOIN empleados ON documentos_diarios.ddi_codemp = empleados.epl_codemp AND documentos_diarios.ddi_emplid = empleados.epl_emplid},   
         tipos_cpbtdoc_idiomas,   
         monedas  
   WHERE ( documentos_diarios.ddi_codemp = tipos_cpbtdoc_idiomas.tci_codemp ) and  
         ( documentos_diarios.ddi_tpcid = tipos_cpbtdoc_idiomas.tci_tpcid ) and  
         ( monedas.mon_codemp = documentos_diarios.ddi_codemp ) and  
         ( monedas.mon_codmon = documentos_diarios.ddi_codmon )
