
/*==============================================================*/
/* View: VIEW_CPBTDOC_JUDICIAL_NOROL                            */
/*==============================================================*/
create view VIEW_CPBTDOC_JUDICIAL_NOROL as
SELECT ccb_codemp rol_codemp,   
         0 rol_rolid,   
         ccb_pclid rol_pclid,   
         ccb_ctcid rol_ctcid,   
         '' rol_numero,   
         0 rol_trbid,   
         0 rol_tcaid,   
         0 rol_estid,   
         null rol_fecemi,   
         null rol_fecdem,   
         null rol_fecrol,   
         0 rol_total,   
         '' rol_comentario,   
         0 rol_esjid,   
         null rol_fecjud,   
         null rol_fecultgest,   
         '' trb_nombre,   
         tci_idid eci_idid,   
         '' eci_nombre,   
         tci_idid tci_idid,   
         '' tci_nombre,   
         tci_idid mji_idid,   
         '' mji_nombre,   
         pcl_rut pcl_rut,   
         pcl_nomfant pcl_nomfant,   
         ctc_rut ctc_rut,   
         ctc_nomfant ctc_nomfant,   
         pai_paiid,   
         pai_nombre,   
         pai_codtel,   
         reg_regid,   
         '' reg_nombre,   
         reg_orden,   
         ciu_ciuid,   
         ciu_nombre,   
         ciu_codarea,   
         com_comid,   
         com_nombre,   
         com_codpost,   
         0 etj_etjid,   
         '' as NomEnte,   
         cartera_clientes_documentos_cpbt_doc.tci_nombre as TipDoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_numero,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecing,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecdoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecvenc,   
         cartera_clientes_documentos_cpbt_doc.eci_nombre as EstDoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_codmon,   
         cartera_clientes_documentos_cpbt_doc.ccb_tipcambio,   
         cartera_clientes_documentos_cpbt_doc.ccb_asignado,   
         cartera_clientes_documentos_cpbt_doc.ccb_monto,   
         cartera_clientes_documentos_cpbt_doc.ccb_saldo,   
         cartera_clientes_documentos_cpbt_doc.ccb_gastjud,   
         cartera_clientes_documentos_cpbt_doc.ccb_gastotro,   
         cartera_clientes_documentos_cpbt_doc.ccb_intereses,   
         cartera_clientes_documentos_cpbt_doc.ccb_honorarios,   
         cartera_clientes_documentos_cpbt_doc.bco_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_rutgir,   
         cartera_clientes_documentos_cpbt_doc.ccb_nomgir,   
         cartera_clientes_documentos_cpbt_doc.ccb_comentario,   
         cartera_clientes_documentos_cpbt_doc.ccb_numesp,   
         cartera_clientes_documentos_cpbt_doc.ccb_numagrupa,   
         cartera_clientes_documentos_cpbt_doc.sbc_rut,   
         cartera_clientes_documentos_cpbt_doc.sbc_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_tipcart,   
         cartera_clientes_documentos_cpbt_doc.tci_idid  as TipIdi,   
         cartera_clientes_documentos_cpbt_doc.eci_idid as EciIdi,   
         cartera_clientes_documentos_cpbt_doc.mci_idid,   
         cartera_clientes_documentos_cpbt_doc.mon_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_compromiso,   
         cartera_clientes_documentos_cpbt_doc.ect_agrupa,   
         cartera_clientes_documentos_cpbt_doc.ect_utiliza,   
         cartera_clientes_documentos_cpbt_doc.ect_prejud,   
         cartera_clientes_documentos_cpbt_doc.pcc_codigo,   
         cartera_clientes_documentos_cpbt_doc.pcc_nombre,   
         cartera_clientes_documentos_cpbt_doc.pcc_codid,   
         cartera_clientes_documentos_cpbt_doc.eci_estid,   
         cartera_clientes_documentos_cpbt_doc.mci_nombre,   
         reg_nombre as RegDeu,
         'N' etj_sindico,
         'N' etj_abogado,
         'N' etj_procurador,
         'N' etj_receptor,
         ccb_saldo rdc_saldo,
         '' trb_direccion,
         ccb_estcpbt,
         ctc_numero,     
         ctc_digito,
          cartera_clientes_documentos_cpbt_doc.ccb_fecultgest,
         cartera_clientes_documentos_cpbt_doc.ccb_ccbid,
         ctc_direccion,
         'N' rol_bloqueo,
         'N' rol_prequiebra
    FROM {oj cartera_clientes_documentos_cpbt_doc LEFT OUTER JOIN rol_documentos ON cartera_clientes_documentos_cpbt_doc.ccb_codemp = rol_documentos.rdc_codemp AND cartera_clientes_documentos_cpbt_doc.ccb_pclid = rol_documentos.rdc_pclid AND cartera_clientes_documentos_cpbt_doc.ccb_ctcid = rol_documentos.rdc_ctcid AND cartera_clientes_documentos_cpbt_doc.ccb_ccbid = rol_documentos.rdc_ccbid},   
         view_datos_geograficos  
   WHERE ( cartera_clientes_documentos_cpbt_doc.ctc_comid = view_datos_geograficos.com_comid ) and  
         ( ( rol_documentos.rdc_codemp is null )   
         )
