


/*==============================================================*/
/* View: VIEW_ROL_DATOS                                         */
/*==============================================================*/
create view VIEW_ROL_DATOS as
 SELECT view_rol.rol_codemp,   
         view_rol.rol_rolid,   
         view_rol.rol_pclid,   
         view_rol.rol_ctcid,   
         view_rol.rol_numero,   
         view_rol.rol_trbid,   
         view_rol.rol_tcaid,   
         view_rol.rol_estid,   
         view_rol.rol_fecemi,   
         view_rol.rol_fecdem,   
         view_rol.rol_fecrol,   
         view_rol.rol_total,   
         view_rol.rol_comentario,   
         view_rol.rol_esjid,   
         view_rol.rol_fecjud,   
         view_rol.rol_fecultgest,   
         view_rol.trb_nombre,   
         view_rol.eci_idid,   
         view_rol.eci_nombre,   
         view_rol.tci_idid,   
         view_rol.tci_nombre,   
         view_rol.mji_idid,   
         view_rol.mji_nombre,   
         view_rol.pcl_rut,   
         view_rol.pcl_nomfant,   
         view_rol.ctc_rut,   
         view_rol.ctc_nomfant,   
         view_rol.pai_paiid,   
         view_rol.pai_nombre,   
         view_rol.pai_codtel,   
         view_rol.reg_regid,   
         view_rol.reg_nombre,   
         view_rol.reg_orden,   
         view_rol.ciu_ciuid,   
         view_rol.ciu_nombre,   
         view_rol.ciu_codarea,   
         view_rol.com_comid,   
         view_rol.com_nombre,   
         view_rol.com_codpost,   
         view_entes_judiciales.etj_etjid,   
         view_entes_judiciales.pcl_nomfant as NomEnte,   
         cartera_clientes_documentos_cpbt_doc.tci_nombre as TipDoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_numero,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecing,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecdoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_fecvenc,   
         cartera_clientes_documentos_cpbt_doc.eci_nombre as EstDoc,   
         cartera_clientes_documentos_cpbt_doc.ccb_codmon,   
         cartera_clientes_documentos_cpbt_doc.ccb_tipcambio,   
         cartera_clientes_documentos_cpbt_doc.ccb_asignado,   
         cartera_clientes_documentos_cpbt_doc.ccb_monto,   
         cartera_clientes_documentos_cpbt_doc.ccb_saldo,   
         cartera_clientes_documentos_cpbt_doc.ccb_gastjud,   
         cartera_clientes_documentos_cpbt_doc.ccb_gastotro,   
         cartera_clientes_documentos_cpbt_doc.ccb_intereses,   
         cartera_clientes_documentos_cpbt_doc.ccb_honorarios,   
         cartera_clientes_documentos_cpbt_doc.bco_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_rutgir,   
         cartera_clientes_documentos_cpbt_doc.ccb_nomgir,   
         cartera_clientes_documentos_cpbt_doc.ccb_comentario,   
         cartera_clientes_documentos_cpbt_doc.ccb_numesp,   
         cartera_clientes_documentos_cpbt_doc.ccb_numagrupa,   
         cartera_clientes_documentos_cpbt_doc.sbc_rut,   
         cartera_clientes_documentos_cpbt_doc.sbc_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_tipcart,   
         cartera_clientes_documentos_cpbt_doc.tci_idid  as TipIdi,   
         cartera_clientes_documentos_cpbt_doc.eci_idid as EciIdi,   
         cartera_clientes_documentos_cpbt_doc.mci_idid,   
         cartera_clientes_documentos_cpbt_doc.mon_nombre,   
         cartera_clientes_documentos_cpbt_doc.ccb_compromiso,   
         cartera_clientes_documentos_cpbt_doc.ect_agrupa,   
         cartera_clientes_documentos_cpbt_doc.ect_utiliza,   
         cartera_clientes_documentos_cpbt_doc.ect_prejud,   
         cartera_clientes_documentos_cpbt_doc.pcc_codigo,   
         cartera_clientes_documentos_cpbt_doc.pcc_nombre,   
         cartera_clientes_documentos_cpbt_doc.pcc_codid,   
         cartera_clientes_documentos_cpbt_doc.eci_estid,   
         cartera_clientes_documentos_cpbt_doc.mci_nombre,   
         view_datos_geograficos.reg_nombre as RegDeu,
         etj_sindico,
         etj_abogado,
         etj_procurador,
         etj_receptor,
         rdc_saldo,
         trb_direccion,
         ccb_estcpbt,
         view_rol.ctc_numero,     
         view_rol.ctc_digito,
          cartera_clientes_documentos_cpbt_doc.ccb_fecultgest,
         cartera_clientes_documentos_cpbt_doc.ccb_ccbid,
         view_rol.ctc_direccion,
         view_rol.rol_bloqueo,
         view_rol.rol_prequiebra,
         view_rol.ctc_nombre,
         view_rol.ctc_apepat,
         view_rol.ctc_apemat        
     FROM {oj view_rol LEFT OUTER JOIN entejud_rol ON view_rol.rol_codemp = entejud_rol.ejr_codemp AND view_rol.rol_rolid = entejud_rol.ejr_rolid LEFT OUTER JOIN view_entes_judiciales ON entejud_rol.ejr_codemp = view_entes_judiciales.etj_codemp AND entejud_rol.ejr_etjid = view_entes_judiciales.etj_etjid},   
         rol_documentos,   
         cartera_clientes_documentos_cpbt_doc,   
         view_datos_geograficos  
   WHERE ( view_rol.rol_codemp = rol_documentos.rdc_codemp ) and  
         ( view_rol.rol_rolid = rol_documentos.rdc_rolid ) and  
         ( rol_documentos.rdc_codemp = cartera_clientes_documentos_cpbt_doc.ccb_codemp ) and  
         ( rol_documentos.rdc_pclid = cartera_clientes_documentos_cpbt_doc.ccb_pclid ) and  
         ( rol_documentos.rdc_ctcid = cartera_clientes_documentos_cpbt_doc.ccb_ctcid ) and  
         ( rol_documentos.rdc_ccbid = cartera_clientes_documentos_cpbt_doc.ccb_ccbid ) and  
         ( cartera_clientes_documentos_cpbt_doc.ctc_comid = view_datos_geograficos.com_comid )
