
/*==============================================================*/
/* View: VIEW_ROL                                               */
/*==============================================================*/
CREATE view [dbo].[VIEW_PAGOS] as
SELECT DISTINCT  dbo.APLICACIONES.APL_CODEMP, 
                 dbo.APLICACIONES.APL_SUCID, 
		 dbo.APLICACIONES.APL_ANIO, 
		 dbo.APLICACIONES.APL_MES, 
		 dbo.APLICACIONES.APL_NUMAPL, 
		 dbo.APLICACIONES.APL_FECAPL, 
                 dbo.APLICACIONES.APL_TIPO, 
		 dbo.APLICACIONES.APL_ACCION, 
		 dbo.APLICACIONES.APL_FECING, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_tpcid, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.tci_nombre, 
                 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_numcta, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_tipcambio, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.mon_nombre, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_pclid, 
                 dbo.VIEW_DOCUMENTOS_DIARIOS.pcl_rut, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.pcl_nomfant, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_ctcid, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ctc_rut, 
                 dbo.VIEW_DOCUMENTOS_DIARIOS.ctc_nomfant,
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_emplid, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.epl_rut, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.epl_nombre, 
                 dbo.VIEW_DOCUMENTOS_DIARIOS.epl_apepat, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_custodia, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_docemp, 
		 dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_pagdir, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.TCI_NOMBRE AS tci_nombreP, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_NUMERO, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_PCLID, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.PCL_RUT AS pcl_rutP,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.PCL_NOMFANT AS pcl_nomfantP, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CTCID AS ccb_ctcidP,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CTC_RUT AS ctc_rutP, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CTC_NUMERO, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CTC_DIGITO, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CTC_NOMFANT AS ctc_nomfantP, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_FECDOC, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_FECVENC,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_FECING, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_TIPCART, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CODMON,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_ASIGNADO,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_MONTO, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_SALDO,
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_NUMESP, 'N' AS gastjud,
		 dbo.APLICACIONES_ITEMS.API_CAPITAL, 
                 dbo.APLICACIONES_ITEMS.API_INTERES, 
		 dbo.APLICACIONES_ITEMS.API_HONORARIO, 
		 dbo.APLICACIONES_ITEMS.API_GASTPRE,
		 dbo.APLICACIONES_ITEMS.API_GASTJUD, 
		 dbo.APLICACIONES_ITEMS.API_GESID, 
                 dbo.APLICACIONES_ITEMS.API_VDEID, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.SBC_RUT, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.SBC_NOMBRE, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.PCC_CODID, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.PCC_CODIGO, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.PCC_NOMBRE, 
                 dbo.USUARIOS.USR_USRID, dbo.USUARIOS.USR_NOMBRE, 
		 dbo.IDIOMAS.IDI_IDID, dbo.APLICACIONES_ITEMS.API_ITEM, 
		 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CCBID, 
                 dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CTCID
FROM dbo.APLICACIONES with (nolock) 
			INNER JOIN dbo.APLICACIONES_ITEMS with (nolock)
ON  (dbo.APLICACIONES.APL_CODEMP = dbo.APLICACIONES_ITEMS.API_CODEMP AND dbo.APLICACIONES.APL_SUCID = dbo.APLICACIONES_ITEMS.API_SUCID AND 
     dbo.APLICACIONES.APL_ANIO = dbo.APLICACIONES_ITEMS.API_ANIO AND dbo.APLICACIONES.APL_NUMAPL = dbo.APLICACIONES_ITEMS.API_NUMAPL) 
		      INNER JOIN dbo.VIEW_DOCUMENTOS_DIARIOS with (nolock)
ON (dbo.APLICACIONES_ITEMS.API_CODEMP = dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_codemp AND dbo.APLICACIONES_ITEMS.API_SUCID = dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_sucid AND 
    dbo.APLICACIONES_ITEMS.API_ANIODOC = dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_anio AND dbo.APLICACIONES_ITEMS.API_NUMDOC = dbo.VIEW_DOCUMENTOS_DIARIOS.ddi_numdoc) 
	              INNER JOIN dbo.USUARIOS with (nolock)
ON (dbo.APLICACIONES.APL_CODEMP = dbo.USUARIOS.USR_CODEMP AND dbo.APLICACIONES.APL_USRID = dbo.USUARIOS.USR_USRID) 
                      INNER JOIN dbo.IDIOMAS with (nolock)
ON (dbo.VIEW_DOCUMENTOS_DIARIOS.edi_idiid = dbo.IDIOMAS.IDI_IDID AND dbo.VIEW_DOCUMENTOS_DIARIOS.tci_idid = dbo.IDIOMAS.IDI_IDID)
                      INNER JOIN dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC with (nolock)
ON (dbo.APLICACIONES_ITEMS.API_CODEMP = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CODEMP AND 
    dbo.APLICACIONES_ITEMS.API_PCLID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_PCLID AND 
	dbo.APLICACIONES_ITEMS.API_CTCID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CTCID AND 
    dbo.APLICACIONES_ITEMS.API_CCBID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.CCB_CCBID AND 
	dbo.IDIOMAS.IDI_IDID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.TCI_IDID AND 
    dbo.IDIOMAS.IDI_IDID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.ECI_IDID AND 
	dbo.IDIOMAS.IDI_IDID = dbo.CARTERA_CLIENTES_DOCUMENTOS_CPBT_DOC.MCI_IDID)


