

Create Procedure Insertar_Insumos(@ins_codemp integer, @ins_insid numeric(15), @ins_codigo varchar(30), @ins_nombre varchar(300),
											 @ins_arancel char(1),  @ins_porcaran decimal(8,2), @ins_exento char(1), @ins_tipo smallint, @ins_terminado char(1), @ins_tiping char(1), 
											 @ins_tipid integer, @ins_catid integer, @ins_cubicaje decimal(15,2), @ins_unmlgt integer,
											 @ins_alto decimal(15,2), @ins_ancho decimal(15,2), @ins_largo decimal(15,2),
											 @ins_perecible char(1), @ins_fecvenc datetime, @ins_gastjud char(1), @ins_impdeu char(1), 
                                             @ins_impcli char(1), @ins_pctid integer, 
                                             @ins_pack smallint, @ins_packint smallint,
                                             @ins_SpcID integer) as
  INSERT INTO insumos  
         ( ins_codemp,   
           ins_insid,   
           ins_codigo,   
           ins_nombre,   
           ins_estado,   
           ins_stock_total,   
           ins_stock_reservado,   
           ins_stock_transito,   
           ins_stock_merma,   
           ins_stock_minimo,   
           ins_stock_maximo,   
           ins_stock_cierre_anio,   
           ins_orden_bodega,   
           ins_orden_otro,   
           ins_fecingreso,   
           ins_fecfin,   
           ins_arancel,   
           ins_porcaran,   
           ins_exento,   
           ins_tipo,   
           ins_terminado,   
           ins_costo,   
           ins_costo_prom,   
           ins_tiping,   
           ins_tipid,   
           ins_catid,   
           ins_cubicaje,   
           ins_unmlgt,   
           ins_alto,   
           ins_ancho,   
           ins_largo,   
           ins_perecible,   
           ins_fecvenc,   
           ins_gastjud,   
           ins_impdeu,   
           ins_impcli,
           ins_pctid,
           ins_pack,
           ins_packint,
           ins_SpcID   )  
  VALUES ( @ins_codemp,   
           @ins_insid,   
           @ins_codigo,   
           @ins_nombre,   
           'U',   
           0,   
           0,   
           0,   
           0,   
           0,   
           0,   
           0,   
           0,   
           0,   
           getdate(),   
           null,   
           @ins_arancel,   
           @ins_porcaran,   
           @ins_exento,   
           @ins_tipo,   
           @ins_terminado,   
           0,   
           0,   
           @ins_tiping,   
           @ins_tipid,   
           @ins_catid,   
           @ins_cubicaje,   
           @ins_unmlgt,   
           @ins_alto,   
           @ins_ancho,   
           @ins_largo,   
           @ins_perecible,   
           @ins_fecvenc,   
           @ins_gastjud,   
           @ins_impdeu,   
           @ins_impcli,
	       @ins_pctid,
           @ins_pack,
           @ins_packint,
           @ins_SpcID )
