

Create Procedure Insertar_Empleados_Especial(@epl_codemp integer, @epl_emplid integer, @epl_rut varchar(20), @epl_nombre varchar(100), @epl_apepat varchar(60),
												@epl_apemat varchar(60), @epl_eemid integer, @epl_comid integer, @epl_direccion varchar(200), @epl_telefono varchar(80),
												@epl_celular varchar(80), @epl_mail varchar(160),  @epl_fecing datetime, @epl_fecfin datetime, @epl_sucid integer,
												@epl_usrid integer, @epl_huella varchar(8000), @epl_digito numeric(10)) as

  INSERT INTO empleados  
         ( epl_codemp,   
           epl_emplid,   
           epl_rut,   
           epl_nombre,   
           epl_apepat,   
           epl_apemat,   
           epl_eemid,   
           epl_comid,   
           epl_direccion,   
           epl_telefono,   
           epl_celular,   
           epl_mail,   
           epl_fecing,   
           epl_fecfin,   
           epl_sucid,   
           epl_usrid,   
           epl_huella,   
           epl_digito )  
  VALUES ( @epl_codemp,   
           @epl_emplid,   
           @epl_rut,   
           @epl_nombre,   
           @epl_apepat,   
           @epl_apemat,   
           @epl_eemid,   
           @epl_comid,   
           @epl_direccion,   
           @epl_telefono,   
           @epl_celular,   
           @epl_mail,   
           @epl_fecing,   
           @epl_fecfin,   
           @epl_sucid,   
           @epl_usrid,   
           @epl_huella,   
           @epl_digito )
