

Create Procedure Insertar_Detalle_Comprobantes(@dcc_codemp integer, @dcc_sucid integer, @dcc_tpcid integer, @dcc_numero numeric (15), 
															@dcc_item smallint, @dcc_insid numeric (15), @dcc_prodid numeric (15), @dcc_pclid numeric (15),
															@dcc_ctcid numeric (15), @dcc_ccbid integer, @dcc_prereal decimal (13,2), @dcc_precio decimal (13,2),
															@dcc_cantidad decimal (10,2), @dcc_saldo decimal (13,2), @dcc_neto decimal (17,2), @dcc_impuesto decimal (10,2),
															@dcc_retenido char (1), @dcc_total decimal (17,2), @dcc_interes decimal (10,2), @dcc_honorario decimal (10,2),
															@dcc_gastpre decimal (10,2), @dcc_gastjud decimal (10,2), @dcc_porcfact decimal (7,4), @dcc_porchon decimal (7,4),
															@dcc_bodid integer, @dcc_bdsid integer, @dcc_posicion smallint, @dcc_tpcidpad integer, @dcc_numeropad numeric (15),
															@dcc_itempad smallint, @dcc_bodiddes integer, @dcc_bdsiddes integer, @dcc_posiciondes smallint, 
															@dcc_numserie numeric (12), @dcc_numserieprov varchar (30),
															@dcc_cantebj decimal (10,2), @dcc_ltpid integer, @dcc_bscid varchar(10), @dcc_bsciddes varchar(10),
														     @dcc_anio smallint, @dcc_numapl integer, @dcc_itemapl integer, @dcc_valrem decimal(10,2), 
															@dcc_comentario text, @dcc_subitem integer, @dcc_exento numeric(10,2) ) as
  INSERT INTO detalle_comprobantes  
         ( dcc_codemp,   
           dcc_sucid,   
           dcc_tpcid,   
           dcc_numero,   
           dcc_item,   
           dcc_insid,   
           dcc_prodid,   
           dcc_pclid,   
           dcc_ctcid,   
           dcc_ccbid,   
           dcc_prereal,   
           dcc_precio,   
           dcc_cantidad,   
           dcc_saldo,   
           dcc_neto,   
           dcc_impuesto,   
           dcc_retenido,   
           dcc_total,   
           dcc_interes,   
           dcc_honorario,   
           dcc_gastpre,   
           dcc_gastjud,   
           dcc_porcfact,   
           dcc_porchon,   
           dcc_bodid,   
           dcc_bdsid,   
           dcc_posicion,   
           dcc_tpcidpad,   
           dcc_numeropad,   
           dcc_itempad,   
           dcc_bodiddes,   
           dcc_bdsiddes,   
           dcc_posiciondes,   
           dcc_numserie,   
           dcc_numserieprov,   
           dcc_cantebj,   
           dcc_ltpid,
           dcc_bscid,
           dcc_bsciddes,
           dcc_anio,
           dcc_numapl,
           dcc_itemapl,
           dcc_valrem,
           dcc_comentario,
           dcc_subitem,
           dcc_exento    )  
  VALUES ( @dcc_codemp,   
           @dcc_sucid,   
           @dcc_tpcid,   
           @dcc_numero,   
           @dcc_item,   
           @dcc_insid,   
           @dcc_prodid,   
           @dcc_pclid,   
           @dcc_ctcid,   
           @dcc_ccbid,   
           @dcc_prereal,   
           @dcc_precio,   
           @dcc_cantidad,   
           @dcc_saldo,   
           @dcc_neto,   
           @dcc_impuesto,   
           @dcc_retenido,   
           @dcc_total,   
           @dcc_interes,   
           @dcc_honorario,   
           @dcc_gastpre,   
           @dcc_gastjud,   
           @dcc_porcfact,   
           @dcc_porchon,   
           @dcc_bodid,   
           @dcc_bdsid,   
           @dcc_posicion,   
           @dcc_tpcidpad,   
           @dcc_numeropad,   
           @dcc_itempad,   
           @dcc_bodiddes,   
           @dcc_bdsiddes,   
           @dcc_posiciondes,   
           @dcc_numserie,   
           @dcc_numserieprov,   
            @dcc_cantebj,   
           @dcc_ltpid,
		@dcc_bscid,
		@dcc_bsciddes,
          @dcc_anio,
          @dcc_numapl,
	     @dcc_itemapl,
         @dcc_valrem,
         @dcc_comentario,
         @dcc_subitem,
         @dcc_exento    )
