

CREATE Procedure [dbo].[Insertar_Rol](@rol_codemp integer, @rol_rolid integer, @rol_pclid numeric (15), @rol_ctcid integer, 
									@rol_trbid integer, @rol_tcaid integer, @rol_estid smallint,  @rol_fecdem datetime,
									@rol_fecrol datetime,  @rol_comentario text, @rol_esjid integer, @rol_fecjud datetime, @rol_numero varchar(200)) as  
  INSERT INTO rol  
         ( rol_codemp,   
           rol_rolid,   
           rol_pclid,   
           rol_ctcid,   
           rol_numero,   
           rol_trbid,   
           rol_tcaid,   
           rol_estid,   
           rol_fecemi,   
           rol_fecdem,   
           rol_fecrol,   
           rol_total,   
           rol_comentario,   
           rol_esjid,   
           rol_fecjud,   
           rol_fecultgest,
           rol_bloqueo,
           rol_prequiebra )  
  VALUES ( @rol_codemp,   
           @rol_rolid,   
           @rol_pclid,   
           @rol_ctcid,   
           @rol_numero,   
           @rol_trbid,   
           @rol_tcaid,   
           @rol_estid,   
           getdate(),   
           @rol_fecdem,   
           @rol_fecrol,   
           0,   
           @rol_comentario,   
           @rol_esjid,   
           @rol_fecjud,   
           getdate(),
           'N',
           'N' )
