

Create Procedure Insertar_Usuarios(@usr_codemp integer, @usr_usrid integer, @usr_nombre varchar (200), @usr_login varchar (15),
                                                           @usr_password varchar (25),  @usr_mail varchar (80), @usr_tipquest smallint,
                                                           @usr_answer varchar (200), @usr_sucid integer, @usr_prfid integer, @usr_permisos smallint, @usr_campass char(1), @usr_feccambio datetime   ) as  
  INSERT INTO usuarios  
         ( usr_codemp,   
           usr_usrid,   
           usr_nombre,   
           usr_login,   
           usr_password,   
           usr_fecing,   
           usr_godlog,   
           usr_badlog,   
           usr_fecultlog,   
           usr_fecblock,   
           usr_mail,   
           usr_tipquest,   
           usr_answer,   
           usr_sucid,   
           usr_prfid,   
           usr_permisos,   
           usr_estado,
           usr_campass,
           usr_feccambio   )  
  VALUES ( @usr_codemp,   
           @usr_usrid,   
           @usr_nombre,   
           @usr_login,   
           @usr_password,   
           getdate(),   
           0,   
           0,   
           getdate(),   
           null,   
           @usr_mail,   
           @usr_tipquest,   
           @usr_answer,   
           @usr_sucid,   
           @usr_prfid,   
           @usr_permisos,   
           'H',
           @usr_campass,
           @usr_feccambio  )
