

Create Procedure Insertar_Negociacion_CpbtDoc(@ngd_codemp integer, @ngd_anio smallint, @ngd_negid integer, @ngd_pclid numeric (15), @ngd_ctcid numeric (15),
															@ngd_ccbid integer, @ngd_monto decimal (15,2), @ngd_monto_n decimal (15,2), @ngd_intereses decimal (15,2),
															@ngd_intereses_n decimal (15,2), @ngd_honorarios decimal (15,2), @ngd_honorarios_n decimal (15,2),
															@ngd_gastjud decimal (15,2), @ngd_gastjud_n decimal (15,2),
															@ngd_gastotro decimal (15,2), @ngd_gastotro_n decimal (15,2)				) as 
   INSERT INTO negociacion_cpbtdoc  
         ( ngd_codemp,   
           ngd_anio,   
           ngd_negid,   
           ngd_pclid,   
           ngd_ctcid,   
           ngd_ccbid,   
           ngd_monto,   
           ngd_monto_n,   
           ngd_intereses,   
           ngd_intereses_n,   
           ngd_honorarios,   
           ngd_honorarios_n,
           ngd_gastjud,   
           ngd_gastjud_n,
           ngd_gastotro,   
           ngd_gastotro_n )  
  VALUES ( @ngd_codemp,   
           @ngd_anio,   
           @ngd_negid,   
           @ngd_pclid,   
           @ngd_ctcid,   
           @ngd_ccbid,   
           @ngd_monto,   
           @ngd_monto_n,   
           @ngd_intereses,   
           @ngd_intereses_n,   
           @ngd_honorarios,   
           @ngd_honorarios_n,
           @ngd_gastjud,   
           @ngd_gastjud_n,
		@ngd_gastotro,   
           @ngd_gastotro_n   )
