

Create Procedure Insertar_Productos_Especial(@pdt_codemp integer, @pdt_prodid numeric (15), @pdt_codfisico varchar (20), @pdt_nombre varchar (200),
											 @pdt_tipo smallint, @pdt_mostrar char (1), @pdt_pctid integer, @pdt_insid numeric (15),
											@pdt_cc smallint, @pdt_exento char (1), 
											@pdt_impesp char (1),  @pdt_stock char (1), @pdt_perecible char (1), 
											@pdt_gastjud char (1), @pdt_impdeu char (1), @pdt_impcli char (1), 
                                            @pdt_catid integer, @pdt_estado char(1), @pdt_codbarra varchar(20), @pdt_SpcID integer) as
  INSERT INTO productos  
         ( pdt_codemp,   
           pdt_prodid,   
           pdt_codfisico,   
           pdt_nombre,   
           pdt_estado,   
           pdt_tipo,   
           pdt_mostrar,   
           pdt_fecing,   
           pdt_fecfin,   
           pdt_pctid,   
           pdt_insid,   
           pdt_costo,   
           pdt_costoprom,   
           pdt_cc,   
           pdt_exento,   
           pdt_impesp,   
           pdt_stock,   
           pdt_perecible,   
           pdt_gastjud,   
           pdt_impdeu,   
           pdt_impcli,
           pdt_catid,
           pdt_codbarra,
           pdt_SpcID )  
  VALUES ( @pdt_codemp,   
           @pdt_prodid,   
           @pdt_codfisico,   
           @pdt_nombre,   
           @pdt_estado,   
           @pdt_tipo,   
           @pdt_mostrar,   
           getdate(),   
           null,   
           @pdt_pctid,   
           @pdt_insid,   
           0,   
           0,   
           @pdt_cc,   
           @pdt_exento,   
           @pdt_impesp,   
           @pdt_stock,   
           @pdt_perecible,   
           @pdt_gastjud,   
           @pdt_impdeu,   
           @pdt_impcli,
           @pdt_catid,
           @pdt_codbarra,
           @pdt_SpcID )
