

Create Procedure Insertar_Rol_Datos_Reporte(@rdr_codemp integer, @rdr_rolid integer, @rdr_item smallint, @rdr_materia varchar (200),
														@rdr_rutdem integer, @rdr_dvdem varchar (1), @rdr_nomdem varchar (300), @rdr_rutabo integer,
														@rdr_dvabo varchar (1), @rdr_nomabo varchar (300), @rdr_telabo varchar (10), @rdr_mailabo varchar (80),
														@rdr_dirabo varchar (300), @rdr_rutdeu integer, @rdr_dvdeu varchar (1), @rdr_nomdeu varchar (300),
														@rdr_dirdeu varchar (300), @rdr_rutgir integer, @rdr_dvgir varchar (1), @rdr_nomgir varchar (300),
														@rdr_tipcpbt varchar (100), @rdr_numero varchar (50), @rdr_monto decimal (15,2), @rdr_moneda varchar (20),
														@rdr_fecpro datetime, @rdr_motivo varchar (200), @rdr_monesc varchar (1000), @rdr_totdeu decimal (15,2),
														@rdr_totesc varchar (1000), @rdr_banco varchar(300), @rdr_saldo decimal(15,2), @rdr_feccpbt datetime) as
  INSERT INTO rol_datos_reporte  
         ( rdr_codemp,   
           rdr_rolid,   
           rdr_item,   
           rdr_materia,   
           rdr_rutdem,   
           rdr_dvdem,   
           rdr_nomdem,   
           rdr_rutabo,   
           rdr_dvabo,   
           rdr_nomabo,   
           rdr_telabo,   
           rdr_mailabo,   
           rdr_dirabo,   
           rdr_rutdeu,   
           rdr_dvdeu,   
           rdr_nomdeu,   
           rdr_dirdeu,   
           rdr_rutgir,   
           rdr_dvgir,   
           rdr_nomgir,   
           rdr_tipcpbt,   
           rdr_numero,   
           rdr_monto,   
           rdr_moneda,   
           rdr_fecpro,   
           rdr_motivo,   
           rdr_monesc,   
           rdr_totdeu,   
           rdr_totesc,
           rdr_banco,
           rdr_saldo,
           rdr_feccpbt )  
  VALUES ( @rdr_codemp,   
           @rdr_rolid,   
           @rdr_item,   
           @rdr_materia,   
           @rdr_rutdem,   
           @rdr_dvdem,   
           @rdr_nomdem,   
           @rdr_rutabo,   
           @rdr_dvabo,   
           @rdr_nomabo,   
           @rdr_telabo,   
           @rdr_mailabo,   
           @rdr_dirabo,   
           @rdr_rutdeu,   
           @rdr_dvdeu,   
           @rdr_nomdeu,   
           @rdr_dirdeu,   
           @rdr_rutgir,   
           @rdr_dvgir,   
           @rdr_nomgir,   
           @rdr_tipcpbt,   
           @rdr_numero,   
           @rdr_monto,   
           @rdr_moneda,   
           @rdr_fecpro,   
           @rdr_motivo,   
           @rdr_monesc,   
           @rdr_totdeu,   
           @rdr_totesc,
		@rdr_banco,
        @rdr_saldo,
        @rdr_feccpbt )
