

Create procedure Insertar_Comisiones(@cms_codemp integer, @cms_sucid integer, @cms_anio smallint, @cms_mes smallint, 
												 @cms_item integer, @cms_gesid integer, @cms_vdeid integer, @cms_anioapl smallint, 
												 @cms_numapl integer, @cms_itemapl integer, @cms_tpcid integer, @cms_numero integer,
												 @cms_totcpbt decimal(15,2), @cms_capital decimal(15,2), @cms_honorario decimal(15,2),
												 @cms_interes decimal(15,2), @cms_gastpre decimal(15,2), @cms_gastjud decimal(15,2),
												 @cms_porcfcob decimal(15,4), @cms_porcki decimal(15,4), @cms_porch decimal(15,4),
												 @cms_comki decimal(15,2), @cms_comh decimal(15,2), @cms_porcJki decimal(15,4), @cms_porcJh decimal(15,4)) as
  INSERT INTO comisiones  
         ( cms_codemp,   
           cms_sucid,   
           cms_anio,   
           cms_mes,   
           cms_item,   
           cms_gesid,   
           cms_vdeid,   
           cms_anioapl,   
           cms_numapl,   
           cms_itemapl,   
           cms_tpcid,   
           cms_numero,   
           cms_totcpbt,   
           cms_capital,   
           cms_honorario,   
           cms_interes,   
           cms_gastpre,   
           cms_gastjud,   
           cms_porcfcob,   
           cms_porcki,   
           cms_porch,   
           cms_comki,   
           cms_comh,
           cms_porcJki,
           cms_porcJh )  
  VALUES ( @cms_codemp,   
           @cms_sucid,   
           @cms_anio,   
           @cms_mes,   
           @cms_item,   
           @cms_gesid,   
           @cms_vdeid,   
           @cms_anioapl,   
           @cms_numapl,   
           @cms_itemapl,   
           @cms_tpcid,   
           @cms_numero,   
           @cms_totcpbt,   
           @cms_capital,   
           @cms_honorario,   
           @cms_interes,   
           @cms_gastpre,   
           @cms_gastjud,   
           @cms_porcfcob,   
           @cms_porcki,   
           @cms_porch,   
           @cms_comki,   
           @cms_comh,
           @cms_porcJki,
           @cms_porcJh )
