

CREATE Procedure [dbo].[Insertar_Cartera_Clientes_Cpbt_Doc](@ccb_codemp integer, @ccb_pclid numeric (15), @ccb_ctcid numeric (15), @ccb_ccbid integer,
                                                                                     @ccb_tpcid integer, @ccb_tipcart smallint, @ccb_numero varchar (30),
                                                                                     @ccb_fecdoc datetime, @ccb_fecvenc datetime, @ccb_estid smallint, @ccb_estcpbt char (1),
                                                                                     @ccb_codmon integer, @ccb_tipcambio decimal (10,2), @ccb_asignado decimal (15,2), @ccb_monto decimal (15,2),
                                                                                     @ccb_saldo decimal (15,2), @ccb_gastjud decimal (15,2), @ccb_gastotro decimal (15,2), 
                                                                                      @ccb_bcoid integer, @ccb_rutgir varchar (20),
                                                                                     @ccb_nomgir varchar (200), @ccb_mtcid integer, @ccb_comentario text, @ccb_retent char (1),
                                                                                     @ccb_codid integer, @ccb_numesp varchar (40), @ccb_numagrupa varchar (40),
                                                                                     @ccb_cctid integer, @ccb_sbcid integer, @ccb_docori char(1), @ccb_docant char(1)) as 
  INSERT INTO cartera_clientes_cpbt_doc  
         ( ccb_codemp,   
           ccb_pclid,   
           ccb_ctcid,   
           ccb_ccbid,   
           ccb_tpcid,   
           ccb_tipcart,   
           ccb_numero,   
           ccb_fecing,   
           ccb_fecdoc,   
           ccb_fecvenc,   
           ccb_fecultgest,   
           ccb_fecplazo,   
           ccb_feccalcint,   
           ccb_feccast,   
           ccb_estid,   
           ccb_estcpbt,   
           ccb_codmon,   
           ccb_tipcambio,   
           ccb_asignado,   
           ccb_monto,   
           ccb_saldo,   
           ccb_gastjud,   
           ccb_gastotro,   
           ccb_intereses,   
           ccb_honorarios,   
           ccb_calchon,   
           ccb_bcoid,   
           ccb_rutgir,   
           ccb_nomgir,   
           ccb_mtcid,   
           ccb_comentario,   
           ccb_retent,   
           ccb_codid,   
           ccb_numesp,   
           ccb_numagrupa,   
           ccb_carta,   
           ccb_cobrable,   
           ccb_cctid,   
           ccb_sbcid,
           ccb_docori,
           ccb_docant,
           ccb_estidj   )  
  VALUES ( @ccb_codemp,   
           @ccb_pclid,   
           @ccb_ctcid,   
           @ccb_ccbid,   
           @ccb_tpcid,   
           @ccb_tipcart,   
           @ccb_numero,   
           getdate(),   
           @ccb_fecdoc,   
           @ccb_fecvenc,   
           getdate(),   
           null,   
           null,   
           null,   
           @ccb_estid,   
           @ccb_estcpbt,   
           @ccb_codmon,   
           @ccb_tipcambio,   
           @ccb_asignado,   
           @ccb_monto,   
           @ccb_saldo,   
           @ccb_gastjud,   
           @ccb_gastotro,   
           0,   
           0,   
          'N',   
           @ccb_bcoid,   
           @ccb_rutgir,   
           @ccb_nomgir,   
           @ccb_mtcid,   
           @ccb_comentario,   
           @ccb_retent,   
           @ccb_codid,   
           @ccb_numesp,   
           @ccb_numagrupa,   
           0,   
           'S',   
           @ccb_cctid,   
           @ccb_sbcid,
           @ccb_docori,
           @ccb_docant,
           @ccb_estid )
