CREATE Procedure [dbo].[Listar_Causa_Rut](@rut varchar(20))

 as   

select R.TIPO,
R.NUMERO,
R.ANIO,
R.FECHA_INGRESO FechaIngreso, 
T.TRIBUNAL, 
L2.NOMBRE DEMANDANTE,
L.NOMBRE DEMANDADO,
R.RUTA_DEMANDA RutaDemanda
from PODER_JUDICIAL_LITIGANTE L  with(nolock)
INNER JOIN  PODER_JUDICIAL_ROL R  with(nolock)
ON L.ID_CAUSA = R.ID_CAUSA
INNER JOIN PODER_JUDICIAL_TRIBUNAL T  with(nolock)
ON R.TRIBUNAL = T.ID_TRIBUNAL
INNER JOIN PODER_JUDICIAL_LITIGANTE L2  with(nolock)
ON L.ID_CAUSA = L2.ID_CAUSA
where L.PARTICIPANTE = 'DDO.'
and L.RUT = @rut
AND L2.PARTICIPANTE = 'DTE.'