
CREATE procedure [dbo].[_Eliminar_PanelDemandaPrevisionalPorId] (
	@idPanel int
) as
	DELETE PANEL_DEMANDA_PREVISIONAL_CONFECCION WHERE ID_PANEL_PREVISIONAL = @idPanel

	DELETE PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS WHERE panel_id = @idPanel

	DELETE PANEL_DEMANDA_PREVISIONAL_DETALLE WHERE panel_id = @idPanel

	DELETE PANEL_DEMANDA_PREVISIONAL_CORRECCION_HISTORIAL WHERE panel_id = @idPanel

	DELETE PANEL_DEMANDA_PREVISIONAL_CURSODEMANDA_HISTORIAL WHERE panel_id = @idPanel

	DELETE PANEL_DEMANDA_PREVISIONAL WHERE panel_id = @idPanel
