create procedure [dbo].[_Insertar_Aplicaciones_Items](@api_codemp integer, @api_sucid integer, @api_anio smallint, @api_numapl integer, 
														  @api_item integer, @api_aniodoc smallint, @api_numdoc integer,
														  @api_aniodoc2 integer, @api_numdoc2 smallint, @api_tpcid integer, @api_numero integer,
														  @api_tpcid2 integer, @api_numero2 integer, @api_pclid integer, @api_ctcid integer, 
														  @api_ccbid integer, @api_capital decimal(15,2), @api_interes decimal(15,2),
														  @api_honorario decimal(15,2),	 @api_gastpre decimal(15,2), @api_gastjud decimal(15,2),	
														  @api_gesid integer, @api_vdeid integer, @api_remesa varchar(1)) as
  INSERT INTO aplicaciones_items  
         ( api_codemp,   
           api_sucid,   
           api_anio,   
           api_numapl,   
           api_item,   
           api_aniodoc,   
           api_numdoc,   
           api_aniodoc2,   
           api_numdoc2,   
           api_tpcid,   
           api_numero,   
           api_tpcid2,   
           api_numero2,   
           api_pclid,   
           api_ctcid,   
           api_ccbid,   
           api_capital,   
           api_interes,   
           api_honorario,   
           api_gastpre,   
           api_gastjud,   
           api_gesid,   
           api_vdeid,
           api_remesa )  
  VALUES ( @api_codemp,   
           @api_sucid,   
           @api_anio,   
           @api_numapl,   
           @api_item,   
           @api_aniodoc,   
           @api_numdoc,   
           @api_aniodoc2,   
           @api_numdoc2,   
           @api_tpcid,   
           @api_numero,   
           @api_tpcid2,   
           @api_numero2,   
           @api_pclid,   
           @api_ctcid,   
           @api_ccbid,   
           @api_capital,   
           @api_interes,   
           @api_honorario,   
           @api_gastpre,   
           @api_gastjud,   
           @api_gesid,   
           @api_vdeid,
           @api_remesa )
