CREATE PROCEDURE [dbo].[_Listar_Visita_Terreno](@ctcid int)
AS
begin
	SELECT
	  vt.ID_VISITA,
	  vts.DIRECCION,
	  d.CTC_RUT DEUDOR_RUT,
	  vte.ESTATUS ESTADO, (CASE
				WHEN vtd.ID_VISITA_DETALLE IS NULL THEN 0
				ELSE vtd.ID_VISITA_DETALLE
				END) ID_VISITA_DETALLE,
	  vt.CTCID, tipo.ESTADO_VISITA ESTADO_VISITA,
	  vtd.VISITA,
	  (CASE
				WHEN vtd.ID_VISITA_DETALLE IS NULL THEN 'SE ENCUENTRA '  + vte.ESTATUS
				ELSE vtd.COMENTARIOS
				END) COMENTARIOS,
		vts.LATITUD, vts.LONGITUD, vts.COMUNA, dateadd(hour, -3, vtd.FEC_ENVIO) FECHAENVIO, isnull(vtd.DIRECCIONENVIO, '') DIRECCIONENVIO, CASE WHEN vtd.POSICIONENVIO is null then '0,0' else CASE vtd.POSICIONENVIO 
																							  WHEN '' THEN '0,0'  
																							  ELSE vtd.POSICIONENVIO END end as POSICIONENVIO
	FROM VISITA_TERRENO vt
	JOIN VISITA_TERRENO_SOLICITUD vts
	ON vt.SOLICITUD_ID = vts.SOLICITUD_ID
	JOIN VISITA_TERRENO_TIPO_ESTATUS_ESTADO vte
	ON vt.ID_ESTATUS = vte.ID_ESTATUS
	JOIN DEUDORES d
	ON vt.CTCID = D.CTC_CTCID
	LEFT JOIN VISITA_TERRENO_DETALLE vtd
	ON vt.ID_VISITA = vtd.ID_VISITA
	AND vt.CTCID = vtd.CTCID
	LEFT JOIN VISITA_TERRENO_DETALLE_TIPO_ESTADO_VISITA tipo
	ON vtd.ESTADO_VISITA = tipo.ID_TIPO_ESTADO_VISITA
	WHERE vt.CTCID = @ctcid --@ctcid
	ORDER BY vts.FEC_CREACION DESC
	--AND vt.ESTADO = 'RECIBIDA'
end
