//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dimol.Carteras.CausaPorRut {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CausaPorRut.IConsultaRut")]
    public interface IConsultaRut {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaRut/CausasPorRut", ReplyAction="http://tempuri.org/IConsultaRut/CausasPorRutResponse")]
        Dimol.Service.dto.ConsultaPJ[] CausasPorRut(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaRut/CausasPorRut", ReplyAction="http://tempuri.org/IConsultaRut/CausasPorRutResponse")]
        System.Threading.Tasks.Task<Dimol.Service.dto.ConsultaPJ[]> CausasPorRutAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaRutChannel : Dimol.Carteras.CausaPorRut.IConsultaRut, System.ServiceModel.IClientChannel {    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaRutClient : System.ServiceModel.ClientBase<Dimol.Carteras.CausaPorRut.IConsultaRut>, Dimol.Carteras.CausaPorRut.IConsultaRut {
        
        public ConsultaRutClient() {
        }
        
        public ConsultaRutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaRutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dimol.Service.dto.ConsultaPJ[] CausasPorRut(string rut) {
            return base.Channel.CausasPorRut(rut);
        }
        
        public System.Threading.Tasks.Task<Dimol.Service.dto.ConsultaPJ[]> CausasPorRutAsync(string rut) {
            return base.Channel.CausasPorRutAsync(rut);
        }
    }
}
