USE [DimolDB]
GO

/****** Object:  Table [dbo].[CENTRAL_GESTOR]    Script Date: 06-07-2017 14:53:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CENTRAL_GESTOR](
	[ANEXO] [int] NOT NULL,
	[NOMBRE] [varchar](100) NULL,
	[CARTERA] [varchar](100) NULL,
	[SUCURSAL] [varchar](100) NULL,
	[DISPONIBLE] [varchar](100) NULL,
	[FECHA_CREA] [datetime] NULL,
	[FECHA_MODIFICA] [datetime] NULL,
 CONSTRAINT [PK_CENTRAL_GESTOR] PRIMARY KEY CLUSTERED 
(
	[ANEXO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

