CREATE PROCEDURE [dbo].[_Buscar_Cartera_Email_Contactos_Prov]
(
@CODEMP int,
@CTCID int,
@PCLID int
)
AS
BEGIN
	SET NOCOUNT ON;

SELECT [DEUDORES_CONTACTOS_MAIL_PROV].[MAIL] AS ddm_mail, 
[DEUDORES_CONTACTOS_MAIL_PROV].[TIPO] AS ddm_tipo,
[VIEW_DATOS_GEOGRAFICOS].[ciu_codarea],
[DEUDORES].[CTC_NOMBRE] AS ctc_nombre,
'N' AS Contacto,
[DEUDORES].[CTC_RUT] AS ctc_rut,
[DEUDORES].[CTC_NOMFANT] AS ctc_nomfant
FROM [DEUDORES],
[DEUDORES_CONTACTOS_MAIL_PROV],
[VIEW_DATOS_GEOGRAFICOS]
WHERE CODEMP = @CODEMP
AND CTCID = @CTCID
AND [DEUDORES].[CTC_COMID] = [VIEW_DATOS_GEOGRAFICOS].[com_comid]
AND [DEUDORES_CONTACTOS_MAIL_PROV].[CODEMP] = [DEUDORES].[CTC_CODEMP]
AND [DEUDORES_CONTACTOS_MAIL_PROV].[CTCID] = [DEUDORES].[CTC_CTCID]
AND PCLID = @PCLID
AND MASIVO = 'S'

END

RETURN 0;