CREATE TABLE [dbo].[APLICACIONES_ITEMS] (
    [API_CODEMP]    INT             NOT NULL,
    [API_SUCID]     INT             NOT NULL,
    [API_ANIO]      INT             NOT NULL,
    [API_NUMAPL]    NUMERIC (15)    NOT NULL,
    [API_ITEM]      INT             NOT NULL,
    [API_ANIODOC]   SMALLINT        NULL,
    [API_NUMDOC]    NUMERIC (15)    NULL,
    [API_ANIODOC2]  SMALLINT        NULL,
    [API_NUMDOC2]   NUMERIC (15)    NULL,
    [API_TPCID]     INT             NULL,
    [API_NUMERO]    NUMERIC (15)    NULL,
    [API_TPCID2]    INT             NULL,
    [API_NUMERO2]   NUMERIC (15)    NULL,
    [API_PCLID]     NUMERIC (15)    NULL,
    [API_CTCID]     NUMERIC (15)    NULL,
    [API_CCBID]     INT             NULL,
    [API_CAPITAL]   NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
    [API_INTERES]   NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
    [API_HONORARIO] NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
    [API_GASTPRE]   NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
    [API_GASTJUD]   NUMERIC (15, 2) DEFAULT ((0)) NOT NULL,
    [API_GESID]     INT             NULL,
    [API_VDEID]     INT             NULL,
    [API_REMESA]    CHAR (1)        DEFAULT ('N') NULL,
    CONSTRAINT [PK_APLICACIONES_ITEMS] PRIMARY KEY CLUSTERED ([API_CODEMP] ASC, [API_SUCID] ASC, [API_ANIO] ASC, [API_NUMAPL] ASC, [API_ITEM] ASC),
    CONSTRAINT [FK_APLICACI_APL_ITEMS_APLICACI] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_ANIO], [API_NUMAPL]) REFERENCES [dbo].[APLICACIONES] ([APL_CODEMP], [APL_SUCID], [APL_ANIO], [APL_NUMAPL]),
    CONSTRAINT [FK_APLICACI_CABCBT_AP_CABACERA] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_TPCID2], [API_NUMERO2]) REFERENCES [dbo].[CABACERA_COMPROBANTES] ([CBC_CODEMP], [CBC_SUCID], [CBC_TPCID], [CBC_NUMERO]),
    CONSTRAINT [FK_APLICACI_CABCPBT_A_CABACERA] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_TPCID], [API_NUMERO]) REFERENCES [dbo].[CABACERA_COMPROBANTES] ([CBC_CODEMP], [CBC_SUCID], [CBC_TPCID], [CBC_NUMERO]),
    CONSTRAINT [FK_APLICACI_CARTCPBTD_CARTERA_] FOREIGN KEY ([API_CODEMP], [API_PCLID], [API_CTCID], [API_CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_APLICACI_DOCDIA_AP_DOCUMENT] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_ANIODOC], [API_NUMDOC]) REFERENCES [dbo].[DOCUMENTOS_DIARIOS] ([DDI_CODEMP], [DDI_SUCID], [DDI_ANIO], [DDI_NUMDOC]),
    CONSTRAINT [FK_APLICACI_DODIA_APL_DOCUMENT] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_ANIODOC2], [API_NUMDOC2]) REFERENCES [dbo].[DOCUMENTOS_DIARIOS] ([DDI_CODEMP], [DDI_SUCID], [DDI_ANIO], [DDI_NUMDOC]),
    CONSTRAINT [FK_APLICACI_GEST_APLI_GESTOR] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_APLICACI_VEND_APLI_VENDEDOR] FOREIGN KEY ([API_CODEMP], [API_SUCID], [API_VDEID]) REFERENCES [dbo].[VENDEDORES] ([VDE_CODEMP], [VDE_SUCID], [VDE_VDEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[APLICACIONES_ITEMS]([API_CODEMP] ASC, [API_SUCID] ASC, [API_ANIO] ASC, [API_NUMAPL] ASC, [API_ITEM] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de aplicaciones, indicando su origen y su contra parte', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APLICACIONES_ITEMS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Indica el año de la aplicacion', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APLICACIONES_ITEMS', @level2type = N'COLUMN', @level2name = N'API_ANIO';

