CREATE TABLE [dbo].[ASIENTOS_CONTABLES_DETALLE] (
    [ACD_CODEMP] INT             NOT NULL,
    [ACD_ANIO]   INT             NOT NULL,
    [ACD_TIPO]   CHAR (1)        NOT NULL,
    [ACD_NUMERO] NUMERIC (15)    NOT NULL,
    [ACD_ITEM]   INT             NOT NULL,
    [ACD_PCTID]  INT             NOT NULL,
    [ACD_CCSID]  INT             NULL,
    [ACD_DEBE]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [ACD_HABER]  DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [ACD_EXENTO] CHAR (1)        NOT NULL,
    [ACD_GLOSA]  VARCHAR (400)   NULL,
    CONSTRAINT [PK_ASIENTOS_CONTABLES_DETALLE] PRIMARY KEY CLUSTERED ([ACD_CODEMP] ASC, [ACD_ANIO] ASC, [ACD_TIPO] ASC, [ACD_NUMERO] ASC, [ACD_ITEM] ASC),
    CONSTRAINT [CKC_ACD_TIPO_ASIENTOS] CHECK ([ACD_TIPO]='A' OR [ACD_TIPO]='T' OR [ACD_TIPO]='E' OR [ACD_TIPO]='I'),
    CONSTRAINT [FK_ASIENTOS_ASICONT_D_ASIENTOS] FOREIGN KEY ([ACD_CODEMP], [ACD_ANIO], [ACD_TIPO], [ACD_NUMERO]) REFERENCES [dbo].[ASIENTOS_CONTABLES] ([AST_CODEMP], [AST_ANIO], [AST_TIPO], [AST_NUMERO]),
    CONSTRAINT [FK_ASIENTOS_CENCOST_A_CENTRO_C] FOREIGN KEY ([ACD_CODEMP], [ACD_CCSID]) REFERENCES [dbo].[CENTRO_COSTOS] ([CCS_CODEMP], [CCS_CCSID]),
    CONSTRAINT [FK_ASIENTOS_PLACTA_AS_PLAN_CUE] FOREIGN KEY ([ACD_CODEMP], [ACD_PCTID]) REFERENCES [dbo].[PLAN_CUENTAS] ([PCT_CODEMP], [PCT_PCTID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ASIENTOS_CONTABLES_DETALLE]([ACD_CODEMP] ASC, [ACD_ANIO] ASC, [ACD_TIPO] ASC, [ACD_NUMERO] ASC, [ACD_ITEM] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Este campo indica si el monto es un impuesto exento', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASIENTOS_CONTABLES_DETALLE', @level2type = N'COLUMN', @level2name = N'ACD_EXENTO';

