CREATE TABLE [dbo].[ASIENTOS_CONTABLES_ESTADOS] (
    [ASE_CODEMP]     INT          NOT NULL,
    [ASE_ANIO]       INT          NOT NULL,
    [ASE_TIPO]       CHAR (1)     NOT NULL,
    [ASE_NUMERO]     NUMERIC (15) NOT NULL,
    [ASE_ESTADO]     CHAR (1)     NOT NULL,
    [ASE_FECHA]      DATETIME     NOT NULL,
    [ASE_COMENTARIO] TEXT         NULL,
    [ASE_USRID]      INT          NOT NULL,
    CONSTRAINT [PK_ASIENTOS_CONTABLES_ESTADOS] PRIMARY KEY CLUSTERED ([ASE_CODEMP] ASC, [ASE_ANIO] ASC, [ASE_TIPO] ASC, [ASE_NUMERO] ASC, [ASE_ESTADO] ASC, [ASE_FECHA] ASC),
    CONSTRAINT [CKC_ASE_TIPO_ASIENTOS] CHECK ([ASE_TIPO]='A' OR [ASE_TIPO]='T' OR [ASE_TIPO]='E' OR [ASE_TIPO]='I'),
    CONSTRAINT [FK_ASIENTOS_ASICONT_E_ASIENTOS] FOREIGN KEY ([ASE_CODEMP], [ASE_ANIO], [ASE_TIPO], [ASE_NUMERO]) REFERENCES [dbo].[ASIENTOS_CONTABLES] ([AST_CODEMP], [AST_ANIO], [AST_TIPO], [AST_NUMERO]),
    CONSTRAINT [FK_ASIENTOS_USUA_ASIE_USUARIOS] FOREIGN KEY ([ASE_CODEMP], [ASE_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ASIENTOS_CONTABLES_ESTADOS]([ASE_CODEMP] ASC, [ASE_ANIO] ASC, [ASE_TIPO] ASC, [ASE_NUMERO] ASC, [ASE_ESTADO] ASC, [ASE_FECHA] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las modificaciones realizadas al asiento contable y el dia y la persona la cual realizo la modificacion sobre el asiento contable', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASIENTOS_CONTABLES_ESTADOS';

