CREATE TABLE [dbo].[BORRADOR_TIPO] (
    [CODEMP]                 INT          NOT NULL,
    [TIPO_BORRADOR]          INT          IDENTITY (1, 1) NOT NULL,
    [DESC_TIPO_BORRADOR]     VARCHAR (50) NOT NULL,
    [FECHA_CREACION]         DATETIME     NOT NULL,
    [USER_CREACION]          INT          NOT NULL,
    [FECHA_ULT_MODIFICACION] DATETIME     NOT NULL,
    [USER_ULT_MODIFICACION]  INT          NOT NULL,
    CONSTRAINT [PK_BORRADOR_TIPO] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [TIPO_BORRADOR] ASC),
    CONSTRAINT [FK_BORRADOR_TIPO_USUARIO_C] FOREIGN KEY ([CODEMP], [USER_CREACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID]),
    CONSTRAINT [FK_BORRADOR_TIPO_USUARIO_M] FOREIGN KEY ([CODEMP], [USER_ULT_MODIFICACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);

