CREATE TABLE [dbo].[BORRADOR_VERSION] (
    [CODEMP]                 INT         NOT NULL,
    [ID_BORRADOR]            INT         NOT NULL,
    [ID_VERSION]             INT         IDENTITY (1, 1) NOT NULL,
    [TEMPLATE]               TEXT        NOT NULL,
    [FECHA_CREACION]         DATETIME    NOT NULL,
    [USER_CREACION]          INT         NOT NULL,
    [FECHA_ULT_MODIFICACION] DATETIME    NOT NULL,
    [USER_ULT_MODIFICACION]  INT         NOT NULL,
    [ESTADO]                 VARCHAR (2) NOT NULL,
    CONSTRAINT [PK_BORRADOR_VERSION] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_BORRADOR] ASC, [ID_VERSION] ASC),
    CONSTRAINT [FK_BORRADOR_VERSION_BORRADOR] FOREIGN KEY ([CODEMP], [ID_BORRADOR]) REFERENCES [dbo].[BORRADOR] ([CODEMP], [ID_BORRADOR]),
    CONSTRAINT [FK_BORRADOR_VERSION_USUARIO_C] FOREIGN KEY ([CODEMP], [USER_CREACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID]),
    CONSTRAINT [FK_BORRADOR_VERSION_USUARIO_M] FOREIGN KEY ([CODEMP], [USER_ULT_MODIFICACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);

