CREATE TABLE [dbo].[BORRADOR] (
    [CODEMP]                 INT          NOT NULL,
    [ID_BORRADOR]            INT          IDENTITY (1, 1) NOT NULL,
    [DESC_BORRADOR]          VARCHAR (50) NOT NULL,
    [TIPO_BORRADOR]          INT          NOT NULL,
    [ORDEN]                  INT          NOT NULL,
    [FECHA_CREACION]         DATETIME     NOT NULL,
    [USER_CREACION]          INT          NOT NULL,
    [FECHA_ULT_MODIFICACION] DATETIME     NOT NULL,
    [USER_ULT_MODIFICACION]  INT          NOT NULL,
    [ESTADO]                 VARCHAR (2)  NOT NULL,
    [AREA]                   VARCHAR (3)  NOT NULL,
    CONSTRAINT [PK_BORRADOR] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_BORRADOR] ASC),
    CONSTRAINT [FK_BORRADOR_TIPO_BORRADOR] FOREIGN KEY ([CODEMP], [TIPO_BORRADOR]) REFERENCES [dbo].[BORRADOR_TIPO] ([CODEMP], [TIPO_BORRADOR]),
    CONSTRAINT [FK_BORRADOR_USUARIO_C] FOREIGN KEY ([CODEMP], [USER_CREACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID]),
    CONSTRAINT [FK_BORRADOR_USUARIO_M] FOREIGN KEY ([CODEMP], [USER_ULT_MODIFICACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);

