CREATE TABLE [dbo].[CABACERA_COMPROBANTES_ESTADOS] (
    [CBE_CODEMP]     INT          NOT NULL,
    [CBE_SUCID]      INT          NOT NULL,
    [CBE_TPCID]      INT          NOT NULL,
    [CBE_NUMERO]     NUMERIC (15) NOT NULL,
    [CBE_ESTADO]     CHAR (1)     NOT NULL,
    [CBE_FECHA]      DATETIME     NOT NULL,
    [CBE_USRID]      INT          NOT NULL,
    [CBE_IPPC]       VARCHAR (20) NOT NULL,
    [CBE_IPRED]      VARCHAR (20) NOT NULL,
    [CBE_COMENTARIO] TEXT         NULL,
    CONSTRAINT [PK_CABACERA_COMPROBANTES_ESTAD] PRIMARY KEY CLUSTERED ([CBE_CODEMP] ASC, [CBE_SUCID] ASC, [CBE_TPCID] ASC, [CBE_NUMERO] ASC, [CBE_ESTADO] ASC, [CBE_FECHA] ASC),
    CONSTRAINT [FK_CABACERA_CABCPNT_E_CABACERA] FOREIGN KEY ([CBE_CODEMP], [CBE_SUCID], [CBE_TPCID], [CBE_NUMERO]) REFERENCES [dbo].[CABACERA_COMPROBANTES] ([CBC_CODEMP], [CBC_SUCID], [CBC_TPCID], [CBC_NUMERO]),
    CONSTRAINT [FK_CABACERA_USU_CPBTE_USUARIOS] FOREIGN KEY ([CBE_CODEMP], [CBE_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CABACERA_COMPROBANTES_ESTADOS]([CBE_CODEMP] ASC, [CBE_SUCID] ASC, [CBE_TPCID] ASC, [CBE_NUMERO] ASC, [CBE_ESTADO] ASC, [CBE_FECHA] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos estados que ha sufrido el cpbt', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CABACERA_COMPROBANTES_ESTADOS';

