CREATE TABLE [dbo].[CAJA_CONDICION_FACTURACION_DETALLE] (
    [CONDICION_DETALLE_ID]    INT             NOT NULL,
    [CONDICION_ID]            INT             NOT NULL,
    [CAMPO_VARIABLE_COMPARAR] VARCHAR (20)    NOT NULL,
    [OPERADOR]                VARCHAR (2)     NOT NULL,
    [MONTO_COMPARADOR]        DECIMAL (15, 2) NOT NULL,
    [USRID_REGISTRO]          INT             NOT NULL,
    [FEC_REGISTRO]            DATETIME        CONSTRAINT [DF_CAJA_CONDICION_FACTURACION_DETALLE_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CAJA_CONDICION_FACTURACION_DETALLE] PRIMARY KEY CLUSTERED ([CONDICION_ID] ASC, [CONDICION_DETALLE_ID] ASC),
    CONSTRAINT [FK_CAJA_CONDICION_FACTURACION_DETALLE_CAJA_CONDICION_FACTURACION] FOREIGN KEY ([CONDICION_ID]) REFERENCES [dbo].[CAJA_CONDICION_FACTURACION] ([CONDICION_ID])
);

