CREATE TABLE [dbo].[CAJA_RECEPCION_DOCUMENTOS] (
    [DOCUMENTO_ID]          INT             NOT NULL,
    [CODEMP]                INT             NOT NULL,
    [REC]                   VARCHAR (20)    NOT NULL,
    [PCLID]                 NUMERIC (15)    NOT NULL,
    [CTCID]                 NUMERIC (15)    NOT NULL,
    [SBCID]                 INT             NULL,
    [CODMON]                INT             NOT NULL,
    [MONTO_INGRESO]         DECIMAL (15, 2) CONSTRAINT [DF_CAJA_RECEPCION_DOCUMENTOS_MONTO_INGRESO] DEFAULT ((0)) NOT NULL,
    [ESTATUS_ID]            INT             CONSTRAINT [DF_CAJA_RECEPCION_DOCUMENTOS_ESTATUS_ID] DEFAULT ((1)) NOT NULL,
    [CRITERIO_ID]           INT             NULL,
    [MONTO_FACTURAR]        DECIMAL (15, 2) NULL,
    [OBSERVACIONES]         VARCHAR (500)   NULL,
    [NUM_FACT]              VARCHAR (20)    NULL,
    [USRID_REGISTRO]        INT             NOT NULL,
    [FEC_REGISTRO]          DATETIME        CONSTRAINT [DF_CAJA_RECEPCION_DOCUMENTOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [OBSERVACIONES_FACTURA] VARCHAR (500)   NULL,
    [VALOR_INGRESO]         DECIMAL (15, 2) NULL,
    [SALDO]                 DECIMAL (15, 2) NOT NULL,
    CONSTRAINT [PK_CAJA_RECEPCION_DOCUMENTOS] PRIMARY KEY CLUSTERED ([DOCUMENTO_ID] ASC),
    CONSTRAINT [FK_CAJA_RECEPCION_DOCUMENTOS_CAJA_CRITERIO_FACTURACION] FOREIGN KEY ([CRITERIO_ID]) REFERENCES [dbo].[CAJA_CRITERIO_FACTURACION] ([CRITERIO_ID]),
    CONSTRAINT [FK_CAJA_RECEPCION_DOCUMENTOS_CAJA_DOCUMENTOS_ESTATUS] FOREIGN KEY ([ESTATUS_ID]) REFERENCES [dbo].[CAJA_DOCUMENTOS_ESTATUS] ([ESTATUS_ID])
);

