CREATE TABLE [dbo].[CAJA_CONDICION_FACTURACION] (
    [CONDICION_ID]   INT           NOT NULL,
    [CODEMP]         INT           NOT NULL,
    [DESCRIPCION]    VARCHAR (100) NULL,
    [USRID_REGISTRO] INT           NOT NULL,
    [FEC_REGISTRO]   DATETIME      CONSTRAINT [DF_CAJA_CONDICION_FACTURACION_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CAJA_CONDICION_FACTURACION] PRIMARY KEY CLUSTERED ([CONDICION_ID] ASC)
);

