CREATE TABLE [dbo].[CAJA_DOCUMENTOS_ESTATUS] (
    [ESTATUS_ID]  INT          NOT NULL,
    [CODEMP]      INT          NOT NULL,
    [DESCRIPCION] VARCHAR (30) NULL,
    CONSTRAINT [PK_CAJA_DOCUMENTOS_ESTATUS] PRIMARY KEY CLUSTERED ([ESTATUS_ID] ASC)
);

