CREATE TABLE [dbo].[CAJA_RECEPCION_DOCUMENTOS_HISTORIAL] (
    [HISTORIAL_ID]   INT             NOT NULL,
    [DOCUMENTO_ID]   INT             NOT NULL,
    [CODEMP]         INT             NOT NULL,
    [REC]            VARCHAR (20)    NOT NULL,
    [PCLID]          NUMERIC (15)    NOT NULL,
    [CTCID]          NUMERIC (15)    NOT NULL,
    [SBCID]          INT             NULL,
    [CODMON]         INT             NOT NULL,
    [MONTO_INGRESO]  DECIMAL (15, 2) NOT NULL,
    [ESTATUS_ID]     INT             NOT NULL,
    [CRITERIO_ID]    INT             NULL,
    [MONTO_FACTURAR] DECIMAL (15, 2) NULL,
    [OBSERVACIONES]  VARCHAR (500)   NULL,
    [NUM_FACT]       VARCHAR (20)    NULL,
    [USRID_REGISTRO] INT             NOT NULL,
    [FEC_REGISTRO]   DATETIME        CONSTRAINT [DF_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL] PRIMARY KEY CLUSTERED ([HISTORIAL_ID] ASC),
    CONSTRAINT [FK_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_CAJA_CRITERIO_FACTURACION] FOREIGN KEY ([CRITERIO_ID]) REFERENCES [dbo].[CAJA_CRITERIO_FACTURACION] ([CRITERIO_ID]),
    CONSTRAINT [FK_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_CAJA_DOCUMENTOS_ESTATUS] FOREIGN KEY ([ESTATUS_ID]) REFERENCES [dbo].[CAJA_DOCUMENTOS_ESTATUS] ([ESTATUS_ID])
);

