CREATE TABLE [dbo].[CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_ESTATUS] (
    [HISTORIAL_ESTATUS_ID] INT      NOT NULL,
    [DOCUMENTO_ID]         INT      NOT NULL,
    [ESTATUS_ID]           INT      NOT NULL,
    [USRID_CREACION]       INT      NOT NULL,
    [FEC_CREACION]         DATETIME CONSTRAINT [DF_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_ESTATUS_FEC_CREACION] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CAJA_RECEPCION_DOCUMENTOS_HISTORIAL_ESTATUS] PRIMARY KEY CLUSTERED ([HISTORIAL_ESTATUS_ID] ASC)
);

