CREATE TABLE [dbo].[CAJA_COMPENSACION] (
    [CJC_CODEMP] INT           NOT NULL,
    [CJC_CJCID]  INT           NOT NULL,
    [CJC_RUT]    VARCHAR (20)  NOT NULL,
    [CJC_NOMBRE] VARCHAR (150) NOT NULL,
    [CJC_PCTID]  INT           NOT NULL,
    CONSTRAINT [PK_CAJA_COMPENSACION] PRIMARY KEY NONCLUSTERED ([CJC_CODEMP] ASC, [CJC_CJCID] ASC),
    CONSTRAINT [FK_CAJA_COM_EMPRESA_C_EMPRESA] FOREIGN KEY ([CJC_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CAJA_COMPENSACION]([CJC_CODEMP] ASC, [CJC_CJCID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_RUT]
    ON [dbo].[CAJA_COMPENSACION]([CJC_CODEMP] ASC, [CJC_RUT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas cajas de compensacion', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CAJA_COMPENSACION';

