CREATE TABLE [dbo].[CARTERA_CLIENTES_CPBT_DOC_EXTENDIDO] (
    [CCB_CODEMP]          NUMERIC (15)  NOT NULL,
    [CCB_PCLID]           NUMERIC (15)  NOT NULL,
    [CCB_CTCID]           INT           NOT NULL,
    [CCB_CCBID]           INT           NOT NULL,
    [NUM_RESOLUCION]      VARCHAR (20)  NOT NULL,
    [FEC_RESOLUCION]      DATETIME      NULL,
    [RUT_REPRESENTANTE_1] VARCHAR (20)  NULL,
    [NOM_REPRESENTANTE_1] VARCHAR (100) NULL,
    [RUT_REPRESENTANTE_2] VARCHAR (20)  NULL,
    [NOM_REPRESENTANTE_2] VARCHAR (100) NULL,
    [RUT_REPRESENTANTE_3] VARCHAR (20)  NULL,
    [NOM_REPRESENTANTE_3] VARCHAR (100) NULL,
    [FEC_CARGA]           DATETIME      NULL,
    CONSTRAINT [PK_CARTERA_CLIENTES_CPBT_DOC_EXTENDIDO] PRIMARY KEY CLUSTERED ([CCB_CODEMP] ASC, [CCB_PCLID] ASC, [CCB_CTCID] ASC, [CCB_CCBID] ASC),
    CONSTRAINT [FK_CARTERA_CLIENTES_CPBT_DOC_EXTENDIDO_CARTERA_CLIENTES_CPBT_DOC_EXTENDIDO] FOREIGN KEY ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC_EXTENDIDO] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID])
);

