CREATE TABLE [dbo].[CARTERA_CLIENTES_ESTADOS_HISTORIAL] (
    [CEH_CODEMP]     INT             NOT NULL,
    [CEH_PCLID]      NUMERIC (15)    NOT NULL,
    [CEH_CTCID]      NUMERIC (15)    NOT NULL,
    [CEH_CCBID]      INT             NOT NULL,
    [CEH_FECHA]      DATETIME        NOT NULL,
    [CEH_ESTID]      SMALLINT        NOT NULL,
    [CEH_SUCID]      INT             NOT NULL,
    [CEH_GESID]      INT             NULL,
    [CEH_IPRED]      VARCHAR (30)    NOT NULL,
    [CEH_IPMAQUINA]  VARCHAR (30)    NOT NULL,
    [CEH_COMENTARIO] TEXT            NULL,
    [CEH_MONTO]      DECIMAL (15, 2) NULL,
    [CEH_SALDO]      DECIMAL (15, 2) NULL,
    [CEH_USRID]      INT             NOT NULL,
    CONSTRAINT [PK_CARTERA_CLIENTES_ESTADOS_HI] PRIMARY KEY NONCLUSTERED ([CEH_CODEMP] ASC, [CEH_PCLID] ASC, [CEH_CTCID] ASC, [CEH_CCBID] ASC, [CEH_FECHA] ASC, [CEH_ESTID] ASC),
    CONSTRAINT [FK_CARTERA__GEST_CCES_GESTOR] FOREIGN KEY ([CEH_CODEMP], [CEH_SUCID], [CEH_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_CARTERA__GESTOR_CC_GESTOR] FOREIGN KEY ([CEH_CODEMP], [CEH_SUCID], [CEH_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_CARTERA__REFERENCE_CARTERA_4] FOREIGN KEY ([CEH_CODEMP], [CEH_PCLID], [CEH_CTCID], [CEH_CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_CARTERA__REFERENCE_ESTADOS_2] FOREIGN KEY ([CEH_CODEMP], [CEH_ESTID]) REFERENCES [dbo].[ESTADOS_CARTERA] ([ECT_CODEMP], [ECT_ESTID]),
    CONSTRAINT [FK_CARTERA__REFERENCE_GESTOR2] FOREIGN KEY ([CEH_CODEMP], [CEH_SUCID], [CEH_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_CARTERA__USU_CARTC_USUARIOS] FOREIGN KEY ([CEH_CODEMP], [CEH_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CARTERA_CLIENTES_ESTADOS_HISTORIAL]([CEH_CODEMP] ASC, [CEH_PCLID] ASC, [CEH_CTCID] ASC, [CEH_CCBID] ASC, [CEH_FECHA] ASC, [CEH_ESTID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos cambios de estados producidos en la cartera', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CARTERA_CLIENTES_ESTADOS_HISTORIAL';

