CREATE TABLE [dbo].[CARTOLA_MOVIMIENTOS] (
    [MOVIMIENTO_ID]            INT             NOT NULL,
    [CODEMP]                   INT             NOT NULL,
    [NUM_CUENTA]               VARCHAR (60)    NULL,
    [FEC_MOVIMIENTO]           DATETIME        NOT NULL,
    [MONTO]                    DECIMAL (15, 2) CONSTRAINT [DF_CARTOLA_MOVIMIENTOS_MONTO] DEFAULT ((0)) NOT NULL,
    [SUCURSAL]                 VARCHAR (100)   NULL,
    [NUM_COMPROBANTE_REF]      VARCHAR (100)   NULL,
    [TIPO_MOVIMIENTO_BANCO_ID] INT             NOT NULL,
    [TIPO_MOTIVO_BANCO_ID]     INT             NOT NULL,
    [TIPO_ESTADO_BANCO_ID]     INT             NOT NULL,
    [ESTATUS_ID]               INT             CONSTRAINT [DF_CARTOLA_MOVIMIENTOS_ESTATUS_ID] DEFAULT ((1)) NOT NULL,
    [EXCEL_ROW_ID]             INT             NOT NULL,
    [USRID_REGISTRO]           INT             NOT NULL,
    [FEC_REGISTRO]             DATETIME        CONSTRAINT [DF_CARTOLA_MOVIMIENTOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [OBSERVACION]              VARCHAR (100)   NULL,
    CONSTRAINT [PK_CARTOLA_MOVIMIENTOS] PRIMARY KEY CLUSTERED ([MOVIMIENTO_ID] ASC),
    CONSTRAINT [FK_CARTOLA_MOVIMIENTOS_CARTOLA_BANCO_EXCEL] FOREIGN KEY ([EXCEL_ROW_ID]) REFERENCES [dbo].[CARTOLA_BANCO_EXCEL] ([EXCEL_ROW_ID]),
    CONSTRAINT [FK_CARTOLA_MOVIMIENTOS_CARTOLA_MOVIMIENTOS_TIPO_ESTATUS] FOREIGN KEY ([ESTATUS_ID]) REFERENCES [dbo].[CARTOLA_MOVIMIENTOS_TIPO_ESTATUS] ([ESTATUS_ID]),
    CONSTRAINT [FK_CARTOLA_MOVIMIENTOS_TESORERIA_TIPO_ESTADO_BANCO] FOREIGN KEY ([TIPO_ESTADO_BANCO_ID]) REFERENCES [dbo].[TESORERIA_TIPO_ESTADO_BANCO] ([TIPO_ESTADO_BANCO_ID]),
    CONSTRAINT [FK_CARTOLA_MOVIMIENTOS_TESORERIA_TIPO_MOTIVO_BANCO] FOREIGN KEY ([TIPO_MOTIVO_BANCO_ID]) REFERENCES [dbo].[TESORERIA_TIPO_MOTIVO_BANCO] ([TIPO_MOTIVO_BANCO_ID]),
    CONSTRAINT [FK_CARTOLA_MOVIMIENTOS_TESORERIA_TIPO_MOVIMIENTO_BANCO] FOREIGN KEY ([TIPO_MOVIMIENTO_BANCO_ID]) REFERENCES [dbo].[TESORERIA_TIPO_MOVIMIENTO_BANCO] ([TIPO_MOVIMIENTO_BANCO_ID])
);

