CREATE TABLE [dbo].[CARTOLA_BANCO_EXCEL_CARGA] (
    [IDCARGA]        INT           NOT NULL,
    [ARCHIVO]        VARCHAR (100) NOT NULL,
    [USRID_DESCARGA] INT           NOT NULL,
    [FEC_DESCARGA]   DATETIME      CONSTRAINT [DF_CARTOLA_BANCO_EXCEL_CARGA_FEC_DESCARGA] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CARTOLA_BANCO_EXCEL_CARGA] PRIMARY KEY CLUSTERED ([IDCARGA] ASC)
);

