CREATE TABLE [dbo].[CARTOLA_BANCO_EXCEL] (
    [EXCEL_ROW_ID]        INT             NOT NULL,
    [NUM_CUENTA]          VARCHAR (60)    NOT NULL,
    [FEC_MOVIMIENTO]      DATETIME        NOT NULL,
    [MONTO]               DECIMAL (15, 2) CONSTRAINT [DF_CARTOLA_BANCO_EXCEL_MONTO] DEFAULT ((0)) NOT NULL,
    [DESCRIPCION]         VARCHAR (200)   NOT NULL,
    [SUCURSAL]            VARCHAR (100)   NULL,
    [NUM_COMPROBANTE_REF] VARCHAR (100)   NULL,
    [IDCARGA]             INT             NOT NULL,
    [PROCESADO]           VARCHAR (1)     CONSTRAINT [DF_CARTOLA_BANCO_EXCEL_PROCESADO] DEFAULT ('N') NOT NULL,
    [USRID_REGISTRO]      INT             NOT NULL,
    [FEC_REGISTRO]        DATETIME        CONSTRAINT [DF_CARTOLA_BANCO_EXCEL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CARTOLA_BANCO_EXCEL] PRIMARY KEY CLUSTERED ([EXCEL_ROW_ID] ASC),
    CONSTRAINT [CKC_CARTOLA_BANCO_EXCEL_PROCESADO] CHECK ([PROCESADO]='N' OR [PROCESADO]='S')
);

