CREATE TABLE [dbo].[CARTERA_CLIENTES_CPBT_DOC_TERCEROS] (
    [CODEMP]    INT           NOT NULL,
    [TERCEROID] INT           NOT NULL,
    [RUT]       VARCHAR (20)  NOT NULL,
    [NOMBRE]    VARCHAR (400) NOT NULL,
    CONSTRAINT [PK_CARTERA_CLIENTES_CPBT_DOC_TERCEROS] PRIMARY KEY NONCLUSTERED ([CODEMP] ASC, [TERCEROID] ASC),
    CONSTRAINT [FK_CARTERA_CLIENTES_CPBT_DOC_TERCEROS_EMPRESA] FOREIGN KEY ([CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);

