CREATE TABLE [dbo].[CARTERA_CLIENTES_ESTADOS_SITREL] (
    [CODEMP]               INT             NOT NULL,
    [PCLID]                NUMERIC (15)    NOT NULL,
    [CTCID]                NUMERIC (15)    NOT NULL,
    [FECHA]                DATETIME        NOT NULL,
    [ACCID]                INT             NOT NULL,
    [CODIGO_MONEDA]        VARCHAR (20)    NULL,
    [CODIGO_EMPRESA]       VARCHAR (6)     NOT NULL,
    [CODIGO_ACCION]        VARCHAR (20)    NULL,
    [CODIGO_CONTACTO]      VARCHAR (20)    NULL,
    [CODIGO_RESPUESTA]     VARCHAR (20)    NULL,
    [GLOSA_GESTION]        VARCHAR (255)   NULL,
    [FECHA_COMPROMISO]     VARCHAR (8)     NULL,
    [MONTO_COMPROMISO]     DECIMAL (15, 2) NULL,
    [MONTO_GESTION]        DECIMAL (15, 2) NULL,
    [NOMBRE_CONTACTO]      VARCHAR (255)   NULL,
    [PROGRAMACION_LLAMADA] VARCHAR (15)    NULL,
    [TELEFONO_CONTACTO]    VARCHAR (20)    NULL,
    CONSTRAINT [PK_CARTERA_CLIENTES_ESTADOS_SITREL] PRIMARY KEY NONCLUSTERED ([CODEMP] ASC, [PCLID] ASC, [CTCID] ASC, [FECHA] ASC, [ACCID] ASC),
    CONSTRAINT [FK_CARTERA__ACCIONES__SITREL] FOREIGN KEY ([CODEMP], [ACCID]) REFERENCES [dbo].[ACCIONES] ([ACC_CODEMP], [ACC_ACCID])
);


GO
CREATE NONCLUSTERED INDEX [CCES_FECHA]
    ON [dbo].[CARTERA_CLIENTES_ESTADOS_SITREL]([CODEMP] ASC, [PCLID] ASC, [FECHA] ASC);


GO
CREATE NONCLUSTERED INDEX [_dta_index_CARTERA_CLIENTES_ESTADOS_SITREL_5_567061156__K1_K4_K3_7_8_9_10_11_12_13_14_15_16_17]
    ON [dbo].[CARTERA_CLIENTES_ESTADOS_SITREL]([CODEMP] ASC, [FECHA] ASC, [CTCID] ASC)
    INCLUDE([CODIGO_EMPRESA], [CODIGO_ACCION], [CODIGO_CONTACTO], [CODIGO_RESPUESTA], [GLOSA_GESTION], [FECHA_COMPROMISO], [MONTO_COMPROMISO], [MONTO_GESTION], [NOMBRE_CONTACTO], [PROGRAMACION_LLAMADA], [TELEFONO_CONTACTO]);

