CREATE TABLE [dbo].[CARTERA_CLIENTES_ESTADOS_ACCIONES_CM] (
    [CEA_CODEMP]     INT          NOT NULL,
    [CEA_PCLID]      NUMERIC (15) NOT NULL,
    [CEA_CTCID]      NUMERIC (15) NOT NULL,
    [CEA_FECHA]      DATETIME     NOT NULL,
    [CEA_ACCID]      INT          NOT NULL,
    [CEA_SUCID]      INT          NOT NULL,
    [CEA_GESID]      INT          NULL,
    [CEA_CONTACTO]   CHAR (1)     NOT NULL,
    [CEA_IPRED]      VARCHAR (30) NOT NULL,
    [CEA_IPMAQUINA]  VARCHAR (30) NOT NULL,
    [CEA_COMENTARIO] TEXT         NOT NULL,
    [CEA_ESTADO]     CHAR (1)     NOT NULL,
    [CEA_USRID]      INT          NOT NULL,
    [CEA_DDCID]      SMALLINT     NULL,
    [CEA_TELEFONO]   INT          NULL,
    CONSTRAINT [PK_CARTERA_CLIENTES_ESTADOS_AC_CM] PRIMARY KEY NONCLUSTERED ([CEA_CODEMP] ASC, [CEA_PCLID] ASC, [CEA_CTCID] ASC, [CEA_FECHA] ASC, [CEA_ACCID] ASC)
);

