CREATE TABLE [dbo].[CASTIGO_DEVOLUCION_RECHAZO] (
    [CODEMP]          INT            NOT NULL,
    [TIPOCOMPROBANTE] INT            NOT NULL,
    [FOLIO]           INT            NOT NULL,
    [PCLID]           INT            NOT NULL,
    [MOTIVO]          VARCHAR (1000) NOT NULL,
    [USRID_REGISTRO]  INT            NOT NULL,
    [FEC_REGISTRO]    DATETIME       CONSTRAINT [DF_CASTIGO_DEVOLUCION_RECHAZO_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CASTIGO_DEVOLUCION_RECHAZO] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [TIPOCOMPROBANTE] ASC, [FOLIO] ASC, [PCLID] ASC)
);

