CREATE TABLE [dbo].[CATEGORIAS_IDIOMAS] (
    [CAI_CODEMP] INT           NOT NULL,
    [CAI_CATID]  INT           NOT NULL,
    [CAI_IDIID]  INT           NOT NULL,
    [CAI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_CATEGORIAS_IDIOMAS] PRIMARY KEY NONCLUSTERED ([CAI_CODEMP] ASC, [CAI_CATID] ASC, [CAI_IDIID] ASC),
    CONSTRAINT [FK_CATEGORI_CATEGORIA_CATEGORI] FOREIGN KEY ([CAI_CODEMP], [CAI_CATID]) REFERENCES [dbo].[CATEGORIAS] ([CAT_CODEMP], [CAT_CATID]),
    CONSTRAINT [FK_CATEGORI_IDIOMAS_C_IDIOMAS] FOREIGN KEY ([CAI_IDIID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CATEGORIAS_IDIOMAS]([CAI_CODEMP] ASC, [CAI_CATID] ASC, [CAI_IDIID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena, las distintas categorias en su respectivo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CATEGORIAS_IDIOMAS';

