CREATE TABLE [dbo].[CLAUSULAS_CONTCART_IDIOMAS] (
    [CLI_CODEMP] INT           NOT NULL,
    [CLI_CLCID]  INT           NOT NULL,
    [CLI_IDID]   INT           NOT NULL,
    [CLI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_CLAUSULAS_CONTCART_IDIOMAS] PRIMARY KEY CLUSTERED ([CLI_CODEMP] ASC, [CLI_CLCID] ASC, [CLI_IDID] ASC),
    CONSTRAINT [FK_CLAUSULA_CLAUCONT__CLAUSULA] FOREIGN KEY ([CLI_CODEMP], [CLI_CLCID]) REFERENCES [dbo].[CLAUSULAS_CONTCART] ([CLC_CODEMP], [CLC_CLCID]),
    CONSTRAINT [FK_CLAUSULA_IDIOMAS_C_IDIOMAS] FOREIGN KEY ([CLI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CLAUSULAS_CONTCART_IDIOMAS]([CLI_CODEMP] ASC, [CLI_CLCID] ASC, [CLI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintas clausulas en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLAUSULAS_CONTCART_IDIOMAS';

