CREATE TABLE [dbo].[CLAUSULAS_CONTCART_RANGOS] (
    [CLR_CODEMP] INT             NOT NULL,
    [CLR_CLCID]  INT             NOT NULL,
    [CLR_CLRID]  INT             NOT NULL,
    [CLR_REGID]  INT             NULL,
    [CLR_DESDE]  DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CLR_HASTA]  DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CLR_FECINI] DATETIME        NULL,
    [CLR_FECFIN] DATETIME        NULL,
    [CLR_VALOR]  DECIMAL (15, 3) NOT NULL,
    CONSTRAINT [PK_CLAUSULAS_CONTCART_RANGOS] PRIMARY KEY CLUSTERED ([CLR_CODEMP] ASC, [CLR_CLCID] ASC, [CLR_CLRID] ASC),
    CONSTRAINT [FK_CLAUSULA_CLAUCTRA__CLAUSULA] FOREIGN KEY ([CLR_CODEMP], [CLR_CLCID]) REFERENCES [dbo].[CLAUSULAS_CONTCART] ([CLC_CODEMP], [CLC_CLCID]),
    CONSTRAINT [FK_CLAUSULA_REGION_CL_REGION] FOREIGN KEY ([CLR_REGID]) REFERENCES [dbo].[REGION] ([REG_REGID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CLAUSULAS_CONTCART_RANGOS]([CLR_CODEMP] ASC, [CLR_CLCID] ASC, [CLR_CLRID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos rangos que seran creados para cada clausula, dependiendo de la cabecersa', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLAUSULAS_CONTCART_RANGOS';

