CREATE TABLE [dbo].[COMISIONES] (
    [CMS_CODEMP]    INT             NOT NULL,
    [CMS_SUCID]     INT             NOT NULL,
    [CMS_ANIO]      SMALLINT        NOT NULL,
    [CMS_MES]       SMALLINT        NOT NULL,
    [CMS_ITEM]      INT             NOT NULL,
    [CMS_GESID]     INT             NULL,
    [CMS_VDEID]     INT             NULL,
    [CMS_ANIOAPL]   INT             NULL,
    [CMS_NUMAPL]    NUMERIC (15)    NULL,
    [CMS_ITEMAPL]   INT             NULL,
    [CMS_TPCID]     INT             NULL,
    [CMS_NUMERO]    NUMERIC (15)    NULL,
    [CMS_TOTCPBT]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_CAPITAL]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_HONORARIO] DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_INTERES]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_GASTPRE]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_GASTJUD]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_PORCFCOB]  DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [CMS_PORCKI]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [CMS_PORCH]     DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [CMS_COMKI]     DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_COMH]      DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    [CMS_PORCJKI]   DECIMAL (10, 4) DEFAULT ((0)) NULL,
    [CMS_PORCJH]    DECIMAL (10, 4) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_COMISIONES] PRIMARY KEY CLUSTERED ([CMS_CODEMP] ASC, [CMS_SUCID] ASC, [CMS_ANIO] ASC, [CMS_MES] ASC, [CMS_ITEM] ASC),
    CONSTRAINT [FK_COMISION_APL_COMI_APLICACI] FOREIGN KEY ([CMS_CODEMP], [CMS_SUCID], [CMS_ANIOAPL], [CMS_NUMAPL], [CMS_ITEMAPL]) REFERENCES [dbo].[APLICACIONES_ITEMS] ([API_CODEMP], [API_SUCID], [API_ANIO], [API_NUMAPL], [API_ITEM]),
    CONSTRAINT [FK_COMISION_CABCPBT_C_CABACERA] FOREIGN KEY ([CMS_CODEMP], [CMS_SUCID], [CMS_TPCID], [CMS_NUMERO]) REFERENCES [dbo].[CABACERA_COMPROBANTES] ([CBC_CODEMP], [CBC_SUCID], [CBC_TPCID], [CBC_NUMERO]),
    CONSTRAINT [FK_COMISION_EMPSUC_CO_EMPRESA_] FOREIGN KEY ([CMS_CODEMP], [CMS_SUCID]) REFERENCES [dbo].[EMPRESA_SUCURSAL] ([ESU_CODEMP], [ESU_SUCID]),
    CONSTRAINT [FK_COMISION_GEST_COMI_GESTOR] FOREIGN KEY ([CMS_CODEMP], [CMS_SUCID], [CMS_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_COMISION_VEND_COMI_VENDEDOR] FOREIGN KEY ([CMS_CODEMP], [CMS_SUCID], [CMS_VDEID]) REFERENCES [dbo].[VENDEDORES] ([VDE_CODEMP], [VDE_SUCID], [VDE_VDEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[COMISIONES]([CMS_CODEMP] ASC, [CMS_SUCID] ASC, [CMS_ANIO] ASC, [CMS_MES] ASC, [CMS_ITEM] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacenara las distintas comisiones, ya sea de gestor o vendedor', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'COMISIONES';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Indica el año de la aplicacion', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'COMISIONES', @level2type = N'COLUMN', @level2name = N'CMS_ANIOAPL';

