CREATE TABLE [dbo].[CONCILIACION_MOVIMIENTOS_DOCUMENTOS] (
    [CONCILIACION_ID]        INT          NOT NULL,
    [MOVIMIENTO_ID]          INT          NULL,
    [NUM_COMPROBANTE]        INT          NOT NULL,
    [CUSTODIA_ID]            INT          NULL,
    [PCLID]                  NUMERIC (15) NOT NULL,
    [CTCID]                  NUMERIC (15) NOT NULL,
    [GESTORID]               INT          NOT NULL,
    [CONCILIACION_TIPO_ID]   INT          NOT NULL,
    [USRID_REGISTRO]         INT          NOT NULL,
    [FEC_REGISTRO]           DATETIME     CONSTRAINT [DF_CONCILIACION_MOVIMIENTOS_DOCUMENTOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [CONCILIACION_ESTADO_ID] INT          CONSTRAINT [DF_CONCILIACION_MOVIMIENTOS_ESTADO_ID] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CONCILIACION_MOVIMIENTOS_DOCUMENTOS] PRIMARY KEY CLUSTERED ([CONCILIACION_ID] ASC),
    CONSTRAINT [FK_CONCILIACION_MOVIMIENTOS_DOCUMENTOS_CARTOLA_MOVIMIENTOS] FOREIGN KEY ([MOVIMIENTO_ID]) REFERENCES [dbo].[CARTOLA_MOVIMIENTOS] ([MOVIMIENTO_ID]),
    CONSTRAINT [FK_CONCILIACION_MOVIMIENTOS_DOCUMENTOS_CONCILIACION_ESTADO] FOREIGN KEY ([CONCILIACION_ESTADO_ID]) REFERENCES [dbo].[CONCILIACION_ESTADO] ([CONCILIACION_ESTADO_ID]),
    CONSTRAINT [FK_CONCILIACION_MOVIMIENTOS_DOCUMENTOS_DOCUMENTOS_CUSTODIA] FOREIGN KEY ([CUSTODIA_ID]) REFERENCES [dbo].[DOCUMENTOS_CUSTODIA] ([CUSTODIA_ID])
);

