CREATE TABLE [dbo].[CONCILIACION_TIPO] (
    [CONCILIACION_TIPO_ID] INT          NOT NULL,
    [DESCRIPCION]          VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_CONCILIACION_TIPO] PRIMARY KEY CLUSTERED ([CONCILIACION_TIPO_ID] ASC)
);

