CREATE TABLE [dbo].[CONCILIACION_MOVIMIENTOS_ARCHIVOS] (
    [IMAGEN_ID]       INT           NOT NULL,
    [CONCILIACION_ID] INT           NOT NULL,
    [MOVIMIENTO_ID]   INT           NOT NULL,
    [NUM_COMPROBANTE] INT           NOT NULL,
    [PCLID]           NUMERIC (15)  NOT NULL,
    [CTCID]           NUMERIC (15)  NOT NULL,
    [PATH_ARCHIVO]    VARCHAR (400) NOT NULL,
    [USRID_REGISTRO]  INT           NOT NULL,
    [FEC_REGISTRO]    DATETIME      CONSTRAINT [DF_CONCILIACION_MOVIMIENTOS_ARCHIVOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CONCILIACION_MOVIMIENTOS_ARCHIVOS] PRIMARY KEY CLUSTERED ([IMAGEN_ID] ASC)
);

