CREATE TABLE [dbo].[CONCILIACION_ESTADO] (
    [CONCILIACION_ESTADO_ID] INT          NOT NULL,
    [DESCRIPCION]            VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_CONCILIACION_ESTADO_ID] PRIMARY KEY CLUSTERED ([CONCILIACION_ESTADO_ID] ASC)
);

