CREATE TABLE [dbo].[CONTRATOS_CARTERA_CLAUSULAS] (
    [CCL_CODEMP] INT NOT NULL,
    [CCL_CCTID]  INT NOT NULL,
    [CCL_CLCID]  INT NOT NULL,
    CONSTRAINT [PK_CONTRATOS_CARTERA_CLAUSULAS] PRIMARY KEY CLUSTERED ([CCL_CODEMP] ASC, [CCL_CCTID] ASC, [CCL_CLCID] ASC),
    CONSTRAINT [FK_CONTRATO_CLAU_CONT_CLAUSULA] FOREIGN KEY ([CCL_CODEMP], [CCL_CLCID]) REFERENCES [dbo].[CLAUSULAS_CONTCART] ([CLC_CODEMP], [CLC_CLCID]),
    CONSTRAINT [FK_CONTRATO_CONTCTERA_CONTRATO] FOREIGN KEY ([CCL_CODEMP], [CCL_CCTID]) REFERENCES [dbo].[CONTRATOS_CARTERA] ([CCT_CODEMP], [CCT_CCTID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[CONTRATOS_CARTERA_CLAUSULAS]([CCL_CODEMP] ASC, [CCL_CCTID] ASC, [CCL_CLCID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas clausulas que utilizara cada contrato', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CONTRATOS_CARTERA_CLAUSULAS';

