CREATE TABLE [dbo].[COPEC_TIPO_JUICIO] (
    [CTJ_CTJID]  INT NOT NULL,
    [CTJ_CODEMP] INT NOT NULL,
    [CTJ_ESJID]  INT NOT NULL,
    CONSTRAINT [PK_COPEC_TIPO_JUICIO] PRIMARY KEY CLUSTERED ([CTJ_CTJID] ASC, [CTJ_CODEMP] ASC, [CTJ_ESJID] ASC)
);

