CREATE TABLE [dbo].[COPEC_TIPO_COBRANZA_DOC] (
    [CCD_CCDID]  INT NOT NULL,
    [CCD_CODEMP] INT NOT NULL,
    [CCD_TPCID]  INT NOT NULL,
    CONSTRAINT [PK_COPEC_TIPO_COBRANZA_DOC] PRIMARY KEY CLUSTERED ([CCD_CCDID] ASC, [CCD_CODEMP] ASC, [CCD_TPCID] ASC)
);

