CREATE TABLE [dbo].[COPEC_ESTADO_JUICIO] (
    [CES_CESID]  INT           NOT NULL,
    [CES_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_COPEC_ESTADO_JUICIO] PRIMARY KEY CLUSTERED ([CES_CESID] ASC)
);

