CREATE TABLE [dbo].[CORTE] (
    [ID_CORTE]       INT          NOT NULL,
    [ID_COMPETENCIA] INT          NOT NULL,
    [CODEMP]         INT          NOT NULL,
    [NOMBRE]         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Corte] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_COMPETENCIA] ASC, [ID_CORTE] ASC),
    CONSTRAINT [FK_CORTE_COMPETENCIA] FOREIGN KEY ([ID_COMPETENCIA]) REFERENCES [dbo].[COMPETENCIA] ([ID_COMPETENCIA])
);

