CREATE TABLE [dbo].[DESPACHOS_DOCUMENTOS_ESTADOS] (
    [DDE_CODEMP]     INT          NOT NULL,
    [DDE_SUCID]      INT          NOT NULL,
    [DDE_DPCID]      NUMERIC (15) NOT NULL,
    [DDE_TPCID]      INT          NOT NULL,
    [DDE_NUMERO]     NUMERIC (15) NOT NULL,
    [DDE_EDPID]      INT          NOT NULL,
    [DDE_FECHA]      DATETIME     NOT NULL,
    [DDE_COMENTARIO] TEXT         NULL,
    [DDE_USRID]      INT          NOT NULL,
    CONSTRAINT [PK_DESPACHOS_DOCUMENTOS_ESTADO] PRIMARY KEY CLUSTERED ([DDE_CODEMP] ASC, [DDE_SUCID] ASC, [DDE_DPCID] ASC, [DDE_TPCID] ASC, [DDE_NUMERO] ASC, [DDE_EDPID] ASC, [DDE_FECHA] ASC),
    CONSTRAINT [FK_DESPACHO_DESPDOC_E_DESPACHO] FOREIGN KEY ([DDE_CODEMP], [DDE_SUCID], [DDE_DPCID], [DDE_TPCID], [DDE_NUMERO]) REFERENCES [dbo].[DESPACHOS_DOCUMENTOS] ([DCD_CODEMP], [DCD_SUCID], [DCD_DPCID], [DCD_TPCID], [DCD_NUMERO]),
    CONSTRAINT [FK_DESPACHO_ESTDESP_D_ESTADOS_] FOREIGN KEY ([DDE_CODEMP], [DDE_EDPID]) REFERENCES [dbo].[ESTADOS_DESPACHOS] ([EDP_CODEMP], [EDP_EDPID]),
    CONSTRAINT [FK_DESPACHO_USU_DESPD_USUARIOS] FOREIGN KEY ([DDE_CODEMP], [DDE_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DESPACHOS_DOCUMENTOS_ESTADOS]([DDE_CODEMP] ASC, [DDE_SUCID] ASC, [DDE_DPCID] ASC, [DDE_TPCID] ASC, [DDE_NUMERO] ASC, [DDE_EDPID] ASC, [DDE_FECHA] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos estados de los documentos que se estan despachando... dependiendo de la fecha y el estado', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DESPACHOS_DOCUMENTOS_ESTADOS';

