CREATE TABLE [dbo].[DETALLE_COMPROBANTES_ROL] (
    [DCR_CODEMP]  INT             NOT NULL,
    [DCR_SUCID]   INT             NOT NULL,
    [DCR_TPCID]   INT             NOT NULL,
    [DCR_NUMERO]  NUMERIC (15)    NOT NULL,
    [DCR_ITEM]    SMALLINT        NOT NULL,
    [DCR_ROLID]   INT             NOT NULL,
    [DCR_SUBITEM] SMALLINT        NOT NULL,
    [DCR_MONTO]   DECIMAL (15, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DETALLE_COMPROBANTES_ROL] PRIMARY KEY CLUSTERED ([DCR_CODEMP] ASC, [DCR_SUCID] ASC, [DCR_TPCID] ASC, [DCR_NUMERO] ASC, [DCR_ITEM] ASC, [DCR_ROLID] ASC, [DCR_SUBITEM] ASC),
    CONSTRAINT [FK_DETALLE__DETCPBT_R_DETALLE_] FOREIGN KEY ([DCR_CODEMP], [DCR_SUCID], [DCR_TPCID], [DCR_NUMERO], [DCR_ITEM]) REFERENCES [dbo].[DETALLE_COMPROBANTES] ([DCC_CODEMP], [DCC_SUCID], [DCC_TPCID], [DCC_NUMERO], [DCC_ITEM]),
    CONSTRAINT [FK_DETALLE__ROL_DETCP_ROL] FOREIGN KEY ([DCR_CODEMP], [DCR_ROLID]) REFERENCES [dbo].[ROL] ([ROL_CODEMP], [ROL_ROLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DETALLE_COMPROBANTES_ROL]([DCR_CODEMP] ASC, [DCR_SUCID] ASC, [DCR_TPCID] ASC, [DCR_NUMERO] ASC, [DCR_ITEM] ASC, [DCR_ROLID] ASC, [DCR_SUBITEM] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena el item que se ingreso, indicando a que ROL afectara', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DETALLE_COMPROBANTES_ROL';

