CREATE TABLE [dbo].[DEUDORES_CONTACTOS_TELEFONOS] (
    [DCT_CODEMP]    INT          NOT NULL,
    [DCT_CTCID]     NUMERIC (15) NOT NULL,
    [DCT_DDCID]     SMALLINT     NOT NULL,
    [DCT_NUMERO]    NUMERIC (12) NOT NULL,
    [DCT_TIPO]      CHAR (1)     NOT NULL,
    [DCT_ESTADO]    CHAR (1)     CONSTRAINT [DF__DEUDORES___DCT_E__2704CA5F] DEFAULT ('A') NOT NULL,
    [DCT_PRIORIDAD] SMALLINT     CONSTRAINT [DF__DEUDORES___DCT_P__3C55B857] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_DEUDORES_CONTACTOS_TELEFONO] PRIMARY KEY CLUSTERED ([DCT_CODEMP] ASC, [DCT_CTCID] ASC, [DCT_DDCID] ASC, [DCT_NUMERO] ASC),
    CONSTRAINT [CKC_DCT_ESTADO_DEUDORES] CHECK ([DCT_ESTADO]='M' OR [DCT_ESTADO]='C' OR [DCT_ESTADO]='A'),
    CONSTRAINT [CKC_DCT_TIPO_DEUDORES] CHECK ([DCT_TIPO]='F' OR [DCT_TIPO]='O' OR [DCT_TIPO]='M' OR [DCT_TIPO]='C'),
    CONSTRAINT [FK_DEUDORES_DEUCONTA__DEUDORES] FOREIGN KEY ([DCT_CODEMP], [DCT_CTCID], [DCT_DDCID]) REFERENCES [dbo].[DEUDORES_CONTACTOS] ([DDC_CODEMP], [DDC_CTCID], [DDC_DDCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DEUDORES_CONTACTOS_TELEFONOS]([DCT_CODEMP] ASC, [DCT_CTCID] ASC, [DCT_DDCID] ASC, [DCT_NUMERO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos telefonos, para cada contacto', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEUDORES_CONTACTOS_TELEFONOS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Este campo indica si es un telefono fijo o movil', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEUDORES_CONTACTOS_TELEFONOS', @level2type = N'COLUMN', @level2name = N'DCT_TIPO';

