CREATE TABLE [dbo].[DEUDORES_CONTACTOS_MAIL_PROV] (
    [CODEMP] INT          NOT NULL,
    [CTCID]  NUMERIC (15) NOT NULL,
    [PCLID]  NUMERIC (15) NOT NULL,
    [DDCID]  SMALLINT     NOT NULL,
    [MAIL]   VARCHAR (80) NOT NULL,
    [TIPO]   CHAR (1)     DEFAULT ('P') NOT NULL,
    [MASIVO] CHAR (1)     DEFAULT ('S') NULL,
    [FECHA_CREACION] DATETIME NOT NULL, 
    [USERID] INT NOT NULL, 
    CONSTRAINT [PK_DEUDORES_CONTACTOS_MAIL_PROV] PRIMARY KEY CLUSTERED ([PCLID] ASC, [CODEMP] ASC, [CTCID] ASC, [DDCID] ASC, [MAIL] ASC),
    CONSTRAINT [FK_DEUDORES_CONTACTOS_MAIL_DEUDORES] FOREIGN KEY ([CODEMP], [CTCID], [DDCID]) REFERENCES [dbo].[DEUDORES_CONTACTOS] ([DDC_CODEMP], [DDC_CTCID], [DDC_DDCID]),
    CONSTRAINT [FK_DEUDORES_CONTACTOS_MAIL_PROV_DEUDORES_CONTACTOS_MAIL_PROV] FOREIGN KEY ([PCLID], [CODEMP], [CTCID], [DDCID], [MAIL]) REFERENCES [dbo].[DEUDORES_CONTACTOS_MAIL_PROV] ([PCLID], [CODEMP], [CTCID], [DDCID], [MAIL]),
    CONSTRAINT [FK_DEUDORES_CONTACTOS_MAIL_PROV_PROVCLI] FOREIGN KEY ([CODEMP], [PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
ALTER TABLE [dbo].[DEUDORES_CONTACTOS_MAIL_PROV] NOCHECK CONSTRAINT [FK_DEUDORES_CONTACTOS_MAIL_DEUDORES];


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Esta tabla almacena los distintos, mail para cada contacto migrando de la anterior DEUDORES_CONTACTOS_MAIL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEUDORES_CONTACTOS_MAIL_PROV';

