CREATE TABLE [dbo].[DEUDORES_DIRECCION_SITREL] (
    [CODEMP]    INT           NOT NULL,
    [CTCID]     NUMERIC (15)  NOT NULL,
    [DIRECCION] VARCHAR (255) NOT NULL,
    [COMID]     INT           NOT NULL,
    [TIPO]      VARCHAR (255) NOT NULL,
    [FECHA]     DATETIME      NOT NULL,
    [ORIGEN]    CHAR (1)      CONSTRAINT [DF__DEUDORES___ORIGE__3F322502] DEFAULT ('C') NULL,
    [ENVIADO]   CHAR (1)      CONSTRAINT [DF__DEUDORES___ENVIA__4026493B] DEFAULT ('N') NULL,
    CONSTRAINT [PK_DEUDORES_DIRECCION_SITREL] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [CTCID] ASC, [DIRECCION] ASC),
    CONSTRAINT [FK_DEUDORES_COMUNA_SITREL] FOREIGN KEY ([COMID]) REFERENCES [dbo].[COMUNA] ([COM_COMID]),
    CONSTRAINT [FK_DEUDORES_DIRECCION_SITREL] FOREIGN KEY ([CODEMP], [CTCID]) REFERENCES [dbo].[DEUDORES] ([CTC_CODEMP], [CTC_CTCID])
);


GO
ALTER TABLE [dbo].[DEUDORES_DIRECCION_SITREL] NOCHECK CONSTRAINT [FK_DEUDORES_COMUNA_SITREL];

