CREATE TABLE [dbo].[DEUDORES_DOCUMENTOS] (
    [DCD_CODEMP] INT           NOT NULL,
    [DCD_CTCID]  NUMERIC (15)  NOT NULL,
    [DCD_DCDID]  INT           NOT NULL,
    [DCD_TDDID]  INT           NOT NULL,
    [DCD_NOMBRE] VARCHAR (300) NULL,
    [DCD_PCLID]  NUMERIC (15)  NULL,
    CONSTRAINT [PK_DEUDORES_DOCUMENTOS] PRIMARY KEY CLUSTERED ([DCD_CODEMP] ASC, [DCD_CTCID] ASC, [DCD_DCDID] ASC),
    CONSTRAINT [FK_DEUDORES_DEUDORES__DEUDORES] FOREIGN KEY ([DCD_CODEMP], [DCD_CTCID]) REFERENCES [dbo].[DEUDORES] ([CTC_CODEMP], [CTC_CTCID]),
    CONSTRAINT [FK_DEUDORES_PROVCLI_D_PROVCLI] FOREIGN KEY ([DCD_CODEMP], [DCD_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_DEUDORES_TIPDD_DOC_TIPOS_DO] FOREIGN KEY ([DCD_CODEMP], [DCD_TDDID]) REFERENCES [dbo].[TIPOS_DOCUMENTOS_DEUDORES] ([TDD_CODEMP], [TDD_TDDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DEUDORES_DOCUMENTOS]([DCD_CODEMP] ASC, [DCD_CTCID] ASC, [DCD_DCDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos documentos para cada deudor, dependiendo si es para el deudor en si o solo para casos del cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEUDORES_DOCUMENTOS';

