CREATE TABLE [dbo].[DEUDORES_ESTAMPES] (
    [DDE_DDEID]  INT           IDENTITY (1, 1) NOT NULL,
    [DDE_CODEMP] INT           NOT NULL,
    [DDE_PCLID]  NUMERIC (15)  NOT NULL,
    [DDE_CTCID]  NUMERIC (15)  NOT NULL,
    [DDE_ROLID]  INT           NOT NULL,
    [DDE_PATH]   VARCHAR (300) NULL,
    [DDE_NOMBRE] VARCHAR (300) NULL,
    [DDE_EXT]    VARCHAR (5)   NULL,
    [DDE_INSID]  NUMERIC (15)  NULL,
    [DDE_ESTADO] VARCHAR (1)   NULL,
    [DDE_ITEM]   SMALLINT      NULL,
    [DDE_TPCID]  INT           NULL,
    [DDE_NUMERO] NUMERIC (15)  NULL,
    [DDE_FECJUD] DATETIME      NULL,
    [DDE_USRID]  INT           NULL,
    [DDE_FECING] DATETIME      NULL,
    CONSTRAINT [PK_DEUDORES_ESTAMPES] PRIMARY KEY CLUSTERED ([DDE_DDEID] ASC, [DDE_CODEMP] ASC, [DDE_PCLID] ASC, [DDE_CTCID] ASC, [DDE_ROLID] ASC)
);

