CREATE TABLE [dbo].[DOCUMENTOS_DIARIOS_IMAGENES] (
    [DDD_CODEMP] INT          NOT NULL,
    [DDD_SUCID]  INT          NOT NULL,
    [DDD_ANIO]   SMALLINT     NOT NULL,
    [DDD_NUMDOC] NUMERIC (15) NOT NULL,
    [DDD_IMGID]  INT          NOT NULL,
    [DDD_IMAGEN] IMAGE        NOT NULL,
    CONSTRAINT [PK_DOCUMENTOS_DIARIOS_IMAGENES] PRIMARY KEY NONCLUSTERED ([DDD_CODEMP] ASC, [DDD_SUCID] ASC, [DDD_ANIO] ASC, [DDD_NUMDOC] ASC, [DDD_IMGID] ASC),
    CONSTRAINT [FK_DOCUMENT_DOCDIA_IM_DOCUMENT] FOREIGN KEY ([DDD_CODEMP], [DDD_SUCID], [DDD_ANIO], [DDD_NUMDOC]) REFERENCES [dbo].[DOCUMENTOS_DIARIOS] ([DDI_CODEMP], [DDI_SUCID], [DDI_ANIO], [DDI_NUMDOC])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DOCUMENTOS_DIARIOS_IMAGENES]([DDD_CODEMP] ASC, [DDD_SUCID] ASC, [DDD_ANIO] ASC, [DDD_NUMDOC] ASC, [DDD_IMGID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena las distintas imagenes para cada documento diario', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DOCUMENTOS_DIARIOS_IMAGENES';

