CREATE TABLE [dbo].[DOCUMENTOS_DIARIOS_ESTADOS] (
    [DDE_CODEMP]     INT          NOT NULL,
    [DDE_SUCID]      INT          NOT NULL,
    [DDE_ANIO]       SMALLINT     NOT NULL,
    [DDE_NUMDOC]     NUMERIC (15) NOT NULL,
    [DDE_EDCID]      INT          NOT NULL,
    [DDE_FECPROC]    DATETIME     NOT NULL,
    [DDE_USRID]      INT          NULL,
    [DDE_COMENTARIO] TEXT         NULL,
    CONSTRAINT [PK_DOCUMENTOS_DIARIOS_ESTADOS] PRIMARY KEY NONCLUSTERED ([DDE_CODEMP] ASC, [DDE_SUCID] ASC, [DDE_ANIO] ASC, [DDE_NUMDOC] ASC, [DDE_EDCID] ASC, [DDE_FECPROC] ASC),
    CONSTRAINT [FK_DOCUMENT_DOCDIA_ES_DOCUMENT] FOREIGN KEY ([DDE_CODEMP], [DDE_SUCID], [DDE_ANIO], [DDE_NUMDOC]) REFERENCES [dbo].[DOCUMENTOS_DIARIOS] ([DDI_CODEMP], [DDI_SUCID], [DDI_ANIO], [DDI_NUMDOC]),
    CONSTRAINT [FK_DOCUMENT_USUARIO_D_USUARIOS] FOREIGN KEY ([DDE_CODEMP], [DDE_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[DOCUMENTOS_DIARIOS_ESTADOS]([DDE_CODEMP] ASC, [DDE_SUCID] ASC, [DDE_ANIO] ASC, [DDE_NUMDOC] ASC, [DDE_EDCID] ASC, [DDE_FECPROC] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos estados, para este documento tambien un comentario y quien hizo dicho cambio', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DOCUMENTOS_DIARIOS_ESTADOS';

