CREATE TABLE [dbo].[EJECUTIVO_CUENTA_MUTUAL] (
    [ID_CUENTA_EJECUTIVO] INT           IDENTITY (1, 1) NOT NULL,
    [CUENTA]              VARCHAR (200) NULL,
    [ID_EJECUTIVO]        INT           NOT NULL,
    [ID_TIPO_BANCO]       INT           NOT NULL,
    CONSTRAINT [PK_EJECUTIVO_CUENTA_MUTUAL] PRIMARY KEY CLUSTERED ([ID_CUENTA_EJECUTIVO] ASC),
    CONSTRAINT [FK_EJECUTIVO_CUENTA_MUTUAL_EJECUTIVO_MUTUAL] FOREIGN KEY ([ID_EJECUTIVO]) REFERENCES [dbo].[EJECUTIVO_MUTUAL] ([ID_EJECUTIVO]),
    CONSTRAINT [FK_EJECUTIVO_CUENTA_MUTUAL_TIPO_BANCO] FOREIGN KEY ([ID_TIPO_BANCO]) REFERENCES [dbo].[TIPO_BANCO] ([ID_TIPO_BANCO])
);

