CREATE TABLE [dbo].[EJECUTIVO_MUTUAL] (
    [ID_EJECUTIVO] INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       VARCHAR (200) NULL,
    [EMAIL]        VARCHAR (200) NULL,
    [OFICINA]      VARCHAR (200) NULL,
    CONSTRAINT [PK_EJECUTIVO_MUTUAL] PRIMARY KEY CLUSTERED ([ID_EJECUTIVO] ASC)
);

