CREATE TABLE [dbo].[EJERCICIOS_IDIOMAS] (
    [EJI_CODEMP] INT           NOT NULL,
    [EJI_EJCID]  INT           NOT NULL,
    [EJI_IDID]   INT           NOT NULL,
    [EJI_NOMBRE] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_EJERCICIOS_IDIOMAS] PRIMARY KEY CLUSTERED ([EJI_CODEMP] ASC, [EJI_EJCID] ASC, [EJI_IDID] ASC),
    CONSTRAINT [FK_EJERCICI_EJERCICIO_EJERCICI] FOREIGN KEY ([EJI_CODEMP], [EJI_EJCID]) REFERENCES [dbo].[EJERCICIOS] ([EJC_CODEMP], [EJC_EJCID]),
    CONSTRAINT [FK_EJERCICI_IDIOMAS_E_IDIOMAS] FOREIGN KEY ([EJI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EJERCICIOS_IDIOMAS]([EJI_CODEMP] ASC, [EJI_EJCID] ASC, [EJI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos ejercicios en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EJERCICIOS_IDIOMAS';

