CREATE TABLE [dbo].[EMBALAJE] (
    [EMB_CODEMP]    INT             NOT NULL,
    [EMB_SUCID]     INT             NOT NULL,
    [EMB_PCLID]     NUMERIC (15)    NOT NULL,
    [EMB_EMBID]     NUMERIC (15)    NOT NULL,
    [EMB_TPCID]     INT             NOT NULL,
    [EMB_NUMERO]    NUMERIC (15)    NOT NULL,
    [EMB_ITEM]      SMALLINT        NOT NULL,
    [EMB_CANTIDAD]  NUMERIC (15, 2) NOT NULL,
    [EMB_ORDENCOMP] VARCHAR (20)    NULL,
    [EMB_PCDID]     INT             NOT NULL,
    [EMB_ESTADO]    CHAR (1)        DEFAULT ('E') NULL,
    CONSTRAINT [PK_EMBALAJE] PRIMARY KEY CLUSTERED ([EMB_CODEMP] ASC, [EMB_SUCID] ASC, [EMB_PCLID] ASC, [EMB_EMBID] ASC, [EMB_TPCID] ASC, [EMB_NUMERO] ASC, [EMB_ITEM] ASC),
    CONSTRAINT [CKC_EMB_ESTADO_EMBALAJE] CHECK ([EMB_ESTADO] IS NULL OR ([EMB_ESTADO]='F' OR [EMB_ESTADO]='E')),
    CONSTRAINT [FK_EMBALAJE_DESP_EMBA_PROVCLI_] FOREIGN KEY ([EMB_CODEMP], [EMB_PCLID], [EMB_PCDID]) REFERENCES [dbo].[PROVCLI_DESPACHOS] ([PCD_CODEMP], [PCD_PCLID], [PCD_PCDID]),
    CONSTRAINT [FK_EMBALAJE_DETCPBT_E_DETALLE_] FOREIGN KEY ([EMB_CODEMP], [EMB_SUCID], [EMB_TPCID], [EMB_NUMERO], [EMB_ITEM]) REFERENCES [dbo].[DETALLE_COMPROBANTES] ([DCC_CODEMP], [DCC_SUCID], [DCC_TPCID], [DCC_NUMERO], [DCC_ITEM]),
    CONSTRAINT [FK_EMBALAJE_PROVCLI_E_PROVCLI_] FOREIGN KEY ([EMB_CODEMP], [EMB_PCLID]) REFERENCES [dbo].[PROVCLI_EMBALAJE] ([PCE_CODEMP], [PCE_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EMBALAJE]([EMB_CODEMP] ASC, [EMB_SUCID] ASC, [EMB_PCLID] ASC, [EMB_EMBID] ASC, [EMB_TPCID] ASC, [EMB_NUMERO] ASC, [EMB_ITEM] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena todos los datos requeridos para el embalaje', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMBALAJE';

