CREATE TABLE [dbo].[EMPLEADOS] (
    [EPL_CODEMP]    INT            NOT NULL,
    [EPL_EMPLID]    INT            NOT NULL,
    [EPL_RUT]       VARCHAR (20)   NOT NULL,
    [EPL_NOMBRE]    VARCHAR (100)  NOT NULL,
    [EPL_APEPAT]    VARCHAR (60)   NOT NULL,
    [EPL_APEMAT]    VARCHAR (60)   NOT NULL,
    [EPL_EEMID]     INT            NOT NULL,
    [EPL_COMID]     INT            NOT NULL,
    [EPL_DIRECCION] VARCHAR (200)  NOT NULL,
    [EPL_TELEFONO]  VARCHAR (80)   NULL,
    [EPL_CELULAR]   VARCHAR (80)   NULL,
    [EPL_MAIL]      VARCHAR (160)  NULL,
    [EPL_FOTO]      IMAGE          NULL,
    [EPL_FECING]    DATETIME       NOT NULL,
    [EPL_FECFIN]    DATETIME       NULL,
    [EPL_SUCID]     INT            NOT NULL,
    [EPL_USRID]     INT            NULL,
    [EPL_HUELLA]    VARCHAR (8000) NULL,
    [EPL_DIGITO]    NUMERIC (10)   NULL,
    [EPL_URL_FOTO]  VARCHAR (500)  NULL,
    CONSTRAINT [PK_EMPLEADOS] PRIMARY KEY NONCLUSTERED ([EPL_CODEMP] ASC, [EPL_EMPLID] ASC),
    CONSTRAINT [FK_EMPLEADO_EMPRESA_E_EMPRESA] FOREIGN KEY ([EPL_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP]),
    CONSTRAINT [FK_EMPLEADO_EMPSUC_EM_EMPRESA_] FOREIGN KEY ([EPL_CODEMP], [EPL_SUCID]) REFERENCES [dbo].[EMPRESA_SUCURSAL] ([ESU_CODEMP], [ESU_SUCID]),
    CONSTRAINT [FK_EMPLEADO_ESTEMPL_E_ESTADOS_] FOREIGN KEY ([EPL_CODEMP], [EPL_EEMID]) REFERENCES [dbo].[ESTADOS_EMPLEADO] ([EEM_CODEMP], [EEM_EEMID]),
    CONSTRAINT [FK_EMPLEADO_USUARIOS__USUARIOS] FOREIGN KEY ([EPL_CODEMP], [EPL_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EMPLEADOS]([EPL_CODEMP] ASC, [EPL_EMPLID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_RUT]
    ON [dbo].[EMPLEADOS]([EPL_CODEMP] ASC, [EPL_RUT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los empleados dependiendo de la sucursal', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMPLEADOS';

