CREATE TABLE [dbo].[EMPRESA_SUCURSAL] (
    [ESU_CODEMP]    INT           NOT NULL,
    [ESU_SUCID]     INT           NOT NULL,
    [ESU_NOMBRE]    VARCHAR (100) NOT NULL,
    [ESU_COMID]     INT           NOT NULL,
    [ESU_DIRECCION] VARCHAR (400) NOT NULL,
    [ESU_TELEFONO]  VARCHAR (80)  NOT NULL,
    [ESU_FAX]       VARCHAR (80)  NULL,
    [ESU_MAIL]      VARCHAR (80)  NULL,
    [ESU_CSS]       VARCHAR (80)  NULL,
    [ESU_MATRIZ]    CHAR (1)      DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_EMPRESA_SUCURSAL] PRIMARY KEY CLUSTERED ([ESU_CODEMP] ASC, [ESU_SUCID] ASC),
    CONSTRAINT [CKC_ESU_MATRIZ_EMPRESA_] CHECK ([ESU_MATRIZ]='N' OR [ESU_MATRIZ]='S'),
    CONSTRAINT [FK_EMPRESA__COMUNA_EM_COMUNA] FOREIGN KEY ([ESU_COMID]) REFERENCES [dbo].[COMUNA] ([COM_COMID]),
    CONSTRAINT [FK_EMPRESA__EMPRESA_S_EMPRESA] FOREIGN KEY ([ESU_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EMPRESA_SUCURSAL]([ESU_CODEMP] ASC, [ESU_SUCID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena lo relacionado a las sucursales de cada empresa', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMPRESA_SUCURSAL';

