CREATE TABLE [dbo].[EMPRESA_CONFIGURACION] (
    [EMC_CODEMP] INT             NOT NULL,
    [EMC_EMCID]  INT             NOT NULL,
    [EMC_NOMBRE] VARCHAR (400)   NOT NULL,
    [EMC_VALNUM] NUMERIC (30, 6) DEFAULT ((0)) NOT NULL,
    [EMC_VALTXT] VARCHAR (1000)  DEFAULT ('0') NOT NULL,
    CONSTRAINT [PK_EMPRESA_CONFIGURACION] PRIMARY KEY CLUSTERED ([EMC_CODEMP] ASC, [EMC_EMCID] ASC),
    CONSTRAINT [FK_EMPRESA__EMPRESA_C_EMPRESA] FOREIGN KEY ([EMC_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EMPRESA_CONFIGURACION]([EMC_CODEMP] ASC, [EMC_EMCID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[EMPRESA_CONFIGURACION]([EMC_NOMBRE] ASC, [EMC_CODEMP] ASC);

