CREATE TABLE [dbo].[EMPRESA_BANCOS] (
    [ESB_CODEMP]    INT           NOT NULL,
    [ESB_BCOID]     INT           NOT NULL,
    [ESB_SUCID]     INT           NOT NULL,
    [ESB_CTACTE]    VARCHAR (40)  NOT NULL,
    [ESB_COMID]     INT           NULL,
    [ESB_DIRECCION] VARCHAR (200) NOT NULL,
    [ESB_AGENTE]    VARCHAR (200) NOT NULL,
    [ESB_TELEFONO]  VARCHAR (80)  NOT NULL,
    [ESB_EMAIL]     VARCHAR (100) NOT NULL,
    [ESB_PCTID]     INT           NOT NULL,
    CONSTRAINT [PK_EMPRESA_BANCOS] PRIMARY KEY NONCLUSTERED ([ESB_CODEMP] ASC, [ESB_BCOID] ASC, [ESB_SUCID] ASC, [ESB_CTACTE] ASC),
    CONSTRAINT [FK_EMPRESA__BANCOS_EM_BANCOS] FOREIGN KEY ([ESB_CODEMP], [ESB_BCOID]) REFERENCES [dbo].[BANCOS] ([BCO_CODEMP], [BCO_BCOID]),
    CONSTRAINT [FK_EMPRESA__COM_EMPBA_COMUNA] FOREIGN KEY ([ESB_COMID]) REFERENCES [dbo].[COMUNA] ([COM_COMID]),
    CONSTRAINT [FK_EMPRESA__EMPSUC_BA_EMPRESA_] FOREIGN KEY ([ESB_CODEMP], [ESB_SUCID]) REFERENCES [dbo].[EMPRESA_SUCURSAL] ([ESU_CODEMP], [ESU_SUCID]),
    CONSTRAINT [FK_EMPRESA__PLACTA_BA_PLAN_CUE] FOREIGN KEY ([ESB_CODEMP], [ESB_PCTID]) REFERENCES [dbo].[PLAN_CUENTAS] ([PCT_CODEMP], [PCT_PCTID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EMPRESA_BANCOS]([ESB_CODEMP] ASC, [ESB_SUCID] ASC, [ESB_BCOID] ASC, [ESB_CTACTE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos bancos que utiliza la empresa y su respectiva cuentas', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMPRESA_BANCOS';

