CREATE TABLE [dbo].[ENTES_JUDICIAL] (
    [ETJ_CODEMP]            INT          NOT NULL,
    [ETJ_ETJID]             INT          NOT NULL,
    [ETJ_PCLID]             NUMERIC (15) NULL,
    [ETJ_EMPLID]            INT          NULL,
    [ETJ_SINDICO]           CHAR (1)     DEFAULT ('N') NOT NULL,
    [ETJ_ABOGADO]           CHAR (1)     DEFAULT ('N') NOT NULL,
    [ETJ_PROCURADOR]        CHAR (1)     DEFAULT ('N') NOT NULL,
    [ETJ_RECEPTOR]          CHAR (1)     DEFAULT ('N') NOT NULL,
    [ETJ_ABOGADO_ENCARGADO] CHAR (1)     NULL,
    CONSTRAINT [PK_ENTES_JUDICIAL] PRIMARY KEY CLUSTERED ([ETJ_CODEMP] ASC, [ETJ_ETJID] ASC),
    CONSTRAINT [CKC_ETJ_ABOGADO_ENTES_JU] CHECK ([ETJ_ABOGADO]='N' OR [ETJ_ABOGADO]='S'),
    CONSTRAINT [CKC_ETJ_PROCURADOR_ENTES_JU] CHECK ([ETJ_PROCURADOR]='N' OR [ETJ_PROCURADOR]='S'),
    CONSTRAINT [CKC_ETJ_RECEPTOR_ENTES_JU] CHECK ([ETJ_RECEPTOR]='N' OR [ETJ_RECEPTOR]='S'),
    CONSTRAINT [CKC_ETJ_SINDICO_ENTES_JU] CHECK ([ETJ_SINDICO]='N' OR [ETJ_SINDICO]='S'),
    CONSTRAINT [FK_ENTES_JU_EMPLEADOS_EMPLEADO] FOREIGN KEY ([ETJ_CODEMP], [ETJ_EMPLID]) REFERENCES [dbo].[EMPLEADOS] ([EPL_CODEMP], [EPL_EMPLID]),
    CONSTRAINT [FK_ENTES_JU_EMPRESA_J_EMPRESA] FOREIGN KEY ([ETJ_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP]),
    CONSTRAINT [FK_ENTES_JU_PROVCLI_E_PROVCLI] FOREIGN KEY ([ETJ_CODEMP], [ETJ_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ENTES_JUDICIAL]([ETJ_CODEMP] ASC, [ETJ_ETJID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena todos los entes judiciales, ejemplo
   
   Sindico, Abogado, Procurador, Receptor, etc,....', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ENTES_JUDICIAL';

