CREATE TABLE [dbo].[ESTADOS_EMPLEADO_IDIOMAS] (
    [EEI_CODEMP] INT          NOT NULL,
    [EEI_EEMID]  INT          NOT NULL,
    [EEI_IDID]   INT          NOT NULL,
    [EEI_NOMBRE] VARCHAR (60) NOT NULL,
    CONSTRAINT [PK_ESTADOS_EMPLEADO_IDIOMAS] PRIMARY KEY NONCLUSTERED ([EEI_CODEMP] ASC, [EEI_EEMID] ASC, [EEI_IDID] ASC),
    CONSTRAINT [FK_ESTADOS__ESTEMPLEA_ESTADOS_] FOREIGN KEY ([EEI_CODEMP], [EEI_EEMID]) REFERENCES [dbo].[ESTADOS_EMPLEADO] ([EEM_CODEMP], [EEM_EEMID]),
    CONSTRAINT [FK_ESTADOS__IDI_ESTEM_IDIOMAS] FOREIGN KEY ([EEI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ESTADOS_EMPLEADO_IDIOMAS]([EEI_CODEMP] ASC, [EEI_EEMID] ASC, [EEI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos idiomas para los estados', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ESTADOS_EMPLEADO_IDIOMAS';

