CREATE TABLE [dbo].[ESTADOS_GARANTIAS] (
    [ESG_CODEMP] INT          NOT NULL,
    [ESG_ESGID]  INT          NOT NULL,
    [ESG_NOMBRE] VARCHAR (50) NOT NULL,
    [ESG_TIPO]   SMALLINT     DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_ESTADOS_GARANTIAS] PRIMARY KEY CLUSTERED ([ESG_CODEMP] ASC, [ESG_ESGID] ASC),
    CONSTRAINT [CKC_ESG_TIPO_ESTADOS_] CHECK ([ESG_TIPO]=(3) OR [ESG_TIPO]=(2) OR [ESG_TIPO]=(1)),
    CONSTRAINT [FK_ESTADOS__EMP_ESTGA_EMPRESA] FOREIGN KEY ([ESG_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ESTADOS_GARANTIAS]([ESG_CODEMP] ASC, [ESG_ESGID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[ESTADOS_GARANTIAS]([ESG_CODEMP] ASC, [ESG_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos estados para cada garantia', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ESTADOS_GARANTIAS';

