CREATE TABLE [dbo].[ESTADOS_GARANTIAS_IDIOMAS] (
    [EGI_CODEMP] INT          NOT NULL,
    [EGI_ESGID]  INT          NOT NULL,
    [EGI_IDID]   INT          NOT NULL,
    [EGI_NOMBRE] VARCHAR (60) NOT NULL,
    CONSTRAINT [PK_ESTADOS_GARANTIAS_IDIOMAS] PRIMARY KEY CLUSTERED ([EGI_CODEMP] ASC, [EGI_ESGID] ASC, [EGI_IDID] ASC),
    CONSTRAINT [FK_ESTADOS__ESTGAR_ID_ESTADOS_] FOREIGN KEY ([EGI_CODEMP], [EGI_ESGID]) REFERENCES [dbo].[ESTADOS_GARANTIAS] ([ESG_CODEMP], [ESG_ESGID]),
    CONSTRAINT [FK_ESTADOS__IDIO_ESTG_IDIOMAS] FOREIGN KEY ([EGI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ESTADOS_GARANTIAS_IDIOMAS]([EGI_CODEMP] ASC, [EGI_ESGID] ASC, [EGI_IDID] ASC);

