CREATE TABLE [dbo].[ESTADOS_DOCUMENTOS_DIARIOS_IDIOMAS] (
    [EDI_CODEMP] INT          NOT NULL,
    [EDI_EDCID]  INT          NOT NULL,
    [EDI_IDIID]  INT          NOT NULL,
    [EDI_NOMBRE] VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_ESTADO_DOCUMENTOS_IDIOMAS] PRIMARY KEY NONCLUSTERED ([EDI_CODEMP] ASC, [EDI_EDCID] ASC, [EDI_IDIID] ASC),
    CONSTRAINT [FK_ESTADOS__ESTDOCDIA_ESTADOS_] FOREIGN KEY ([EDI_CODEMP], [EDI_EDCID]) REFERENCES [dbo].[ESTADOS_DOCUMENTOS_DIARIOS] ([EDC_CODEMP], [EDC_EDCID]),
    CONSTRAINT [FK_ESTADOS__IDI_ESTDO_IDIOMAS] FOREIGN KEY ([EDI_IDIID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ESTADOS_DOCUMENTOS_DIARIOS_IDIOMAS]([EDI_CODEMP] ASC, [EDI_EDCID] ASC, [EDI_IDIID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos, estados de los documentos en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ESTADOS_DOCUMENTOS_DIARIOS_IDIOMAS';

