CREATE TABLE [dbo].[ESTADOS_DESPACHOS_IDIOMAS] (
    [EDI_CODEMP] INT           NOT NULL,
    [EDI_EDPID]  INT           NOT NULL,
    [EDI_IDID]   INT           NOT NULL,
    [EDI_NOMBRE] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_ESTADOS_DESPACHOS_IDIOMAS] PRIMARY KEY CLUSTERED ([EDI_CODEMP] ASC, [EDI_EDPID] ASC, [EDI_IDID] ASC),
    CONSTRAINT [FK_ESTADOS__ESTDESP_I_ESTADOS_] FOREIGN KEY ([EDI_CODEMP], [EDI_EDPID]) REFERENCES [dbo].[ESTADOS_DESPACHOS] ([EDP_CODEMP], [EDP_EDPID]),
    CONSTRAINT [FK_ESTADOS__IDIOMAS_E_IDIOMAS] FOREIGN KEY ([EDI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ESTADOS_DESPACHOS_IDIOMAS]([EDI_CODEMP] ASC, [EDI_EDPID] ASC, [EDI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de despacho en su rerspectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ESTADOS_DESPACHOS_IDIOMAS';

