CREATE TABLE [dbo].[EVENTOS_IDIOMAS] (
    [EVI_CODEMP] INT           NOT NULL,
    [EVI_EVEID]  INT           NOT NULL,
    [EVI_IDID]   INT           NOT NULL,
    [EVI_TITULO] VARCHAR (200) NOT NULL,
    [EVI_TEXTO]  TEXT          NULL,
    CONSTRAINT [PK_EVENTOS_IDIOMAS] PRIMARY KEY CLUSTERED ([EVI_CODEMP] ASC, [EVI_EVEID] ASC, [EVI_IDID] ASC),
    CONSTRAINT [FK_EVENTOS__EVENTOS_I_EVENTOS] FOREIGN KEY ([EVI_CODEMP], [EVI_EVEID]) REFERENCES [dbo].[EVENTOS] ([EVE_CODEMP], [EVE_EVEID]),
    CONSTRAINT [FK_EVENTOS__IDIOMAS_E_IDIOMAS] FOREIGN KEY ([EVI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[EVENTOS_IDIOMAS]([EVI_CODEMP] ASC, [EVI_EVEID] ASC, [EVI_IDID] ASC);

