CREATE TABLE [dbo].[GARANTIA_VEHICULO] (
    [GTV_CODEMP]     INT           NOT NULL,
    [GTV_GRTID]      INT           NOT NULL,
    [GTV_PLACA]      VARCHAR (20)  NOT NULL,
    [GTV_TVCID]      INT           NOT NULL,
    [GTV_MKVID]      INT           NOT NULL,
    [GTV_MOTOR]      VARCHAR (50)  NOT NULL,
    [GTV_COLOR]      VARCHAR (200) NOT NULL,
    [GTV_MODELO]     VARCHAR (200) NOT NULL,
    [GTV_CHASIS]     VARCHAR (200) NOT NULL,
    [GTV_SERIE]      VARCHAR (200) NOT NULL,
    [GTV_ANIO]       SMALLINT      NOT NULL,
    [GTV_PARTICULAR] CHAR (1)      DEFAULT ('S') NOT NULL,
    CONSTRAINT [PK_GARANTIA_VEHICULO] PRIMARY KEY CLUSTERED ([GTV_CODEMP] ASC, [GTV_GRTID] ASC, [GTV_PLACA] ASC),
    CONSTRAINT [CKC_GTV_PARTICULAR_GARANTIA] CHECK ([GTV_PARTICULAR]='N' OR [GTV_PARTICULAR]='S'),
    CONSTRAINT [FK_GARANTIA_GAR_VEHIC_GARANTIA] FOREIGN KEY ([GTV_CODEMP], [GTV_GRTID]) REFERENCES [dbo].[GARANTIA] ([GRT_CODEMP], [GRT_GRTID]),
    CONSTRAINT [FK_GARANTIA_MARCAVEH__MARCAS_V] FOREIGN KEY ([GTV_CODEMP], [GTV_MKVID]) REFERENCES [dbo].[MARCAS_VEHICULOS] ([MKV_CODEMP], [MKV_MKVID]),
    CONSTRAINT [FK_GARANTIA_TVC_GARAN_TIPOS_VE] FOREIGN KEY ([GTV_CODEMP], [GTV_TVCID]) REFERENCES [dbo].[TIPOS_VEHICULOS] ([TVC_CODEMP], [TVC_TVCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[GARANTIA_VEHICULO]([GTV_CODEMP] ASC, [GTV_GRTID] ASC, [GTV_PLACA] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos datos de la garantia del vehiculo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GARANTIA_VEHICULO';

