CREATE TABLE [dbo].[GIROS_IDIOMAS] (
    [GII_CODEMP] INT            NOT NULL,
    [GII_GIRID]  INT            NOT NULL,
    [GII_IDID]   INT            NOT NULL,
    [GII_NOMBRE] VARCHAR (1500) NOT NULL,
    CONSTRAINT [PK_GIROS_IDIOMAS] PRIMARY KEY NONCLUSTERED ([GII_CODEMP] ASC, [GII_GIRID] ASC, [GII_IDID] ASC),
    CONSTRAINT [FK_GIROS_ID_GIROS_IDI_GIROS] FOREIGN KEY ([GII_CODEMP], [GII_GIRID]) REFERENCES [dbo].[GIROS] ([GIR_CODEMP], [GIR_GIRID]),
    CONSTRAINT [FK_GIROS_ID_IDIOMAS_G_IDIOMAS] FOREIGN KEY ([GII_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[GIROS_IDIOMAS]([GII_IDID] ASC, [GII_CODEMP] ASC, [GII_GIRID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[GIROS_IDIOMAS]([GII_CODEMP] ASC, [GII_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos giros en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GIROS_IDIOMAS';

