CREATE TABLE [dbo].[GRUPOS_COBRANZA] (
    [GRC_CODEMP] INT           NOT NULL,
    [GRC_SUCID]  INT           NOT NULL,
    [GRC_GRCID]  INT           NOT NULL,
    [GRC_NOMBRE] VARCHAR (200) NOT NULL,
    [GRC_EMPLID] INT           NOT NULL,
    CONSTRAINT [PK_GRUPOS_COBRANZA] PRIMARY KEY CLUSTERED ([GRC_CODEMP] ASC, [GRC_SUCID] ASC, [GRC_GRCID] ASC),
    CONSTRAINT [FK_GRUPOS_C_EMPLEADOS_EMPLEADO] FOREIGN KEY ([GRC_CODEMP], [GRC_EMPLID]) REFERENCES [dbo].[EMPLEADOS] ([EPL_CODEMP], [EPL_EMPLID]),
    CONSTRAINT [FK_GRUPOS_C_EMPSUC_GR_EMPRESA_] FOREIGN KEY ([GRC_CODEMP], [GRC_SUCID]) REFERENCES [dbo].[EMPRESA_SUCURSAL] ([ESU_CODEMP], [ESU_SUCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[GRUPOS_COBRANZA]([GRC_CODEMP] ASC, [GRC_SUCID] ASC, [GRC_GRCID] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[GRUPOS_COBRANZA]([GRC_CODEMP] ASC, [GRC_SUCID] ASC, [GRC_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos grupos de cobranza tambien el encargado de dicho grupo
   
   
   Ejemplo:
   
   PAZ, COCHA, DIMERC, ETC...', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GRUPOS_COBRANZA';

