CREATE TABLE [dbo].[GRUPO_COBRANZA_GESTOR] (
    [GCG_CODEMP] INT NOT NULL,
    [GCG_SUCID]  INT NOT NULL,
    [GCG_GRCID]  INT NOT NULL,
    [GCG_GESID]  INT NOT NULL,
    CONSTRAINT [PK_GRUPO_COBRANZA_GESTOR] PRIMARY KEY CLUSTERED ([GCG_CODEMP] ASC, [GCG_SUCID] ASC, [GCG_GRCID] ASC, [GCG_GESID] ASC),
    CONSTRAINT [FK_GRUPO_CO_GESTOR_GR_GESTOR] FOREIGN KEY ([GCG_CODEMP], [GCG_SUCID], [GCG_GESID]) REFERENCES [dbo].[GESTOR] ([GES_CODEMP], [GES_SUCID], [GES_GESID]),
    CONSTRAINT [FK_GRUPO_CO_GRUCOB_GR_GRUPOS_C] FOREIGN KEY ([GCG_CODEMP], [GCG_SUCID], [GCG_GRCID]) REFERENCES [dbo].[GRUPOS_COBRANZA] ([GRC_CODEMP], [GRC_SUCID], [GRC_GRCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[GRUPO_COBRANZA_GESTOR]([GCG_CODEMP] ASC, [GCG_SUCID] ASC, [GCG_GRCID] ASC, [GCG_GESID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos gestores que estan asignados a los grupos de cobranza', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GRUPO_COBRANZA_GESTOR';

