CREATE TABLE [dbo].[HELP_IDIOMAS] (
    [HPI_TRVID]   INT           NOT NULL,
    [HPI_HLPID]   INT           NOT NULL,
    [HPI_IDID]    INT           NOT NULL,
    [HPI_NOMBRE]  VARCHAR (100) NOT NULL,
    [HPI_ARCHIVO] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_HELP_IDIOMAS] PRIMARY KEY CLUSTERED ([HPI_TRVID] ASC, [HPI_HLPID] ASC, [HPI_IDID] ASC),
    CONSTRAINT [FK_HELP_IDI_HELP_IDIO_HELP] FOREIGN KEY ([HPI_TRVID], [HPI_HLPID]) REFERENCES [dbo].[HELP] ([HLP_TRVID], [HLP_HLPID]),
    CONSTRAINT [FK_HELP_IDI_IDIOMAS_H_IDIOMAS] FOREIGN KEY ([HPI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[HELP_IDIOMAS]([HPI_TRVID] ASC, [HPI_HLPID] ASC, [HPI_IDID] ASC);

