CREATE TABLE [dbo].[IMPORTACION] (
    [IMP_CODEMP]    INT           NOT NULL,
    [IMP_IMPID]     INT           NOT NULL,
    [IMP_TPTID]     INT           NOT NULL,
    [IMP_NUMERO]    VARCHAR (15)  NOT NULL,
    [IMP_NOMBRE]    VARCHAR (200) NOT NULL,
    [IMP_PCLID]     NUMERIC (15)  NULL,
    [IMP_FECING]    DATETIME      NOT NULL,
    [IMP_FECARRIBO] DATETIME      NOT NULL,
    [IMP_ESTADO]    CHAR (1)      DEFAULT ('E') NULL,
    CONSTRAINT [PK_IMPORTACION] PRIMARY KEY CLUSTERED ([IMP_CODEMP] ASC, [IMP_IMPID] ASC),
    CONSTRAINT [CKC_IMP_ESTADO_IMPORTAC] CHECK ([IMP_ESTADO] IS NULL OR ([IMP_ESTADO]='F' OR [IMP_ESTADO]='A' OR [IMP_ESTADO]='E')),
    CONSTRAINT [FK_IMPORTAC_PROVCLI_I_PROVCLI] FOREIGN KEY ([IMP_CODEMP], [IMP_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_IMPORTAC_TIPTRAN_I_TIPOS_TR] FOREIGN KEY ([IMP_CODEMP], [IMP_TPTID]) REFERENCES [dbo].[TIPOS_TRANSPORTE] ([TPT_CODEMP], [TPT_TPTID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[IMPORTACION]([IMP_CODEMP] ASC, [IMP_IMPID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de importacion, ya sea por avion, barco etc...', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'IMPORTACION';

