CREATE TABLE [dbo].[IMPORTACION_CPBTDOC] (
    [IPC_CODEMP] INT          NOT NULL,
    [IPC_IMPID]  INT          NOT NULL,
    [IPC_SUCID]  INT          NOT NULL,
    [IPC_TPCID]  INT          NOT NULL,
    [IPC_NUMERO] NUMERIC (15) NOT NULL,
    [IPC_TCOID]  INT          NOT NULL,
    CONSTRAINT [PK_IMPORTACION_CPBTDOC] PRIMARY KEY CLUSTERED ([IPC_CODEMP] ASC, [IPC_IMPID] ASC, [IPC_SUCID] ASC, [IPC_TPCID] ASC, [IPC_NUMERO] ASC),
    CONSTRAINT [FK_IMPORTAC_CPBT_IMPO_CABACERA] FOREIGN KEY ([IPC_CODEMP], [IPC_SUCID], [IPC_TPCID], [IPC_NUMERO]) REFERENCES [dbo].[CABACERA_COMPROBANTES] ([CBC_CODEMP], [CBC_SUCID], [CBC_TPCID], [CBC_NUMERO]),
    CONSTRAINT [FK_IMPORTAC_IMPORT_CP_IMPORTAC] FOREIGN KEY ([IPC_CODEMP], [IPC_IMPID]) REFERENCES [dbo].[IMPORTACION] ([IMP_CODEMP], [IMP_IMPID]),
    CONSTRAINT [FK_IMPORTAC_TIPCOST_I_TIPOS_CO] FOREIGN KEY ([IPC_CODEMP], [IPC_TCOID]) REFERENCES [dbo].[TIPOS_COSTO] ([TCO_CODEMP], [TCO_TCOID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[IMPORTACION_CPBTDOC]([IPC_CODEMP] ASC, [IPC_IMPID] ASC, [IPC_SUCID] ASC, [IPC_TPCID] ASC, [IPC_NUMERO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena todos los comprobantes (facturas) asociadas a la importacion
   
   se debe indicar el tipo de gasto de la factura, la cual servira para el calculo de costos', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'IMPORTACION_CPBTDOC';

