CREATE TABLE [dbo].[INSUMO_ESPECIFICACIONES_IDIOMAS] (
    [IEI_CODEMP]      INT          NOT NULL,
    [IEI_INSID]       NUMERIC (15) NOT NULL,
    [IEI_ISEID]       INT          NOT NULL,
    [IEI_IDID]        INT          NOT NULL,
    [IEI_DESCRIPCION] TEXT         NOT NULL,
    CONSTRAINT [PK_INSUMO_ESPECIFICACIONES_IDI] PRIMARY KEY NONCLUSTERED ([IEI_CODEMP] ASC, [IEI_INSID] ASC, [IEI_ISEID] ASC, [IEI_IDID] ASC),
    CONSTRAINT [FK_INSUMO_E_IDIOMAS_I_IDIOMAS] FOREIGN KEY ([IEI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_INSUMO_E_INSU_ESPI_INSUMO_E] FOREIGN KEY ([IEI_CODEMP], [IEI_INSID], [IEI_ISEID]) REFERENCES [dbo].[INSUMO_ESPECIFICACIONES] ([ISE_CODEMP], [ISE_INSID], [ISE_ISEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[INSUMO_ESPECIFICACIONES_IDIOMAS]([IEI_CODEMP] ASC, [IEI_INSID] ASC, [IEI_ISEID] ASC, [IEI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas especificaciones en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INSUMO_ESPECIFICACIONES_IDIOMAS';

