CREATE TABLE [dbo].[INSUMO_ESPECIFICACIONES] (
    [ISE_CODEMP] INT          NOT NULL,
    [ISE_INSID]  NUMERIC (15) NOT NULL,
    [ISE_ISEID]  INT          NOT NULL,
    [ISE_TPDID]  INT          NOT NULL,
    CONSTRAINT [PK_INSUMO_ESPECIFICACIONES] PRIMARY KEY NONCLUSTERED ([ISE_CODEMP] ASC, [ISE_INSID] ASC, [ISE_ISEID] ASC),
    CONSTRAINT [FK_INSUMO_E_INSU_ESPE_INSUMOS] FOREIGN KEY ([ISE_CODEMP], [ISE_INSID]) REFERENCES [dbo].[INSUMOS] ([INS_CODEMP], [INS_INSID]),
    CONSTRAINT [FK_INSUMO_E_TIPDESCPR_TIPO_DES] FOREIGN KEY ([ISE_CODEMP], [ISE_TPDID]) REFERENCES [dbo].[TIPOS_DESCRIPCION_PRODUCTO] ([TDP_CODEMP], [TDP_TPDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[INSUMO_ESPECIFICACIONES]([ISE_CODEMP] ASC, [ISE_INSID] ASC, [ISE_ISEID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los ditintos tipos de especificaciones, para los insumos
   
   Ejmplo, Posibles precauciones', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INSUMO_ESPECIFICACIONES';

