CREATE TABLE [dbo].[LISTAS_PRECIOS_PRODUCTOS] (
    [LPP_CODEMP]  INT             NOT NULL,
    [LPP_LTPID]   INT             NOT NULL,
    [LPP_PRODID]  NUMERIC (15)    NOT NULL,
    [LPP_PREREAL] DECIMAL (10, 2) NOT NULL,
    [LPP_PRECIO]  DECIMAL (10, 2) NOT NULL,
    [LPP_ORDEN01] SMALLINT        DEFAULT ((0)) NOT NULL,
    [LPP_ORDEN02] SMALLINT        DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_LISTAS_PRECIOS_PRODUCTOS] PRIMARY KEY CLUSTERED ([LPP_CODEMP] ASC, [LPP_LTPID] ASC, [LPP_PRODID] ASC),
    CONSTRAINT [FK_LISTAS_P_LISTPRE_P_LISTAS_P] FOREIGN KEY ([LPP_CODEMP], [LPP_LTPID]) REFERENCES [dbo].[LISTAS_PRECIOS] ([LTP_CODEMP], [LTP_LTPID]),
    CONSTRAINT [FK_LISTAS_P_PRODUCTOS_PRODUCTO] FOREIGN KEY ([LPP_CODEMP], [LPP_PRODID]) REFERENCES [dbo].[PRODUCTOS] ([PDT_CODEMP], [PDT_PRODID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[LISTAS_PRECIOS_PRODUCTOS]([LPP_CODEMP] ASC, [LPP_LTPID] ASC, [LPP_PRODID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos productos asociados a la lista de precios', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LISTAS_PRECIOS_PRODUCTOS';

