CREATE TABLE [dbo].[MAESTRA_PRODUCTOS_PROVCLI] (
    [PDT_CODEMP]    INT           NOT NULL,
    [PDT_PRODID]    NUMERIC (15)  NOT NULL,
    [PCL_PCLID]     NUMERIC (15)  NOT NULL,
    [MPC_CODIGO]    VARCHAR (30)  NOT NULL,
    [MPC_NOMBRE]    VARCHAR (200) NOT NULL,
    [MPC_CODBARRA]  VARCHAR (30)  NOT NULL,
    [MPC_PACK]      SMALLINT      NOT NULL,
    [MPC_CODBARIMG] IMAGE         NULL,
    CONSTRAINT [PK_MAESTRA_PRODUCTOS_PROVCLI] PRIMARY KEY NONCLUSTERED ([PDT_CODEMP] ASC, [PDT_PRODID] ASC, [PCL_PCLID] ASC),
    CONSTRAINT [FK_MAESTRA__PRODUCTOS_PRODUCTO] FOREIGN KEY ([PDT_CODEMP], [PDT_PRODID]) REFERENCES [dbo].[PRODUCTOS] ([PDT_CODEMP], [PDT_PRODID]),
    CONSTRAINT [FK_MAESTRA__PROVCLI_M_PROVCLI] FOREIGN KEY ([PDT_CODEMP], [PCL_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[MAESTRA_PRODUCTOS_PROVCLI]([PDT_CODEMP] ASC, [PDT_PRODID] ASC, [PCL_PCLID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_CODIGO]
    ON [dbo].[MAESTRA_PRODUCTOS_PROVCLI]([PDT_CODEMP] ASC, [PCL_PCLID] ASC, [MPC_CODIGO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena, los distintos productos para cada cliente o proveedor', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MAESTRA_PRODUCTOS_PROVCLI';

