CREATE TABLE [dbo].[MAESTRA_INSUMOS_PROVCLI] (
    [MIP_CODEMP]   INT             NOT NULL,
    [MIP_INSID]    NUMERIC (15)    NOT NULL,
    [MIP_PCLID]    NUMERIC (15)    NOT NULL,
    [MIP_CODIGO]   VARCHAR (30)    NOT NULL,
    [MIP_NOMBRE]   VARCHAR (200)   NOT NULL,
    [MIP_CODBARRA] VARCHAR (30)    NULL,
    [MIP_CUBICAJE] DECIMAL (15, 2) NOT NULL,
    [MIP_PACK]     SMALLINT        NOT NULL,
    [MIP_UNMLGT]   INT             NOT NULL,
    [MIP_ALTO]     DECIMAL (15, 2) NOT NULL,
    [MIP_ANCHO]    DECIMAL (15, 2) NOT NULL,
    [MIP_LARGO]    DECIMAL (15, 2) NOT NULL,
    [MIP_UNMID]    INT             NOT NULL,
    [MIP_PESO]     DECIMAL (15, 2) NOT NULL,
    [MIP_CODMON]   INT             NOT NULL,
    [MIP_PRECIO]   DECIMAL (14, 2) NOT NULL,
    CONSTRAINT [PK_MAESTRA_INSUMOS_PROVCLI] PRIMARY KEY NONCLUSTERED ([MIP_CODEMP] ASC, [MIP_INSID] ASC, [MIP_PCLID] ASC),
    CONSTRAINT [FK_MAESTRA__INSUMOS_M_INSUMOS] FOREIGN KEY ([MIP_CODEMP], [MIP_INSID]) REFERENCES [dbo].[INSUMOS] ([INS_CODEMP], [INS_INSID]),
    CONSTRAINT [FK_MAESTRA__MONEDAS_I_MONEDAS] FOREIGN KEY ([MIP_CODEMP], [MIP_CODMON]) REFERENCES [dbo].[MONEDAS] ([MON_CODEMP], [MON_CODMON]),
    CONSTRAINT [FK_MAESTRA__PROVCLI_I_PROVCLI] FOREIGN KEY ([MIP_CODEMP], [MIP_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_MAESTRA__UM_INSMAE_UNIDADES] FOREIGN KEY ([MIP_UNMID]) REFERENCES [dbo].[UNIDADES_MEDIDA] ([UNM_UNMID]),
    CONSTRAINT [FK_MAESTRA__UNIMED_IN_UNIDADES] FOREIGN KEY ([MIP_UNMLGT]) REFERENCES [dbo].[UNIDADES_MEDIDA] ([UNM_UNMID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[MAESTRA_INSUMOS_PROVCLI]([MIP_CODEMP] ASC, [MIP_INSID] ASC, [MIP_PCLID] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CODIGO]
    ON [dbo].[MAESTRA_INSUMOS_PROVCLI]([MIP_CODEMP] ASC, [MIP_PCLID] ASC, [MIP_CODIGO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacenara los distintos Insumos que manejara el tipo de cliente, proveedor o demas....
   
   
   
   ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MAESTRA_INSUMOS_PROVCLI';

