CREATE TABLE [dbo].[MAXIMA_CONVENCIONAL] (
    [MXC_CODEMP] INT             NOT NULL,
    [MXC_MXCID]  INT             NOT NULL,
    [MXC_TPCID]  INT             NOT NULL,
    [MXC_TIPO]   CHAR (1)        NOT NULL,
    [MXC_APLICA] CHAR (1)        DEFAULT ('H') NOT NULL,
    [MXC_CODMON] INT             NOT NULL,
    [MXC_DESDE]  DECIMAL (10, 2) NOT NULL,
    [MXC_HASTA]  DECIMAL (10, 2) NOT NULL,
    [MXC_VALOR]  DECIMAL (10, 2) NOT NULL,
    CONSTRAINT [PK_MAXIMA_CONVENCIONAL] PRIMARY KEY NONCLUSTERED ([MXC_CODEMP] ASC, [MXC_MXCID] ASC),
    CONSTRAINT [CKC_MXC_APLICA_MAXIMA_C] CHECK ([MXC_APLICA]='I' OR [MXC_APLICA]='H'),
    CONSTRAINT [CKC_MXC_TIPO_MAXIMA_C] CHECK ([MXC_TIPO]='C' OR [MXC_TIPO]='M'),
    CONSTRAINT [FK_MAXIMA_C_MONEDAS_M_MONEDAS] FOREIGN KEY ([MXC_CODEMP], [MXC_CODMON]) REFERENCES [dbo].[MONEDAS] ([MON_CODEMP], [MON_CODMON]),
    CONSTRAINT [FK_MAXIMA_C_TIPCPBT_M_TIPOS_CP] FOREIGN KEY ([MXC_CODEMP], [MXC_TPCID]) REFERENCES [dbo].[TIPOS_CPBTDOC] ([TPC_CODEMP], [TPC_TPCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[MAXIMA_CONVENCIONAL]([MXC_CODEMP] ASC, [MXC_MXCID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla ,almacena los distitnos valores de la maxima convencional para los honorarios', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MAXIMA_CONVENCIONAL';

