CREATE TABLE [dbo].[MENU] (
    [MEN_MENID]      INT            NOT NULL,
    [MEN_NOMBRE]     VARCHAR (400)  NOT NULL,
    [MEN_IMAGEN]     VARCHAR (100)  NOT NULL,
    [MEN_ORDEN]      SMALLINT       DEFAULT ((5)) NOT NULL,
    [MEN_DIRECTORIO] VARCHAR (1000) NOT NULL,
    CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED ([MEN_MENID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[MENU]([MEN_MENID] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[MENU]([MEN_NOMBRE] ASC);

