CREATE TABLE [dbo].[MENU_IDIOMAS] (
    [MNI_MENID]  INT           NOT NULL,
    [MNI_IDID]   INT           NOT NULL,
    [MNI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_MENU_IDIOMAS] PRIMARY KEY CLUSTERED ([MNI_MENID] ASC, [MNI_IDID] ASC),
    CONSTRAINT [FK_MENU_IDI_IDIOMAS_M_IDIOMAS] FOREIGN KEY ([MNI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_MENU_IDI_MENU_IDIO_MENU] FOREIGN KEY ([MNI_MENID]) REFERENCES [dbo].[MENU] ([MEN_MENID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[MENU_IDIOMAS]([MNI_MENID] ASC, [MNI_IDID] ASC);

