CREATE TABLE [dbo].[MUTUAL_LEY_REAJUSTE] (
    [FECHA_PAGO]    DATETIME        NOT NULL,
    [PERIODO]       VARCHAR (150)   NOT NULL,
    [FECHA_INICIAL] DATETIME        NOT NULL,
    [FECHA_FINAL]   DATETIME        NOT NULL,
    [REAJUSTE]      DECIMAL (15, 2) NOT NULL
);

