CREATE TABLE [dbo].[MUTUAL_LEY_DIVISION] (
    [DIVISION]           INT           NOT NULL,
    [NOMBRE_REAL]        VARCHAR (50)  NULL,
    [NOMBRE_LIQUIDACION] VARCHAR (50)  NULL,
    [NOMBRE_ENCARGADO]   VARCHAR (150) NULL,
    [TELEFONO]           VARCHAR (50)  NULL,
    [EMAIL]              VARCHAR (150) NULL,
    [DIRECCION]          VARCHAR (150) NULL,
    CONSTRAINT [PK_MUTUAL_LEY_DIVISION] PRIMARY KEY CLUSTERED ([DIVISION] ASC)
);

