CREATE TABLE [dbo].[NEGOCIACION_ESTADOS_HISTORIAL] (
    [NGH_CODEMP]     INT            NOT NULL,
    [NGH_ANIO]       SMALLINT       NOT NULL,
    [NGH_NEGID]      INT            NOT NULL,
    [NGH_FECHA]      DATETIME       NOT NULL,
    [NGH_ESTADO]     CHAR (1)       NOT NULL,
    [NGH_COMENTARIO] VARCHAR (1000) NOT NULL,
    [NGH_USRID]      INT            NULL,
    CONSTRAINT [PK_NEGOCIACION_ESTADOS_HISTORI] PRIMARY KEY CLUSTERED ([NGH_CODEMP] ASC, [NGH_ANIO] ASC, [NGH_NEGID] ASC, [NGH_FECHA] ASC, [NGH_ESTADO] ASC),
    CONSTRAINT [FK_NEGOCIAC_NEGOCIACI_NEGOCIAC] FOREIGN KEY ([NGH_CODEMP], [NGH_ANIO], [NGH_NEGID]) REFERENCES [dbo].[NEGOCIACION] ([NEG_CODEMP], [NEG_ANIO], [NEG_NEGID]),
    CONSTRAINT [FK_NEGOCIAC_USU_NEGES_USUARIOS] FOREIGN KEY ([NGH_CODEMP], [NGH_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[NEGOCIACION_ESTADOS_HISTORIAL]([NGH_CODEMP] ASC, [NGH_ANIO] ASC, [NGH_NEGID] ASC, [NGH_FECHA] ASC, [NGH_ESTADO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos estados por los cuales atravezo la negociacion y quien fue el responsable', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NEGOCIACION_ESTADOS_HISTORIAL';

