CREATE TABLE [dbo].[NEGOCIACION_CPBTDOC] (
    [NGD_CODEMP]       INT             NOT NULL,
    [NGD_ANIO]         SMALLINT        NOT NULL,
    [NGD_NEGID]        INT             NOT NULL,
    [NGD_PCLID]        NUMERIC (15)    NOT NULL,
    [NGD_CTCID]        NUMERIC (15)    NOT NULL,
    [NGD_CCBID]        INT             NOT NULL,
    [NGD_MONTO]        DECIMAL (15, 2) NOT NULL,
    [NGD_MONTO_N]      DECIMAL (15, 2) NOT NULL,
    [NGD_INTERESES]    DECIMAL (15, 2) NOT NULL,
    [NGD_INTERESES_N]  DECIMAL (15, 2) NOT NULL,
    [NGD_HONORARIOS]   DECIMAL (15, 2) NOT NULL,
    [NGD_HONORARIOS_N] DECIMAL (15, 2) NOT NULL,
    [NGD_GASTJUD]      DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [NGD_GASTJUD_N]    DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [NGD_GASTOTRO]     DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [NGD_GASTOTRO_N]   DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_NEGOCIACION_CPBTDOC] PRIMARY KEY CLUSTERED ([NGD_CODEMP] ASC, [NGD_ANIO] ASC, [NGD_NEGID] ASC, [NGD_PCLID] ASC, [NGD_CTCID] ASC, [NGD_CCBID] ASC),
    CONSTRAINT [FK_NEGOCIAC_CPBTDOC_N_CARTERA_] FOREIGN KEY ([NGD_CODEMP], [NGD_PCLID], [NGD_CTCID], [NGD_CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_NEGOCIAC_NEG_CPBTD_NEGOCIAC] FOREIGN KEY ([NGD_CODEMP], [NGD_ANIO], [NGD_NEGID]) REFERENCES [dbo].[NEGOCIACION] ([NEG_CODEMP], [NEG_ANIO], [NEG_NEGID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[NEGOCIACION_CPBTDOC]([NGD_CODEMP] ASC, [NGD_ANIO] ASC, [NGD_NEGID] ASC, [NGD_PCLID] ASC, [NGD_CTCID] ASC, [NGD_CCBID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos documentos que se han negociado', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NEGOCIACION_CPBTDOC';

