CREATE TABLE [dbo].[NOTICIAS_IDIOMAS] (
    [NEI_CODEMP] INT           NOT NULL,
    [NEI_NTEID]  INT           NOT NULL,
    [NEI_IDID]   INT           NOT NULL,
    [NEI_TITULO] VARCHAR (800) NOT NULL,
    [NEI_TEXTO]  TEXT          NOT NULL,
    CONSTRAINT [PK_NOTICIAS_IDIOMAS] PRIMARY KEY CLUSTERED ([NEI_CODEMP] ASC, [NEI_NTEID] ASC, [NEI_IDID] ASC),
    CONSTRAINT [FK_NOTICIAS_IDIOMAS_N_IDIOMAS] FOREIGN KEY ([NEI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_NOTICIAS_NOTICIAS__NOTICIAS] FOREIGN KEY ([NEI_CODEMP], [NEI_NTEID]) REFERENCES [dbo].[NOTICIAS] ([NTE_CODEMP], [NTE_NTEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[NOTICIAS_IDIOMAS]([NEI_CODEMP] ASC, [NEI_NTEID] ASC, [NEI_IDID] ASC);

