CREATE TABLE [dbo].[PANEL_DEMANDA_PREVISIONAL_DETALLE] (
    [PANEL_ID]             INT            NOT NULL,
    [USRID_ENCARGADO]      INT            NOT NULL,
    [FEC_ENVIO]            DATETIME       CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_DETALLE_FEC_ENVIO] DEFAULT (getdate()) NOT NULL,
    [FEC_ENTREGA]          DATETIME       NULL,
    [FEC_INGRESO_TRIBUNAL] DATETIME       NULL,
    [ROL_ADJUDICADO]       VARCHAR (30)   NULL,
    [ROLID]                INT            NULL,
    [COMENTARIOS]          VARCHAR (1000) NULL,
    [USRID_REGISTRO]       INT            NOT NULL,
    [FEC_REGISTRO]         DATETIME       CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_DETALLE_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_PREVISIONAL_DETALLE] PRIMARY KEY CLUSTERED ([PANEL_ID] ASC),
    CONSTRAINT [FK_PANEL_DEMANDA_PREVISIONAL_DETALLE_PANEL_DEMANDA_PREVISIONAL] FOREIGN KEY ([PANEL_ID]) REFERENCES [dbo].[PANEL_DEMANDA_PREVISIONAL] ([PANEL_ID])
);

