CREATE TABLE [dbo].[PANEL_DEMANDA_MASIVA_DOCUMENTOS] (
    [ID_PANEL_MASIVO] INT          NOT NULL,
    [CODEMP]          INT          NOT NULL,
    [PCLID]           NUMERIC (15) NOT NULL,
    [CTCID]           NUMERIC (15) NOT NULL,
    [CCBID]           INT          NOT NULL,
    [ESTADO]          VARCHAR (3)  CONSTRAINT [DF_PANEL_DEMANDA_MASIVA_DOCUMENTOS_ESTADO] DEFAULT ('ACT') NOT NULL,
    [USRID]           INT          NOT NULL,
    [FECHA_REG]       DATETIME     CONSTRAINT [DF_PANEL_DEMANDA_MASIVA_DOCUMENTOS_FECHA_REG] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_MASIVA_DOCUMENTOS] PRIMARY KEY CLUSTERED ([ID_PANEL_MASIVO] ASC, [CODEMP] ASC, [PCLID] ASC, [CTCID] ASC, [CCBID] ASC),
    CONSTRAINT [CKC_PANEL_DEMANDA_MASIVA_DOCUMENTOS_ESTADO] CHECK ([ESTADO]='ACT' OR [ESTADO]='INA'),
    CONSTRAINT [FK_PANEL_DEMANDA_MASIVA_DOCUMENTOS_CARTERA_CLIENTES_CPBT_DOC] FOREIGN KEY ([CODEMP], [PCLID], [CTCID], [CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_PANEL_DEMANDA_MASIVA_DOCUMENTOS_PANEL_DEMANDA_MASIVA] FOREIGN KEY ([ID_PANEL_MASIVO]) REFERENCES [dbo].[PANEL_DEMANDA_MASIVA] ([ID_PANEL_MASIVO])
);

