CREATE TABLE [dbo].[PANEL_QUIEBRA_REPARTOS] (
    [REPARTO_ID]     INT             NOT NULL,
    [QUIEBRA_ID]     INT             NOT NULL,
    [FEC_REPARTO]    DATETIME        NOT NULL,
    [MTO_REPARTO]    DECIMAL (15, 2) NOT NULL,
    [USRID_REGISTRO] INT             NOT NULL,
    [FEC_REGISTRO]   DATETIME        CONSTRAINT [DF_PANEL_QUIEBRA_REPARTOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_QUIEBRA_REPARTOS] PRIMARY KEY CLUSTERED ([REPARTO_ID] ASC),
    CONSTRAINT [FK_PANEL_QUIEBRA_REPARTOS_PANEL_QUIEBRA] FOREIGN KEY ([QUIEBRA_ID]) REFERENCES [dbo].[PANEL_QUIEBRA] ([QUIEBRA_ID])
);

