CREATE TABLE [dbo].[PANEL_DEMANDA_PREVISIONAL] (
    [PANEL_ID]       INT          NOT NULL,
    [CODEMP]         INT          NOT NULL,
    [PCLID]          NUMERIC (15) NOT NULL,
    [CTCID]          NUMERIC (15) NOT NULL,
    [SBCID]          INT          NULL,
    [TPCID]          INT          NULL,
    [PROCESADA]      VARCHAR (1)  CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_PROCESADA] DEFAULT ('N') NOT NULL,
    [USRID_REGISTRO] INT          NOT NULL,
    [FEC_REGISTRO]   DATETIME     CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [CURSODEMANDA]   VARCHAR (2)  NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_PREVISIONAL] PRIMARY KEY CLUSTERED ([PANEL_ID] ASC),
    CONSTRAINT [CKC_CURSODEMANDAPREVISIONAL] CHECK ([CURSODEMANDA]='SI' OR [CURSODEMANDA]='NO'),
    CONSTRAINT [CKC_PANEL_DEMANDA_PREVISIONAL_PROCESADA] CHECK ([PROCESADA]='N' OR [PROCESADA]='S')
);

