CREATE TABLE [dbo].[PANEL_DEMANDA_MASIVA_CORRECCION_HISTORIAL] (
    [ID_PANEL_MASIVO] INT      NOT NULL,
    [IDCORRECCION]    INT      NOT NULL,
    [FEC_ENTREGA]     DATETIME NULL,
    [USRID_REGISTRO]  INT      NOT NULL,
    [FEC_REGISTRO]    DATETIME CONSTRAINT [DF_PANEL_DEMANDA_MASIVA_CORRECCION_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_MASIVA_CORRECCION_HISTORIAL] PRIMARY KEY CLUSTERED ([IDCORRECCION] ASC),
    CONSTRAINT [FK_PANEL_DEMANDA_MASIVA_CORRECCION_HISTORIAL_PANEL_DEMANDA_MASIVA] FOREIGN KEY ([ID_PANEL_MASIVO]) REFERENCES [dbo].[PANEL_DEMANDA_MASIVA] ([ID_PANEL_MASIVO])
);

