CREATE TABLE [dbo].[PANEL_DEMANDA_PREVISIONAL_CURSODEMANDA_HISTORIAL] (
    [PANEL_ID]       INT           NOT NULL,
    [ID]             INT           NOT NULL,
    [CURSODEMANDA]   VARCHAR (2)   NOT NULL,
    [MOTIVO]         VARCHAR (200) NULL,
    [USRID_REGISTRO] INT           NOT NULL,
    [FEC_REGISTRO]   DATETIME      CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_CURSODEMANDA_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_PREVISIONAL_CURSODEMANDA_HISTORIAL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PANEL_DEMANDA_PREVISIONAL_CURSODEMANDA_HISTORIAL_PANEL_DEMANDA_PREVISIONAL] FOREIGN KEY ([PANEL_ID]) REFERENCES [dbo].[PANEL_DEMANDA_PREVISIONAL] ([PANEL_ID])
);

