CREATE TABLE [dbo].[PANEL_DEMANDA_CORRECCION_HISTORIAL] (
    [PANEL_ID]       INT      NOT NULL,
    [IDCORRECCION]   INT      NOT NULL,
    [FEC_ENTREGA]    DATETIME NULL,
    [USRID_REGISTRO] INT      NOT NULL,
    [FEC_REGISTRO]   DATETIME CONSTRAINT [DF_PANEL_DEMANDA_CORRECCION_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_CORRECCION_HISTORIAL] PRIMARY KEY CLUSTERED ([IDCORRECCION] ASC),
    CONSTRAINT [FK_PANEL_DEMANDA_CORRECCION_HISTORIAL_PANEL_DEMANDA] FOREIGN KEY ([PANEL_ID]) REFERENCES [dbo].[PANEL_DEMANDA] ([PANEL_ID])
);

