CREATE TABLE [dbo].[PANEL_QUIEBRA_SINDICO] (
    [CODEMP]         INT           NOT NULL,
    [ROLID]          INT           NOT NULL,
    [SINDICO]        VARCHAR (100) NOT NULL,
    [VEEDOR]         VARCHAR (100) NOT NULL,
    [USRID_REGISTRO] INT           NOT NULL,
    [FEC_REGISTRO]   DATETIME      CONSTRAINT [DF_PANEL_QUIEBRA_SINDICO_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [INTERVENTOR]    VARCHAR (100) NULL,
    CONSTRAINT [PK_PANEL_QUIEBRA_SINDICO] PRIMARY KEY CLUSTERED ([ROLID] ASC)
);

