CREATE TABLE [dbo].[PANEL_TRASPASOS_AVENIMIENTO] (
    [CODEMP]         INT          NOT NULL,
    [ROLID]          INT          NOT NULL,
    [ROLNUMERO]      VARCHAR (20) NOT NULL,
    [PCLID]          NUMERIC (15) NOT NULL,
    [CTCID]          NUMERIC (15) NOT NULL,
    [TRBID]          INT          NOT NULL,
    [USRID_REGISTRO] INT          NOT NULL,
    [FEC_REGISTRO]   DATETIME     CONSTRAINT [DF_PANEL_TRASPASOS_AVENIMIENTO_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [ESTATUS]        VARCHAR (1)  CONSTRAINT [DF_ESTATUS] DEFAULT ('E') NOT NULL,
    CONSTRAINT [PK_PANEL_TRASPASOS_AVENIMIENTO] PRIMARY KEY CLUSTERED ([ROLID] ASC),
    CONSTRAINT [CKC_ESTATUS] CHECK ([ESTATUS]='E' OR [ESTATUS]='A' OR [ESTATUS]='R')
);

