CREATE TABLE [dbo].[PANEL_DEMANDA_MASIVA_CONFECCION_OLD] (
    [PDMC_ID]       INT  NOT NULL,
    [PDMC_TEMPLATE] TEXT NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_MASIVA_CONFECCION] PRIMARY KEY CLUSTERED ([PDMC_ID] ASC)
);

