CREATE TABLE [dbo].[PANEL_DEMANDA_MASIVA_CURSODEMANDA_HISTORIAL] (
    [ID_PANEL_MASIVO] INT           NOT NULL,
    [ID]              INT           NOT NULL,
    [CURSODEMANDA]    VARCHAR (2)   NOT NULL,
    [MOTIVO]          VARCHAR (200) NULL,
    [USRID]           INT           NOT NULL,
    [FECHA_REG]       DATETIME      CONSTRAINT [DF_PANEL_DEMANDA_MASIVA_CURSODEMANDA_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL
);

