CREATE TABLE [dbo].[PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS] (
    [PANEL_ID]       INT          NOT NULL,
    [CODEMP]         INT          NOT NULL,
    [PCLID]          NUMERIC (15) NOT NULL,
    [CTCID]          NUMERIC (15) NOT NULL,
    [CCBID]          INT          NOT NULL,
    [ESTADO]         VARCHAR (3)  CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS_ESTADO] DEFAULT ('ACT') NOT NULL,
    [USRID_REGISTRO] INT          NOT NULL,
    [FEC_REGISTRO]   DATETIME     CONSTRAINT [DF_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS] PRIMARY KEY CLUSTERED ([PANEL_ID] ASC, [CODEMP] ASC, [PCLID] ASC, [CTCID] ASC, [CCBID] ASC),
    CONSTRAINT [CKC_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS_ESTADO] CHECK ([ESTADO]='ACT' OR [ESTADO]='INA'),
    CONSTRAINT [FK_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS_CARTERA_CLIENTES_CPBT_DOC] FOREIGN KEY ([CODEMP], [PCLID], [CTCID], [CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_PANEL_DEMANDA_PREVISIONAL_DOCUMENTOS_PANEL_DEMANDA_PREVISIONAL] FOREIGN KEY ([PANEL_ID]) REFERENCES [dbo].[PANEL_DEMANDA_PREVISIONAL] ([PANEL_ID])
);

