CREATE TABLE [dbo].[PERFILES_COMPROBANTES] (
    [PFC_CODEMP] INT NOT NULL,
    [PFC_PRFID]  INT NOT NULL,
    [PFC_TPCID]  INT NOT NULL,
    CONSTRAINT [PK_PERFILES_COMPROBANTES] PRIMARY KEY CLUSTERED ([PFC_CODEMP] ASC, [PFC_PRFID] ASC, [PFC_TPCID] ASC),
    CONSTRAINT [FK_PERFILES_CPBT_PERF_TIPOS_CP] FOREIGN KEY ([PFC_CODEMP], [PFC_TPCID]) REFERENCES [dbo].[TIPOS_CPBTDOC] ([TPC_CODEMP], [TPC_TPCID]),
    CONSTRAINT [FK_PERFILES_PERFILE_C_PERFILES] FOREIGN KEY ([PFC_CODEMP], [PFC_PRFID]) REFERENCES [dbo].[PERFILES] ([PRF_CODEMP], [PRF_PRFID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PERFILES_COMPROBANTES]([PFC_CODEMP] ASC, [PFC_PRFID] ASC, [PFC_TPCID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena el perfil, que comprobantes puede realizar', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PERFILES_COMPROBANTES';

