CREATE TABLE [dbo].[PERFILES_LISTAPRECIOS] (
    [PLP_CODEMP] INT NOT NULL,
    [PLP_PRFID]  INT NOT NULL,
    [PLP_LTPID]  INT NOT NULL,
    CONSTRAINT [PK_PERFILES_LISTAPRECIOS] PRIMARY KEY CLUSTERED ([PLP_CODEMP] ASC, [PLP_PRFID] ASC, [PLP_LTPID] ASC),
    CONSTRAINT [FK_PERFILES_LISTPRE_P_LISTAS_P] FOREIGN KEY ([PLP_CODEMP], [PLP_LTPID]) REFERENCES [dbo].[LISTAS_PRECIOS] ([LTP_CODEMP], [LTP_LTPID]),
    CONSTRAINT [FK_PERFILES_PERFIL_LI_PERFILES] FOREIGN KEY ([PLP_CODEMP], [PLP_PRFID]) REFERENCES [dbo].[PERFILES] ([PRF_CODEMP], [PRF_PRFID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PERFILES_LISTAPRECIOS]([PLP_CODEMP] ASC, [PLP_PRFID] ASC, [PLP_LTPID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas listas de precio que puede acceder el perfil', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PERFILES_LISTAPRECIOS';

