CREATE TABLE [dbo].[PERFILES_ESTADOS] (
    [PFE_CODEMP] INT      NOT NULL,
    [PFE_PRFID]  INT      NOT NULL,
    [PFE_ESTID]  SMALLINT NOT NULL,
    CONSTRAINT [PK_PERFILES_ESTADOS] PRIMARY KEY CLUSTERED ([PFE_CODEMP] ASC, [PFE_PRFID] ASC, [PFE_ESTID] ASC),
    CONSTRAINT [FK_PERFILES_ESTADOS_P_ESTADOS_] FOREIGN KEY ([PFE_CODEMP], [PFE_ESTID]) REFERENCES [dbo].[ESTADOS_CARTERA] ([ECT_CODEMP], [ECT_ESTID]),
    CONSTRAINT [FK_PERFILES_PERFILES__PERFILES] FOREIGN KEY ([PFE_CODEMP], [PFE_PRFID]) REFERENCES [dbo].[PERFILES] ([PRF_CODEMP], [PRF_PRFID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PERFILES_ESTADOS]([PFE_CODEMP] ASC, [PFE_PRFID] ASC, [PFE_ESTID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos estados de cobranza, para su respectivo permiso', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PERFILES_ESTADOS';

