CREATE TABLE [dbo].[PERFILES_ESTADOS_HISTORIAL] (
    [PERFIL_ID]      INT      NOT NULL,
    [ESTID]          INT      NOT NULL,
    [ACCION]         INT      NOT NULL,
    [USRID_REGISTRO] INT      NOT NULL,
    [FEC_REGISTRO]   DATETIME CONSTRAINT [DF_PERFILES_ESTADOS_HISTORIAL_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL
);

