CREATE TABLE [dbo].[PODER_JUDICIAL_MONITOREO_SII] (
    [PCLID]          INT             NOT NULL,
    [TOTAL_CARTERA]  DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_SII_TOTAL_CARTERA] DEFAULT ((0)) NOT NULL,
    [TOTAL_VERDE]    DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_SII_TOTAL_VERDE] DEFAULT ((0)) NOT NULL,
    [TOTAL_AMARILLO] DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_SII_TOTAL_AMARILLO] DEFAULT ((0)) NOT NULL,
    [TOTAL_ROJO]     DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_SII_DTOTAL_ROJO] DEFAULT ((0)) NOT NULL,
    [FEC_REGISTRO]   DATETIME        CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_SII_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PODER_JUDICIAL_MONITOREO_SII] PRIMARY KEY CLUSTERED ([PCLID] ASC)
);

