CREATE TABLE [dbo].[PODER_JUDICIAL_MONITOREO_EXTERNO] (
    [PCLID]              INT             NOT NULL,
    [TOTAL_CARTERA]      DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_EXTERNO_TOTAL_CARTERA] DEFAULT ((0)) NOT NULL,
    [TOTAL_SINDEMANDA]   DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_EXTERNO_TOTAL_SINDEMANDA] DEFAULT ((0)) NOT NULL,
    [TOTAL_DEMANDADO]    DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_EXTERNO_TOTAL_DEMANDADO] DEFAULT ((0)) NOT NULL,
    [DEMANDADO_DOSANIOS] DECIMAL (15, 2) CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_EXTERNO_DEMANDADO_DOSANIOS] DEFAULT ((0)) NOT NULL,
    [FEC_REGISTRO]       DATETIME        CONSTRAINT [DF_PODER_JUDICIAL_MONITOREO_EXTERNO_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PODER_JUDICIAL_MONITOREO_EXTERNO] PRIMARY KEY CLUSTERED ([PCLID] ASC)
);

