CREATE TABLE [dbo].[PODER_JUDICIAL_TIPO_CUADERNO] (
    [TIPO_CUADERNO] INT           NOT NULL,
    [CUADERNO]      VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_PODER_JUDICIAL_TIPO_CUADERNO] PRIMARY KEY CLUSTERED ([TIPO_CUADERNO] ASC)
);

