CREATE TABLE [dbo].[PRE_EMAIL_DEUDORES] (
    [CODEMP]            INT           NOT NULL,
    [CTCID]             NUMERIC (15)  NOT NULL,
    [EMAIL]             VARCHAR (255) NOT NULL,
    [FECHA_CREACION]    DATETIME      NOT NULL,
    [USUARIO_CREACION]  INT           NOT NULL,
    [FECHA_ENVIO]       DATETIME      NOT NULL,
    [ESTADO]            CHAR (1)      NOT NULL,
    [FECHA_ULT_MODIF]   DATETIME      NOT NULL,
    [USUARIO_ULT_MODIF] INT           NOT NULL,
    CONSTRAINT [PK_PRE_EMAIL_DEUDORES] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [CTCID] ASC, [EMAIL] ASC),
    CONSTRAINT [CKC_PRE_EMAIL_DEUDORES_ESTADO] CHECK ([ESTADO]='V' OR [ESTADO]='N'),
    CONSTRAINT [FK_PRE_EMAIL_DEUDORES_DEUDORES] FOREIGN KEY ([CODEMP], [CTCID]) REFERENCES [dbo].[DEUDORES] ([CTC_CODEMP], [CTC_CTCID])
);

