CREATE TABLE [dbo].[PROCESO_ITINERARIOS] (
    [CODEMP]               INT          NOT NULL,
    [PROCESO]              INT          NOT NULL,
    [DIA]                  INT          NOT NULL,
    [DIASEMANA]            VARCHAR (10) NOT NULL,
    [HORAINICIO]           TIME (7)     NOT NULL,
    [HORAFIN]              TIME (7)     NOT NULL,
    [USUARIO_INGRESO]      INT          NOT NULL,
    [FECHA_INGRESO]        DATETIME     NOT NULL,
    [USUARIO_MODIFICACION] INT          NOT NULL,
    [FECHA_MODIFICACION]   DATETIME     NOT NULL,
    CONSTRAINT [PROCESO_ITINERARIOS_PK] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PROCESO] ASC, [DIA] ASC),
    CONSTRAINT [CK_PROCESO_ITINERARIOS] CHECK ([DIA]>=(1) AND [DIA]<=(7) AND ([DIASEMANA]='Sábado' OR [DIASEMANA]='Sabado' OR [DIASEMANA]='Viernes' OR [DIASEMANA]='Jueves' OR [DIASEMANA]='Miércoles' OR [DIASEMANA]='Miercoles' OR [DIASEMANA]='Martes' OR [DIASEMANA]='Lunes' OR [DIASEMANA]='Domingo')),
    CONSTRAINT [CK_PROCESO_ITINERARIOSDIASEMANA] CHECK ([DIA]=(1) AND [DIASEMANA]='Domingo' OR [DIA]=(2) AND [DIASEMANA]='Lunes' OR [DIA]=(3) AND [DIASEMANA]='Martes' OR [DIA]=(4) AND [DIASEMANA]='Miercoles' OR [DIA]=(4) AND [DIASEMANA]='Miércoles' OR [DIA]=(5) AND [DIASEMANA]='Jueves' OR [DIA]=(6) AND [DIASEMANA]='Viernes' OR [DIA]=(7) AND [DIASEMANA]='Sabado' OR [DIA]=(7) AND [DIASEMANA]='Sábado'),
    CONSTRAINT [FK_PROCESO_ITINERARIOSPROCESO] FOREIGN KEY ([CODEMP], [PROCESO]) REFERENCES [dbo].[PROCESO] ([CODEMP], [PROCESO])
);

