CREATE TABLE [dbo].[PRODUCTOS_IMAGENES] (
    [PDI_CODEMP]  INT          NOT NULL,
    [PDI_PRODID]  NUMERIC (15) NOT NULL,
    [PDI_PDIID]   INT          NOT NULL,
    [PDI_IMAGEN]  IMAGE        NOT NULL,
    [PDI_DEFAULT] CHAR (1)     DEFAULT ('N') NOT NULL,
    [PDI_ORDEN]   SMALLINT     NOT NULL,
    CONSTRAINT [PK_PRODUCTOS_IMAGENES] PRIMARY KEY NONCLUSTERED ([PDI_CODEMP] ASC, [PDI_PRODID] ASC, [PDI_PDIID] ASC),
    CONSTRAINT [CKC_PDI_DEFAULT_PRODUCTO] CHECK ([PDI_DEFAULT]='N' OR [PDI_DEFAULT]='S'),
    CONSTRAINT [FK_PRODUCTO_PRODUCTOS_PRODUCTO5] FOREIGN KEY ([PDI_CODEMP], [PDI_PRODID]) REFERENCES [dbo].[PRODUCTOS] ([PDT_CODEMP], [PDT_PRODID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PRODUCTOS_IMAGENES]([PDI_CODEMP] ASC, [PDI_PRODID] ASC, [PDI_PDIID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena las distintas imagenes del producto, se creara una galeria de imagen', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRODUCTOS_IMAGENES';

