CREATE TABLE [dbo].[PRODUCTOS_DOCUMENTOS_IDIOMAS] (
    [PDI_CODEMP]    INT           NOT NULL,
    [PDI_PRODID]    NUMERIC (15)  NOT NULL,
    [PDI_TPDID]     INT           NOT NULL,
    [PDI_IDID]      INT           NOT NULL,
    [PDI_DOCUMENTO] VARCHAR (300) NOT NULL,
    CONSTRAINT [PK_PRODUCTOS_DOCUMENTOS_IDIOMA] PRIMARY KEY CLUSTERED ([PDI_CODEMP] ASC, [PDI_PRODID] ASC, [PDI_TPDID] ASC, [PDI_IDID] ASC, [PDI_DOCUMENTO] ASC),
    CONSTRAINT [FK_PRODUCTO_IDIOMAS_P_IDIOMAS] FOREIGN KEY ([PDI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_PRODUCTO_PRODDOC_I_PRODUCTO] FOREIGN KEY ([PDI_CODEMP], [PDI_TPDID], [PDI_PRODID]) REFERENCES [dbo].[PRODUCTOS_DOCUMENTOS] ([PDC_CODEMP], [PDC_TPDID], [PDC_PRODID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PRODUCTOS_DOCUMENTOS_IDIOMAS]([PDI_CODEMP] ASC, [PDI_PRODID] ASC, [PDI_TPDID] ASC, [PDI_IDID] ASC, [PDI_DOCUMENTO] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla podra almacenar los distintos documentos en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRODUCTOS_DOCUMENTOS_IDIOMAS';

