CREATE TABLE [dbo].[PRODUCTOS_INSUMOS] (
    [PTI_CODEMP]   INT             NOT NULL,
    [PTI_PRODID]   NUMERIC (15)    NOT NULL,
    [PTI_INSID]    NUMERIC (15)    NOT NULL,
    [PTI_CANTIDAD] DECIMAL (15, 2) NOT NULL,
    [PTI_FECING]   DATETIME        NOT NULL,
    CONSTRAINT [PK_PRODUCTOS_INSUMOS] PRIMARY KEY NONCLUSTERED ([PTI_CODEMP] ASC, [PTI_PRODID] ASC, [PTI_INSID] ASC),
    CONSTRAINT [FK_PRODUCTO_INSUMOS_P_INSUMOS] FOREIGN KEY ([PTI_CODEMP], [PTI_INSID]) REFERENCES [dbo].[INSUMOS] ([INS_CODEMP], [INS_INSID]),
    CONSTRAINT [FK_PRODUCTO_PRODUCTOS_PRODUCTO7] FOREIGN KEY ([PTI_CODEMP], [PTI_PRODID]) REFERENCES [dbo].[PRODUCTOS] ([PDT_CODEMP], [PDT_PRODID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PRODUCTOS_INSUMOS]([PTI_CODEMP] ASC, [PTI_PRODID] ASC, [PTI_INSID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos insumos que contendran para armar un producto nuevo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRODUCTOS_INSUMOS';

