CREATE TABLE [dbo].[PRODUCTOS_MONEDA] (
    [PDM_CODEMP] INT             NOT NULL,
    [PDM_PRODID] NUMERIC (15)    NOT NULL,
    [PDM_CODMON] INT             NOT NULL,
    [PDM_PRECIO] DECIMAL (25, 2) NOT NULL,
    CONSTRAINT [PK_PRODUCTOS_MONEDA] PRIMARY KEY NONCLUSTERED ([PDM_CODEMP] ASC, [PDM_PRODID] ASC, [PDM_CODMON] ASC),
    CONSTRAINT [FK_PRODUCTO_MONEDAS_P_MONEDAS] FOREIGN KEY ([PDM_CODEMP], [PDM_CODMON]) REFERENCES [dbo].[MONEDAS] ([MON_CODEMP], [MON_CODMON]),
    CONSTRAINT [FK_PRODUCTO_PRODUCTOS_PRODUCTO6] FOREIGN KEY ([PDM_CODEMP], [PDM_PRODID]) REFERENCES [dbo].[PRODUCTOS] ([PDT_CODEMP], [PDT_PRODID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PRODUCTOS_MONEDA]([PDM_CODEMP] ASC, [PDM_PRODID] ASC, [PDM_CODMON] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos precios de los productos en su respectiva moneda', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRODUCTOS_MONEDA';

