CREATE TABLE [dbo].[PROVCLI_LISTAS] (
    [PLP_CODEMP] INT          NOT NULL,
    [PLP_PCLID]  NUMERIC (15) NOT NULL,
    [PLP_LTPID]  INT          NOT NULL,
    CONSTRAINT [PK_PROVCLI_LISTAS] PRIMARY KEY CLUSTERED ([PLP_CODEMP] ASC, [PLP_PCLID] ASC, [PLP_LTPID] ASC),
    CONSTRAINT [FK_PROVCLI__LISTA_PRO_LISTAS_P] FOREIGN KEY ([PLP_CODEMP], [PLP_LTPID]) REFERENCES [dbo].[LISTAS_PRECIOS] ([LTP_CODEMP], [LTP_LTPID]),
    CONSTRAINT [FK_PROVCLI__PROVCLI_L_PROVCLI] FOREIGN KEY ([PLP_CODEMP], [PLP_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PROVCLI_LISTAS]([PLP_CODEMP] ASC, [PLP_PCLID] ASC, [PLP_LTPID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas listas de precios de los clientes', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PROVCLI_LISTAS';

