CREATE TABLE [dbo].[PROVCLI_CODIGO_CARGA] (
    [PCC_CODEMP] INT           NOT NULL,
    [PCC_PCLID]  NUMERIC (15)  NOT NULL,
    [PCC_CODID]  INT           NOT NULL,
    [PCC_CODIGO] VARCHAR (20)  NOT NULL,
    [PCC_NOMBRE] VARCHAR (120) NOT NULL,
    CONSTRAINT [PK_PROVCLI_CODIGO_CARGA] PRIMARY KEY NONCLUSTERED ([PCC_CODEMP] ASC, [PCC_PCLID] ASC, [PCC_CODID] ASC),
    CONSTRAINT [FK_PROVCLI__PROVCLI_C_PROVCLI] FOREIGN KEY ([PCC_CODEMP], [PCC_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PROVCLI_CODIGO_CARGA]([PCC_CODEMP] ASC, [PCC_PCLID] ASC, [PCC_CODID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_CODIGO]
    ON [dbo].[PROVCLI_CODIGO_CARGA]([PCC_CODEMP] ASC, [PCC_PCLID] ASC, [PCC_CODIGO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[PROVCLI_CODIGO_CARGA]([PCC_CODEMP] ASC, [PCC_PCLID] ASC, [PCC_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacenara los distintos codigos de carga para cada cartera, de esta forma se podra separar cada una de ellas.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PROVCLI_CODIGO_CARGA';

