CREATE TABLE [dbo].[PROVCLI_EJECUTIVO] (
    [PCLID]        NUMERIC (15) NOT NULL,
    [ID_EJECUTIVO] INT          NOT NULL,
    CONSTRAINT [PK_PROVCLI_EJECUTIVO] PRIMARY KEY CLUSTERED ([PCLID] ASC, [ID_EJECUTIVO] ASC)
);

