CREATE TABLE [dbo].[PROVCLI_PRODUCTO] (
    [PDT_CODEMP]      INT           NOT NULL,
    [PDT_PCLID]       NUMERIC (15)  NOT NULL,
    [PDT_PDTID]       INT           NOT NULL,
    [PDT_NOMBRE]      VARCHAR (150) NOT NULL,
    [PDT_DESCRIPCION] INT           NULL,
    CONSTRAINT [PK_PROVCLI_PRODUCTO] PRIMARY KEY NONCLUSTERED ([PDT_CODEMP] ASC, [PDT_PCLID] ASC, [PDT_PDTID] ASC)
);

