CREATE TABLE [dbo].[PROVCLI_BANCO] (
    [CODEMP]      INT           NOT NULL,
    [PCLID]       NUMERIC (15)  NOT NULL,
    [IDBANCO]     INT           NOT NULL,
    [NOMBRE]      VARCHAR (150) NULL,
    [CUENTA]      VARCHAR (25)  NULL,
    [TIPO]        INT           NOT NULL,
    [POR_DEFECTO] VARCHAR (1)   NULL,
    CONSTRAINT [PK_BANCO] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [IDBANCO] ASC),
    CONSTRAINT [FK_PROVCLI_BANCO] FOREIGN KEY ([CODEMP], [PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_PROVCLI_MONEDAS] FOREIGN KEY ([CODEMP], [TIPO]) REFERENCES [dbo].[MONEDAS] ([MON_CODEMP], [MON_CODMON])
);

