CREATE TABLE [dbo].[PROVCLI_DESPACHOS] (
    [PCD_CODEMP]    INT           NOT NULL,
    [PCD_PCLID]     NUMERIC (15)  NOT NULL,
    [PCD_PCDID]     INT           NOT NULL,
    [PCD_NOMBRE]    VARCHAR (200) NOT NULL,
    [PCD_COMID]     INT           NOT NULL,
    [PCD_DIRECCION] VARCHAR (200) NOT NULL,
    [PCD_CODIGO]    VARCHAR (10)  NULL,
    CONSTRAINT [PK_PROVCLI_DESPACHOS] PRIMARY KEY CLUSTERED ([PCD_CODEMP] ASC, [PCD_PCLID] ASC, [PCD_PCDID] ASC),
    CONSTRAINT [FK_PROVCLI__COM_PROVD_COMUNA] FOREIGN KEY ([PCD_COMID]) REFERENCES [dbo].[COMUNA] ([COM_COMID]),
    CONSTRAINT [FK_PROVCLI__PROVCLI_D_PROVCLI] FOREIGN KEY ([PCD_CODEMP], [PCD_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PROVCLI_DESPACHOS]([PCD_CODEMP] ASC, [PCD_PCLID] ASC, [PCD_PCDID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[PROVCLI_DESPACHOS]([PCD_CODEMP] ASC, [PCD_PCLID] ASC, [PCD_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos puntos de despacho de cada cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PROVCLI_DESPACHOS';

