CREATE TABLE [dbo].[PROVCLI_IMPUESTOS] (
    [PCI_CODEMP] INT          NOT NULL,
    [PCI_PCLID]  NUMERIC (15) NOT NULL,
    [PCI_IPTID]  SMALLINT     NOT NULL,
    CONSTRAINT [PK_PROVCLI_IMPUESTOS] PRIMARY KEY NONCLUSTERED ([PCI_CODEMP] ASC, [PCI_PCLID] ASC, [PCI_IPTID] ASC),
    CONSTRAINT [FK_PROVCLI__IMPUESTOS_IMPUESTO] FOREIGN KEY ([PCI_CODEMP], [PCI_IPTID]) REFERENCES [dbo].[IMPUESTOS] ([IPT_CODEMP], [IPT_IPTID]),
    CONSTRAINT [FK_PROVCLI__PROVCLI_I_PROVCLI] FOREIGN KEY ([PCI_CODEMP], [PCI_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[PROVCLI_IMPUESTOS]([PCI_CODEMP] ASC, [PCI_PCLID] ASC, [PCI_IPTID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos impuestos para cada cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PROVCLI_IMPUESTOS';

