CREATE TABLE [dbo].[REMESA] (
    [REMESA_ID]      INT      NOT NULL,
    [USRID_REGISTRO] INT      NOT NULL,
    [FEC_REGISTRO]   DATETIME CONSTRAINT [DF_REMESA_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_REMESA] PRIMARY KEY CLUSTERED ([REMESA_ID] ASC)
);

