CREATE TABLE [dbo].[REPORTES_IDIOMAS] (
    [RTI_TRVID]  INT           NOT NULL,
    [RTI_RPTID]  SMALLINT      NOT NULL,
    [RTI_IDID]   INT           NOT NULL,
    [RTI_NOMBRE] VARCHAR (250) NOT NULL,
    [RTI_FISICO] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_REPORTES_IDIOMAS] PRIMARY KEY CLUSTERED ([RTI_TRVID] ASC, [RTI_RPTID] ASC, [RTI_IDID] ASC),
    CONSTRAINT [FK_REPORTES_IDIOMAS_R_IDIOMAS] FOREIGN KEY ([RTI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_REPORTES_REFERENCE_REPORTES] FOREIGN KEY ([RTI_TRVID], [RTI_RPTID]) REFERENCES [dbo].[REPORTES] ([RPT_TRVID], [RPT_RPTID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[REPORTES_IDIOMAS]([RTI_TRVID] ASC, [RTI_RPTID] ASC, [RTI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de reportes en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'REPORTES_IDIOMAS';

