CREATE TABLE [dbo].[ROL BORRADOR] (
    [CODEMP]         INT      NOT NULL,
    [ID_BORRADOR]    INT      NOT NULL,
    [ID_VERSION]     INT      NOT NULL,
    [ROLID]          INT      NOT NULL,
    [CORRELATIVO]    INT      IDENTITY (1, 1) NOT NULL,
    [HTML]           TEXT     NOT NULL,
    [FECHA_CREACION] DATETIME NOT NULL,
    [USER_CREACION]  INT      NOT NULL,
    CONSTRAINT [PK_ROL BORRADOR] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_BORRADOR] ASC, [ID_VERSION] ASC, [CORRELATIVO] ASC),
    CONSTRAINT [FK_ROL BORRADOR_ROL] FOREIGN KEY ([CODEMP], [ROLID]) REFERENCES [dbo].[ROL] ([ROL_CODEMP], [ROL_ROLID]),
    CONSTRAINT [FK_ROL_BORRADOR_USUARIO] FOREIGN KEY ([CODEMP], [USER_CREACION]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID]),
    CONSTRAINT [FK_ROL_BORRADOR_VERSION_BORRADOR] FOREIGN KEY ([CODEMP], [ID_BORRADOR], [ID_VERSION]) REFERENCES [dbo].[BORRADOR_VERSION] ([CODEMP], [ID_BORRADOR], [ID_VERSION])
);

