CREATE TABLE [dbo].[ROL_ACTUALIZA_PODERJUDICIAL_HISTORIAL] (
    [CODEMP]             INT         NOT NULL,
    [ROLID]              INT         NOT NULL,
    [FLAG_PODERJUDICIAL] VARCHAR (1) NOT NULL,
    [USERID]             INT         NOT NULL,
    [FEC_REGISTRO]       DATETIME    CONSTRAINT [DF__ROL_ACTUA__FEC_R__051B5D5D] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_ROL_ACTUALIZA_PODERJUDICIAL_HISTORIAL] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ROLID] ASC, [FEC_REGISTRO] ASC)
);

