CREATE TABLE [dbo].[ROL_DOCUMENTOS] (
    [RDC_CODEMP] INT             NOT NULL,
    [RDC_ROLID]  INT             NOT NULL,
    [RDC_PCLID]  NUMERIC (15)    NOT NULL,
    [RDC_CTCID]  NUMERIC (15)    NOT NULL,
    [RDC_CCBID]  INT             NOT NULL,
    [RDC_MONTO]  DECIMAL (15, 2) NOT NULL,
    [RDC_SALDO]  DECIMAL (15, 2) NOT NULL,
    CONSTRAINT [PK_ROL_DOCUMENTOS] PRIMARY KEY CLUSTERED ([RDC_CODEMP] ASC, [RDC_ROLID] ASC, [RDC_PCLID] ASC, [RDC_CTCID] ASC, [RDC_CCBID] ASC),
    CONSTRAINT [FK_ROL_DOCU_CARTCPBT__CARTERA_] FOREIGN KEY ([RDC_CODEMP], [RDC_PCLID], [RDC_CTCID], [RDC_CCBID]) REFERENCES [dbo].[CARTERA_CLIENTES_CPBT_DOC] ([CCB_CODEMP], [CCB_PCLID], [CCB_CTCID], [CCB_CCBID]),
    CONSTRAINT [FK_ROL_DOCU_ROL_DOCUM_ROL] FOREIGN KEY ([RDC_CODEMP], [RDC_ROLID]) REFERENCES [dbo].[ROL] ([ROL_CODEMP], [ROL_ROLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[ROL_DOCUMENTOS]([RDC_CODEMP] ASC, [RDC_ROLID] ASC, [RDC_PCLID] ASC, [RDC_CTCID] ASC, [RDC_CCBID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos documentos que seran demandados', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ROL_DOCUMENTOS';

