CREATE TABLE [dbo].[SERVICIOS_IDIOMAS] (
    [SVI_CODEMP] INT           NOT NULL,
    [SVI_SVEID]  INT           NOT NULL,
    [SVI_IDID]   INT           NOT NULL,
    [SVI_TITULO] VARCHAR (200) NOT NULL,
    [SVI_TEXTO]  TEXT          NOT NULL,
    CONSTRAINT [PK_SERVICIOS_IDIOMAS] PRIMARY KEY CLUSTERED ([SVI_CODEMP] ASC, [SVI_SVEID] ASC, [SVI_IDID] ASC),
    CONSTRAINT [FK_SERVICIO_IDIOMAS_S_IDIOMAS] FOREIGN KEY ([SVI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_SERVICIO_SERVICIOS_SERVICIO] FOREIGN KEY ([SVI_CODEMP], [SVI_SVEID]) REFERENCES [dbo].[SERVICIOS] ([SVE_CODEMP], [SVE_SVEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[SERVICIOS_IDIOMAS]([SVI_CODEMP] ASC, [SVI_SVEID] ASC, [SVI_IDID] ASC);

