CREATE TABLE [dbo].[SITREL_OPERACION_20161124] (
    [CODEMP]              INT             NOT NULL,
    [ID_CARGA]            INT             NOT NULL,
    [PCLID]               INT             NOT NULL,
    [RUT]                 VARCHAR (9)     NOT NULL,
    [NUMERO_OPERACION]    VARCHAR (24)    NOT NULL,
    [CODIGO_PRODUCTO]     VARCHAR (20)    NOT NULL,
    [NOMBRE_PRODUCTO]     VARCHAR (50)    NOT NULL,
    [TIPO_DEUDOR]         VARCHAR (20)    NOT NULL,
    [MONEDA]              VARCHAR (20)    NOT NULL,
    [MONTO_MORA]          DECIMAL (15, 2) NOT NULL,
    [SALDO_INSOLUTO]      DECIMAL (15, 2) NOT NULL,
    [MONTO_OPERACION]     DECIMAL (15, 2) NOT NULL,
    [DEUDA_TOTAL]         DECIMAL (15, 2) NOT NULL,
    [DIAS_MORA]           INT             NOT NULL,
    [EJECUTIVO_CUENTA]    VARCHAR (50)    NULL,
    [MONTO_TOTAL_INTERES] DECIMAL (15, 2) NULL,
    [ESTADO_PRODUCTO]     VARCHAR (11)    NULL,
    [FECHA_ULTIMO_PAGO]   INT             NULL,
    [CAMPANIA]            VARCHAR (20)    NOT NULL,
    [ACCION]              VARCHAR (50)    NULL,
    [CONTACTO]            VARCHAR (50)    NULL,
    [RESPUESTA]           VARCHAR (50)    NULL,
    [GLOSA]               VARCHAR (255)   NULL,
    [FECHA_GESTION]       DATETIME        NULL,
    [CODIGO_SUCURSAL]     VARCHAR (20)    NOT NULL,
    [NOMBRE_SUCURSAL]     VARCHAR (50)    NOT NULL,
    [DIRECCION_SUCURSAL]  VARCHAR (255)   NOT NULL,
    [TELEFONO_SUCURSAL]   VARCHAR (20)    NOT NULL,
    [FECHA_VENCIMIENTO]   INT             NOT NULL,
    [NOMBRE_ESTRATEGIA]   VARCHAR (50)    NOT NULL,
    [TIPO_PERSONA]        VARCHAR (7)     NOT NULL,
    CONSTRAINT [PK_SITREL_OPERACION] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_CARGA] ASC, [PCLID] ASC, [RUT] ASC, [NUMERO_OPERACION] ASC, [CODIGO_PRODUCTO] ASC),
    CONSTRAINT [FK_SITREL_OPERACION_DEUDOR] FOREIGN KEY ([CODEMP], [ID_CARGA], [PCLID], [RUT], [TIPO_PERSONA]) REFERENCES [dbo].[SITREL_DEUDOR] ([CODEMP], [ID_CARGA], [PCLID], [RUT], [TIPO_PERSONA]),
    CONSTRAINT [FK_SITREL_OPERACION_SUCURSAL] FOREIGN KEY ([CODEMP], [PCLID], [CODIGO_SUCURSAL]) REFERENCES [dbo].[SITREL_SUCURSAL] ([CODEMP], [PCLID], [CODIGO])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_SITREL_OPERACION_5_1130539161__K1_K3]
    ON [dbo].[SITREL_OPERACION_20161124]([CODEMP] ASC, [PCLID] ASC);

