CREATE TABLE [dbo].[SITREL_CARGA] (
    [CODEMP]      INT           NOT NULL,
    [PCLID]       INT           NOT NULL,
    [ID_CARGA]    INT           IDENTITY (1, 1) NOT NULL,
    [FECHA_CARGA] DATETIME      NOT NULL,
    [ESTADO]      VARCHAR (2)   NULL,
    [ERROR]       VARCHAR (300) NULL,
    CONSTRAINT [PK_SITREL_CARGA] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [ID_CARGA] ASC)
);

