CREATE TABLE [dbo].[SITREL_ARCHIVO] (
    [CODEMP]         INT           NOT NULL,
    [PCLID]          INT           NOT NULL,
    [ID_CARGA]       INT           NOT NULL,
    [CODIGO_ARCHIVO] INT           NOT NULL,
    [FECHA_ARCHIVO]  DATE          NOT NULL,
    [NOMBRE_ARCHIVO] VARCHAR (200) NOT NULL,
    [ESTADO]         VARCHAR (2)   NULL,
    [ERROR]          VARCHAR (300) NULL,
    CONSTRAINT [PK_SITREL_ARCHIVO] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [ID_CARGA] ASC, [CODIGO_ARCHIVO] ASC),
    CONSTRAINT [FK_SITREL_ARCHIVO_CARGA] FOREIGN KEY ([CODEMP], [PCLID], [ID_CARGA]) REFERENCES [dbo].[SITREL_CARGA] ([CODEMP], [PCLID], [ID_CARGA]),
    CONSTRAINT [FK_SITREL_ARCHIVO_TIPO_ARCHIVO] FOREIGN KEY ([CODEMP], [CODIGO_ARCHIVO]) REFERENCES [dbo].[SITREL_TIPO_ARCHIVO] ([CODEMP], [TIPO_ARCHIVO])
);

