CREATE TABLE [dbo].[SITREL_DEUDOR] (
    [CODEMP]             INT          NOT NULL,
    [ID_CARGA]           INT          NOT NULL,
    [PCLID]              INT          NOT NULL,
    [RUT]                VARCHAR (9)  NOT NULL,
    [DIGITO_VERIFICADOR] VARCHAR (1)  NULL,
    [TIPO_PERSONA]       VARCHAR (7)  NOT NULL,
    [NOMBRES]            VARCHAR (50) NULL,
    [APELLIDO_PATERNO]   VARCHAR (50) NULL,
    [APELLIDO_MATERNO]   VARCHAR (50) NULL,
    [NOMBRE]             VARCHAR (80) NULL,
    [RAZON_SOCIAL]       VARCHAR (80) NULL,
    [NOMBRE_FANTASIA]    VARCHAR (80) NULL,
    [SEXO]               VARCHAR (9)  NULL,
    [SEGMENTO_DEUDOR]    VARCHAR (20) NULL,
    [CUENTA_CORRIENTE]   VARCHAR (1)  NULL,
    CONSTRAINT [PK_SITREL_DEUDOR] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_CARGA] ASC, [PCLID] ASC, [RUT] ASC, [TIPO_PERSONA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_RUT_SITREL_DEUDOR]
    ON [dbo].[SITREL_DEUDOR]([RUT] ASC);

