CREATE TABLE [dbo].[SITREL_ACCION] (
    [CODEMP] INT          NOT NULL,
    [PCLID]  INT          NOT NULL,
    [CODIGO] VARCHAR (20) NOT NULL,
    [NOMBRE] VARCHAR (50) NOT NULL,
    [ESTADO] VARCHAR (1)  NULL,
    [FECHA]  DATETIME     NULL,
    CONSTRAINT [PK_SITREL_ACCION] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [CODIGO] ASC)
);

