CREATE TABLE [dbo].[SITREL_TIPO_ARCHIVO] (
    [CODEMP]         INT           NOT NULL,
    [TIPO_ARCHIVO]   INT           NOT NULL,
    [NOMBRE]         VARCHAR (50)  NOT NULL,
    [FORMATO_NOMBRE] VARCHAR (100) NULL,
    [FECHA_INGRESO]  DATETIME      NOT NULL,
    [TIPO]           VARCHAR (1)   NULL,
    CONSTRAINT [PK_SITREL_TIPO_ARCHIVO] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [TIPO_ARCHIVO] ASC)
);

