CREATE TABLE [dbo].[SITREL_MONEDA] (
    [CODEMP] INT          NOT NULL,
    [PCLID]  INT          NOT NULL,
    [CODIGO] VARCHAR (20) NOT NULL,
    [NOMBRE] VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_SITREL_MONEDA] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [CODIGO] ASC)
);

