CREATE TABLE [dbo].[SITREL_RELACION] (
    [CODEMP]    INT          NOT NULL,
    [PCLID]     INT          NOT NULL,
    [ACCION]    VARCHAR (20) NOT NULL,
    [CONTACTO]  VARCHAR (20) NOT NULL,
    [RESPUESTA] VARCHAR (20) NOT NULL,
    [ESTADO]    VARCHAR (1)  NULL,
    [FECHA]     DATETIME     NULL,
    CONSTRAINT [PK_SITREL_RELACION] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC, [ACCION] ASC, [CONTACTO] ASC, [RESPUESTA] ASC),
    CONSTRAINT [FK_SITREL_RELACION_ACCION] FOREIGN KEY ([CODEMP], [PCLID], [ACCION]) REFERENCES [dbo].[SITREL_ACCION] ([CODEMP], [PCLID], [CODIGO]),
    CONSTRAINT [FK_SITREL_RELACION_CONTACTO] FOREIGN KEY ([CODEMP], [PCLID], [CONTACTO]) REFERENCES [dbo].[SITREL_CONTACTO] ([CODEMP], [PCLID], [CODIGO]),
    CONSTRAINT [FK_SITREL_RELACION_RESPUESTA] FOREIGN KEY ([CODEMP], [PCLID], [RESPUESTA]) REFERENCES [dbo].[SITREL_RESPUESTA] ([CODEMP], [PCLID], [CODIGO])
);

