CREATE TABLE [dbo].[SOCIOS_EJERCICIOS_REPETICION] (
    [SER_CODEMP]     INT             NOT NULL,
    [SER_SOCID]      INT             NOT NULL,
    [SER_EJCID]      INT             NOT NULL,
    [SER_REPID]      SMALLINT        NOT NULL,
    [SER_REPETICION] SMALLINT        NOT NULL,
    [SER_PESO]       NUMERIC (15, 2) NOT NULL,
    CONSTRAINT [PK_SOCIOS_EJERCICIOS_REPETICIO] PRIMARY KEY CLUSTERED ([SER_CODEMP] ASC, [SER_SOCID] ASC, [SER_EJCID] ASC, [SER_REPID] ASC),
    CONSTRAINT [FK_SOCIOS_E_SOCEJER_R_SOCIOS_E] FOREIGN KEY ([SER_CODEMP], [SER_SOCID], [SER_EJCID]) REFERENCES [dbo].[tmp_SOCIOS_EJERCICIOS] ([SOE_CODEMP], [SOE_SOCID], [SOE_EJCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[SOCIOS_EJERCICIOS_REPETICION]([SER_CODEMP] ASC, [SER_SOCID] ASC, [SER_EJCID] ASC, [SER_REPID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena las repeticiones x socios', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SOCIOS_EJERCICIOS_REPETICION';

