CREATE TABLE [dbo].[SUPCAT_CATEGORIAS] (
    [SCC_CODEMP] INT      NOT NULL,
    [SCC_SPCID]  INT      NOT NULL,
    [SCC_CATID]  INT      NOT NULL,
    [SCC_ORDEN]  SMALLINT NOT NULL,
    CONSTRAINT [PK_SUPCAT_CATEGORIAS] PRIMARY KEY NONCLUSTERED ([SCC_CODEMP] ASC, [SCC_SPCID] ASC, [SCC_CATID] ASC),
    CONSTRAINT [FK_SUPCAT_C_CATEGORIA_CATEGORI] FOREIGN KEY ([SCC_CODEMP], [SCC_CATID]) REFERENCES [dbo].[CATEGORIAS] ([CAT_CODEMP], [CAT_CATID]),
    CONSTRAINT [FK_SUPCAT_C_SUPCAT_SU_SUPERCAT] FOREIGN KEY ([SCC_CODEMP], [SCC_SPCID]) REFERENCES [dbo].[SUPERCATEGORIAS] ([SPC_CODEMP], [SPC_SPCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[SUPCAT_CATEGORIAS]([SCC_SPCID] ASC, [SCC_CODEMP] ASC, [SCC_CATID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Junta las super categorias y las categorias', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SUPCAT_CATEGORIAS';

