CREATE TABLE [dbo].[SUPERCATEGORIAS_IDIOMA] (
    [SCI_CODEMP] INT           NOT NULL,
    [SCI_SPCID]  INT           NOT NULL,
    [SCI_IDIID]  INT           NOT NULL,
    [SCI_NOMBRE] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_SUPERCATEGORIAS_IDIOMA] PRIMARY KEY NONCLUSTERED ([SCI_CODEMP] ASC, [SCI_SPCID] ASC, [SCI_IDIID] ASC),
    CONSTRAINT [FK_SUPERCAT_IDIOMAS_S_IDIOMAS] FOREIGN KEY ([SCI_IDIID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_SUPERCAT_SUPCAT_ID_SUPERCAT] FOREIGN KEY ([SCI_CODEMP], [SCI_SPCID]) REFERENCES [dbo].[SUPERCATEGORIAS] ([SPC_CODEMP], [SPC_SPCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[SUPERCATEGORIAS_IDIOMA]([SCI_CODEMP] ASC, [SCI_SPCID] ASC, [SCI_IDIID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena las distintas super categorias en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SUPERCATEGORIAS_IDIOMA';

