CREATE TABLE [dbo].[SYSTEM_EMAIL_TEMPLATES]
(
	[CODEMP] INT NOT NULL, 
    [PCLID] NUMERIC(15) NOT NULL, 
	[TEMPLATEID] INT NOT NULL, 
    [ALIAS] VARCHAR(50) NOT NULL, 
    [FILENAME] VARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_SYSTEM_EMAIL_TEMPLATES] PRIMARY KEY NONCLUSTERED ([CODEMP] ASC, [PCLID] ASC, [TEMPLATEID] ASC), 
    CONSTRAINT [FK_SYSTEM_EMAIL_TEMPLATES_PROVCLI] FOREIGN KEY ([CODEMP], [PCLID]) REFERENCES [PROVCLI]([PCL_CODEMP], [PCL_PCLID]),
)

GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_SYSTEM_EMAIL_TEMPLATES_ID] ON [dbo].[SYSTEM_EMAIL_TEMPLATES] ([TEMPLATEID])
