CREATE TABLE [dbo].[TESORERIA_CUENTAS_TIPO] (
    [TIPO_CUENTA_ID] INT          NOT NULL,
    [DESCRIPCION]    VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_TESORERIA_CUENTAS_TIPO] PRIMARY KEY CLUSTERED ([TIPO_CUENTA_ID] ASC)
);

