CREATE TABLE [dbo].[TESORERIA_TIPO_ESTADO_BANCO] (
    [TIPO_ESTADO_BANCO_ID] INT          NOT NULL,
    [DESCRIPCION]          VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_TESORERIA_TIPO_ESTADO_BANCO] PRIMARY KEY CLUSTERED ([TIPO_ESTADO_BANCO_ID] ASC)
);

