CREATE TABLE [dbo].[TESORERIA_CRITERIO_IMPUTACION_PORCENTAJE] (
    [CODEMP]         INT          NOT NULL,
    [PCLID]          NUMERIC (15) NOT NULL,
    [CAPITAL]        NUMERIC (3)  NOT NULL,
    [INTERES]        NUMERIC (3)  NOT NULL,
    [HONORARIO]      NUMERIC (3)  NOT NULL,
    [USRID_REGISTRO] INT          NOT NULL,
    [FEC_REGISTRO]   DATETIME     CONSTRAINT [DF_CRITERIO_IMPUTACION_PORCENTAJE_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_TESORERIA_CRITERIO_IMPUTACION_PORCENTAJE] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [PCLID] ASC)
);

