CREATE TABLE [dbo].[TESORERIA_CRITERIO_GANANCIA_PORCENTAJE] (
    [ID]                   INT          NOT NULL,
    [CODEMP]               INT          NOT NULL,
    [PCLID]                NUMERIC (15) NOT NULL,
    [DESDEDIASVENCIDO]     INT          NULL,
    [HASTADIASVENCIDO]     INT          NULL,
    [CODIGOREGION]         INT          NULL,
    [CODIGOCARGA]          INT          NULL,
    [CAPITAL]              NUMERIC (3)  NOT NULL,
    [INTERES]              NUMERIC (3)  NOT NULL,
    [HONORARIO]            NUMERIC (3)  NOT NULL,
    [USRID_REGISTRO]       INT          NOT NULL,
    [FEC_REGISTRO]         DATETIME     CONSTRAINT [DF_CRITERIO_GANANCIA_PORCENTAJE_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    [TIPOCAMBIOCAPITAL]    VARCHAR (2)  NULL,
    [CONCILIACION_TIPO_ID] INT          NULL,
    [CONDICION_ID]         INT          NULL,
    CONSTRAINT [PK_TESORERIA_CRITERIO_GANANCIA_PORCENTAJE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TESORERIA_CRITERIO_GANANCIA_PORCENTAJE_CAJA_CONDICION_FACTURACION] FOREIGN KEY ([CONDICION_ID]) REFERENCES [dbo].[CAJA_CONDICION_FACTURACION] ([CONDICION_ID]),
    CONSTRAINT [FK_TESORERIA_CRITERIO_GANANCIA_PORCENTAJE_CONCILIACION_TIPO] FOREIGN KEY ([CONCILIACION_TIPO_ID]) REFERENCES [dbo].[CONCILIACION_TIPO] ([CONCILIACION_TIPO_ID])
);

