CREATE TABLE [dbo].[TESORERIA_TIPO_MOTIVO_BANCO] (
    [TIPO_MOTIVO_BANCO_ID] INT          NOT NULL,
    [DESCRIPCION]          VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_TESORERIA_TIPO_MOTIVO_BANCO] PRIMARY KEY CLUSTERED ([TIPO_MOTIVO_BANCO_ID] ASC)
);

