CREATE TABLE [dbo].[TESORERIA_CUENTAS_BANCARIAS] (
    [CUENTA_ID]      INT          NOT NULL,
    [NUM_CUENTA]     VARCHAR (60) NOT NULL,
    [CODEMP]         INT          NOT NULL,
    [BANCO_ID]       INT          NOT NULL,
    [TIPO_CUENTA_ID] INT          NOT NULL,
    [USRID_REGISTRO] INT          NOT NULL,
    [FEC_REGISTRO]   DATETIME     CONSTRAINT [DF_TESORERIA_CUENTAS_BANCARIAS_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_TESORERIA_CUENTAS_BANCARIAS] PRIMARY KEY CLUSTERED ([CUENTA_ID] ASC),
    CONSTRAINT [FK_TESORERIA_CUENTAS_BANCARIAS_TESORERIA_CUENTAS_TIPO] FOREIGN KEY ([TIPO_CUENTA_ID]) REFERENCES [dbo].[TESORERIA_CUENTAS_TIPO] ([TIPO_CUENTA_ID])
);

