CREATE TABLE [dbo].[TESORERIA_TIPO_MOVIMIENTO_BANCO] (
    [TIPO_MOVIMIENTO_BANCO_ID] INT          NOT NULL,
    [DESCRIPCION]              VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_TESORERIA_TIPO_MOVIMIENTO_BANCO] PRIMARY KEY CLUSTERED ([TIPO_MOVIMIENTO_BANCO_ID] ASC)
);

