CREATE TABLE [dbo].[TIPOS_VEHICULOS] (
    [TVC_CODEMP] INT          NOT NULL,
    [TVC_TVCID]  INT          NOT NULL,
    [TVC_NOMBRE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TIPOS_VEHICULOS] PRIMARY KEY CLUSTERED ([TVC_CODEMP] ASC, [TVC_TVCID] ASC),
    CONSTRAINT [FK_TIPOS_VE_TIPVCH_EM_EMPRESA] FOREIGN KEY ([TVC_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_VEHICULOS]([TVC_CODEMP] ASC, [TVC_TVCID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOM]
    ON [dbo].[TIPOS_VEHICULOS]([TVC_CODEMP] ASC, [TVC_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de vehiculos', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_VEHICULOS';

