CREATE TABLE [dbo].[TIPOS_CAUSA_IDIOMAS] (
    [TCI_CODEMP] INT           NOT NULL,
    [TCI_TCAID]  INT           NOT NULL,
    [TCI_IDID]   INT           NOT NULL,
    [TCI_NOMBRE] VARCHAR (800) NOT NULL,
    CONSTRAINT [PK_TIPOS_CAUSA_IDIOMAS] PRIMARY KEY CLUSTERED ([TCI_CODEMP] ASC, [TCI_TCAID] ASC, [TCI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_CA_IDI_TIPCA_IDIOMAS] FOREIGN KEY ([TCI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_CA_TIPCAU_ID_TIPOS_CA] FOREIGN KEY ([TCI_CODEMP], [TCI_TCAID]) REFERENCES [dbo].[TIPOS_CAUSA] ([TCA_CODEMP], [TCA_TCAID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_CAUSA_IDIOMAS]([TCI_CODEMP] ASC, [TCI_TCAID] ASC, [TCI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos idiomas para los tipos de causa', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_CAUSA_IDIOMAS';

