CREATE TABLE [dbo].[TIPOS_INFORMES_IDIOMAS] (
    [TFI_CODEMP] INT           NOT NULL,
    [TFI_TIFID]  INT           NOT NULL,
    [TFI_IDID]   INT           NOT NULL,
    [TFI_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPOS_INFORMES_IDIOMAS] PRIMARY KEY CLUSTERED ([TFI_CODEMP] ASC, [TFI_TIFID] ASC, [TFI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_IN_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TFI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_IN_TIPINF_ID_TIPOS_IN] FOREIGN KEY ([TFI_CODEMP], [TFI_TIFID]) REFERENCES [dbo].[TIPOS_INFORMES] ([TIF_CODEMP], [TIF_TIFID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_INFORMES_IDIOMAS]([TFI_CODEMP] ASC, [TFI_TIFID] ASC, [TFI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de informes en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_INFORMES_IDIOMAS';

