CREATE TABLE [dbo].[TIPOS_PROPIEDADES_IDIOMAS] (
    [TPI_CODEMP] INT           NOT NULL,
    [TPI_TPPID]  INT           NOT NULL,
    [TPI_IDID]   INT           NOT NULL,
    [TPI_NOMBRE] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_TIPOS_PROPIEDADES_IDIOMAS] PRIMARY KEY CLUSTERED ([TPI_CODEMP] ASC, [TPI_TPPID] ASC, [TPI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_PR_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TPI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_PR_TIPPROP_I_TIPOS_PR] FOREIGN KEY ([TPI_CODEMP], [TPI_TPPID]) REFERENCES [dbo].[TIPOS_PROPIEDADES] ([TPP_CODEMP], [TPP_TPPID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_PROPIEDADES_IDIOMAS]([TPI_CODEMP] ASC, [TPI_TPPID] ASC, [TPI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos idiomas, para cada tipo de propiedad', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_PROPIEDADES_IDIOMAS';

