CREATE TABLE [dbo].[TIPOS_CAUSA_GUIAS_IDIOMAS] (
    [TGI_CODEMP] INT           NOT NULL,
    [TGI_TGDID]  INT           NOT NULL,
    [TGI_IDID]   INT           NOT NULL,
    [TGI_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPOS_CAUSA_GUIAS_IDIOMAS] PRIMARY KEY CLUSTERED ([TGI_CODEMP] ASC, [TGI_TGDID] ASC, [TGI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_CA_IDIOMA_TI_IDIOMAS] FOREIGN KEY ([TGI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_CA_TIPGD_IDI_TIPOS_CA] FOREIGN KEY ([TGI_CODEMP], [TGI_TGDID]) REFERENCES [dbo].[TIPOS_CAUSA_GUIAS] ([TGD_CODEMP], [TGD_TGDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_CAUSA_GUIAS_IDIOMAS]([TGI_CODEMP] ASC, [TGI_TGDID] ASC, [TGI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena las distintas causas de la guia', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_CAUSA_GUIAS_IDIOMAS';

