CREATE TABLE [dbo].[TIPOS_TRANSPORTE_IDIOMAS] (
    [TTI_CODEMP] INT           NOT NULL,
    [TTI_TPTID]  INT           NOT NULL,
    [TTI_IDID]   INT           NOT NULL,
    [TTI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPOS_TRANSPORTE_IDIOMAS] PRIMARY KEY CLUSTERED ([TTI_CODEMP] ASC, [TTI_TPTID] ASC, [TTI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_TR_IDIOMA_TI_IDIOMAS] FOREIGN KEY ([TTI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_TR_TIPTRANS__TIPOS_TR] FOREIGN KEY ([TTI_CODEMP], [TTI_TPTID]) REFERENCES [dbo].[TIPOS_TRANSPORTE] ([TPT_CODEMP], [TPT_TPTID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_TRANSPORTE_IDIOMAS]([TTI_CODEMP] ASC, [TTI_TPTID] ASC, [TTI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos tipos de idiomas para cada transporte', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_TRANSPORTE_IDIOMAS';

