CREATE TABLE [dbo].[TIPOS_CAUSA_NCND] (
    [TNT_CODEMP] INT          NOT NULL,
    [TNT_TNTID]  INT          NOT NULL,
    [TNT_NOMBRE] VARCHAR (80) NOT NULL,
    [TNT_CODIGO] VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_TIPOS_CAUSA_NCND] PRIMARY KEY CLUSTERED ([TNT_CODEMP] ASC, [TNT_TNTID] ASC),
    CONSTRAINT [FK_TIPOS_CA_TIPNCND_E_EMPRESA] FOREIGN KEY ([TNT_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_CAUSA_NCND]([TNT_CODEMP] ASC, [TNT_TNTID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_COD]
    ON [dbo].[TIPOS_CAUSA_NCND]([TNT_CODEMP] ASC, [TNT_CODIGO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOM]
    ON [dbo].[TIPOS_CAUSA_NCND]([TNT_CODEMP] ASC, [TNT_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos casos para las notas de Credito y Debito', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_CAUSA_NCND';

