CREATE TABLE [dbo].[TIPOS_MOTIVOS_CASTIGOS] (
    [TMC_CODEMP] INT           NOT NULL,
    [TMC_TMCID]  INT           NOT NULL,
    [TMC_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPOS_MOTIVOS_CASTIGOS] PRIMARY KEY CLUSTERED ([TMC_CODEMP] ASC, [TMC_TMCID] ASC),
    CONSTRAINT [FK_TIPOS_MO_EMPREA_TI_EMPRESA] FOREIGN KEY ([TMC_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_MOTIVOS_CASTIGOS]([TMC_CODEMP] ASC, [TMC_TMCID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[TIPOS_MOTIVOS_CASTIGOS]([TMC_CODEMP] ASC, [TMC_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos tipos de castigos, que seran seleccionados para realizarlos', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_MOTIVOS_CASTIGOS';

