CREATE TABLE [dbo].[TIPOS_CPBTDOC_TALONARIO] (
    [TCT_CODEMP] INT NOT NULL,
    [TCT_TACID]  INT NOT NULL,
    [TCT_TPCID]  INT NOT NULL,
    [TCT_SUCID]  INT NOT NULL,
    CONSTRAINT [PK_TIPOS_CPBTDOC_TALONARIO] PRIMARY KEY NONCLUSTERED ([TCT_CODEMP] ASC, [TCT_TACID] ASC, [TCT_TPCID] ASC, [TCT_SUCID] ASC),
    CONSTRAINT [FK_TIPOS_CP_TAL_CPBTD_TALONARI] FOREIGN KEY ([TCT_CODEMP], [TCT_TACID]) REFERENCES [dbo].[TALONARIO_CPBTDOC] ([TAC_CODEMP], [TAC_TACID]),
    CONSTRAINT [FK_TIPOS_CP_TIPCPBT_T_TIPOS_CP] FOREIGN KEY ([TCT_CODEMP], [TCT_TPCID]) REFERENCES [dbo].[TIPOS_CPBTDOC] ([TPC_CODEMP], [TPC_TPCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_CPBTDOC_TALONARIO]([TCT_CODEMP] ASC, [TCT_SUCID] ASC, [TCT_TACID] ASC, [TCT_TPCID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Indica, el talonario del comprobante dependiendo de la sucursal', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_CPBTDOC_TALONARIO';

