CREATE TABLE [dbo].[TIPOS_TRASLADO_IDIOMAS] (
    [TLI_CODEMP] INT           NOT NULL,
    [TLI_TTLID]  INT           NOT NULL,
    [TLI_IDID]   INT           NOT NULL,
    [TLI_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPOS_TRASLADO_IDIOMAS] PRIMARY KEY CLUSTERED ([TLI_CODEMP] ASC, [TLI_TTLID] ASC, [TLI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_TR_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TLI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_TR_TIPTRASL__TIPOS_TR] FOREIGN KEY ([TLI_CODEMP], [TLI_TTLID]) REFERENCES [dbo].[TIPOS_TRASLADO] ([TTL_CODEMP], [TTL_TTLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_TRASLADO_IDIOMAS]([TLI_CODEMP] ASC, [TLI_TTLID] ASC, [TLI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de traslado en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_TRASLADO_IDIOMAS';

