CREATE TABLE [dbo].[TIPOS_EJERCICIOS_IDIOMAS] (
    [TJI_CODEMP] INT           NOT NULL,
    [TJI_TEJID]  INT           NOT NULL,
    [TJI_IDID]   INT           NOT NULL,
    [TJI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPOS_EJERCICIOS_IDIOMAS] PRIMARY KEY CLUSTERED ([TJI_CODEMP] ASC, [TJI_TEJID] ASC, [TJI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_EJ_IDIOMA_TI_IDIOMAS] FOREIGN KEY ([TJI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_EJ_TIPEJER_I_TIPOS_EJ] FOREIGN KEY ([TJI_CODEMP], [TJI_TEJID]) REFERENCES [dbo].[TIPOS_EJERCICIOS] ([TEJ_CODEMP], [TEJ_TEJID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_EJERCICIOS_IDIOMAS]([TJI_CODEMP] ASC, [TJI_TEJID] ASC, [TJI_IDID] ASC);

