CREATE TABLE [dbo].[TIPOS_DOCUMENTOS_ENVIOS_IDIOMAS] (
    [TEI_CODEMP] INT           NOT NULL,
    [TEI_TDEID]  INT           NOT NULL,
    [TEI_IDID]   INT           NOT NULL,
    [TEI_NOMBRE] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TIPOS_DOCUMENTOS_ENVIOS_IDI] PRIMARY KEY CLUSTERED ([TEI_CODEMP] ASC, [TEI_TDEID] ASC, [TEI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_DO_IDI_TIPDE_IDIOMAS] FOREIGN KEY ([TEI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_DO_TIPDOCENV_TIPOS_DO] FOREIGN KEY ([TEI_CODEMP], [TEI_TDEID]) REFERENCES [dbo].[TIPOS_DOCUMENTOS_ENVIOS] ([TDE_CODEMP], [TDE_TDEID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_DOCUMENTOS_ENVIOS_IDIOMAS]([TEI_CODEMP] ASC, [TEI_TDEID] ASC, [TEI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos idiomas, para los tipos de envios', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_DOCUMENTOS_ENVIOS_IDIOMAS';

