CREATE TABLE [dbo].[TIPOS_IMAGENES_CPBTDOC_IDIOMAS] (
    [TPI_CODEMP] INT           NOT NULL,
    [TPI_TPCID]  INT           NOT NULL,
    [TPI_IDID]   INT           NOT NULL,
    [TPI_NOMBRE] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_TIPOS_IMAGENES_CPBTDOC_IDIO] PRIMARY KEY CLUSTERED ([TPI_CODEMP] ASC, [TPI_TPCID] ASC, [TPI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_IM_REFERENCE_IDIOMAS] FOREIGN KEY ([TPI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_IM_REFERENCE_TIPOS_IM] FOREIGN KEY ([TPI_CODEMP], [TPI_TPCID]) REFERENCES [dbo].[TIPOS_IMAGENES_CPBTDOC] ([TPC_CODEMP], [TPC_TPCID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_IMAGENES_CPBTDOC_IDIOMAS]([TPI_CODEMP] ASC, [TPI_TPCID] ASC, [TPI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Almacena el distinto idioma, para cada tipo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_IMAGENES_CPBTDOC_IDIOMAS';

