CREATE TABLE [dbo].[TIPOS_INSUMO_IDIOMAS] (
    [TII_CODEMP] INT           NOT NULL,
    [TII_TIPID]  INT           NOT NULL,
    [TII_IDID]   INT           NOT NULL,
    [TII_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPOS_INSUMO_IDIOMAS] PRIMARY KEY CLUSTERED ([TII_CODEMP] ASC, [TII_TIPID] ASC, [TII_IDID] ASC),
    CONSTRAINT [FK_TIPOS_IN_IDIO_TIPI_IDIOMAS] FOREIGN KEY ([TII_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_IN_TIPINS_ID_TIPOS_IN] FOREIGN KEY ([TII_CODEMP], [TII_TIPID]) REFERENCES [dbo].[TIPOS_INSUMO] ([TPI_CODEMP], [TPI_TIPID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_INSUMO_IDIOMAS]([TII_CODEMP] ASC, [TII_TIPID] ASC, [TII_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_INSUMO_IDIOMAS';

