CREATE TABLE [dbo].[TIPOS_MOTIVOS_CASTIGOS_IDIOMAS] (
    [TMI_CODEMP] INT           NOT NULL,
    [TMI_TMCID]  INT           NOT NULL,
    [TMI_IDID]   INT           NOT NULL,
    [TMI_NOMBRE] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_TIPOS_MOTIVOS_CASTIGOS_IDIO] PRIMARY KEY CLUSTERED ([TMI_CODEMP] ASC, [TMI_TMCID] ASC, [TMI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_MO_IDIOMA_TI_IDIOMAS] FOREIGN KEY ([TMI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_MO_REFERENCE_TIPOS_MO] FOREIGN KEY ([TMI_CODEMP], [TMI_TMCID]) REFERENCES [dbo].[TIPOS_MOTIVOS_CASTIGOS] ([TMC_CODEMP], [TMC_TMCID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_MOTIVOS_CASTIGOS_IDIOMAS]([TMI_CODEMP] ASC, [TMI_TMCID] ASC, [TMI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintod idiomas para cada tipo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_MOTIVOS_CASTIGOS_IDIOMAS';

