CREATE TABLE [dbo].[TIPOS_CAUSA_GUIAS] (
    [TGD_CODEMP] INT          NOT NULL,
    [TGD_TGDID]  INT          NOT NULL,
    [TGD_NOMBRE] VARCHAR (80) NOT NULL,
    [TGD_CODIGO] VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_TIPOS_CAUSA_GUIAS] PRIMARY KEY CLUSTERED ([TGD_CODEMP] ASC, [TGD_TGDID] ASC),
    CONSTRAINT [FK_TIPOS_CA_TIPGD_EMP_EMPRESA] FOREIGN KEY ([TGD_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_CAUSA_GUIAS]([TGD_CODEMP] ASC, [TGD_TGDID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_COD]
    ON [dbo].[TIPOS_CAUSA_GUIAS]([TGD_CODEMP] ASC, [TGD_CODIGO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOM]
    ON [dbo].[TIPOS_CAUSA_GUIAS]([TGD_CODEMP] ASC, [TGD_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos casos para las notas de Credito y Debito', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_CAUSA_GUIAS';

