CREATE TABLE [dbo].[TIPOS_RETIRO_ENTREGA_IDIOMAS] (
    [TRI_CODEMP] INT           NOT NULL,
    [TRI_TREID]  INT           NOT NULL,
    [TRI_IDID]   INT           NOT NULL,
    [TRI_NOMBRE] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPOS_RETIRO_ENTREGA_IDIOMA] PRIMARY KEY NONCLUSTERED ([TRI_CODEMP] ASC, [TRI_TREID] ASC, [TRI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_RE_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TRI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_RE_TIPRET_ID_TIPOS_RE] FOREIGN KEY ([TRI_CODEMP], [TRI_TREID]) REFERENCES [dbo].[TIPOS_RETIRO_ENTREGA] ([TRE_CODEMP], [TRE_TREID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_RETIRO_ENTREGA_IDIOMAS]([TRI_CODEMP] ASC, [TRI_TREID] ASC, [TRI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena los distintos tipos de retiros en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_RETIRO_ENTREGA_IDIOMAS';

