CREATE TABLE [dbo].[TIPOS_DESCRIPCION_PRODUCTO_IDIOMA] (
    [TPI_CODEMP] INT          NOT NULL,
    [TPI_TPDID]  INT          NOT NULL,
    [TPI_IDIID]  INT          NOT NULL,
    [TPI_NOMBRE] VARCHAR (80) NOT NULL,
    CONSTRAINT [PK_TIPO_DESCRIPCION_PRODUCTO_I] PRIMARY KEY NONCLUSTERED ([TPI_CODEMP] ASC, [TPI_TPDID] ASC, [TPI_IDIID] ASC),
    CONSTRAINT [FK_TIPO_DES_TIPDESCPR_TIPO_DES] FOREIGN KEY ([TPI_CODEMP], [TPI_TPDID]) REFERENCES [dbo].[TIPOS_DESCRIPCION_PRODUCTO] ([TDP_CODEMP], [TDP_TPDID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_DESCRIPCION_PRODUCTO_IDIOMA]([TPI_CODEMP] ASC, [TPI_TPDID] ASC, [TPI_IDIID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla, almacena las distintas especificaciones del producto en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_DESCRIPCION_PRODUCTO_IDIOMA';

