CREATE TABLE [dbo].[TIPOS_ASISTENCIA_IDIOMAS] (
    [TAI_CODEMP] INT          NOT NULL,
    [TAI_TIPOID] INT          NOT NULL,
    [TAI_IDID]   INT          NOT NULL,
    [TAI_NOMBRE] VARCHAR (80) NOT NULL,
    CONSTRAINT [PK_TIPOS_ASISTENCIA_IDIOMAS] PRIMARY KEY CLUSTERED ([TAI_CODEMP] ASC, [TAI_TIPOID] ASC, [TAI_IDID] ASC),
    CONSTRAINT [FK_TIPOS_AS_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TAI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TIPOS_AS_TIPASIS_I_TIPOS_AS] FOREIGN KEY ([TAI_CODEMP], [TAI_TIPOID]) REFERENCES [dbo].[TIPOS_ASISTENCIA] ([TIA_CODEMP], [TIA_TIPOID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_ASISTENCIA_IDIOMAS]([TAI_CODEMP] ASC, [TAI_TIPOID] ASC, [TAI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos idiomas para cada tipo', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_ASISTENCIA_IDIOMAS';

