CREATE TABLE [dbo].[TIPOS_TRASLADO] (
    [TTL_CODEMP] INT          NOT NULL,
    [TTL_TTLID]  INT          NOT NULL,
    [TTL_NOMBRE] VARCHAR (80) NOT NULL,
    [TTL_CODIGO] VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_TIPOS_TRASLADO] PRIMARY KEY CLUSTERED ([TTL_CODEMP] ASC, [TTL_TTLID] ASC),
    CONSTRAINT [FK_TIPOS_TR_EMPRESA_T_EMPRESA] FOREIGN KEY ([TTL_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TIPOS_TRASLADO]([TTL_CODEMP] ASC, [TTL_TTLID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_COD]
    ON [dbo].[TIPOS_TRASLADO]([TTL_CODEMP] ASC, [TTL_CODIGO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOM]
    ON [dbo].[TIPOS_TRASLADO]([TTL_CODEMP] ASC, [TTL_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de traslados, que utilizara la guia de despacho', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TIPOS_TRASLADO';

