CREATE TABLE [dbo].[TREEVIEW] (
    [TRV_TRVID]          INT            NOT NULL,
    [TRV_PADID]          INT            NULL,
    [TRV_NOMBRE]         VARCHAR (800)  NOT NULL,
    [TRV_IMAGEN]         VARCHAR (100)  NOT NULL,
    [TRV_VENTANA]        VARCHAR (1000) NOT NULL,
    [TRV_ORDEN]          SMALLINT       DEFAULT ((5)) NOT NULL,
    [TRV_MENID]          INT            NOT NULL,
    [TRV_DIMOL_VENTANA]  VARCHAR (1000) NULL,
    [TRV_DIMOL_AMBIENTE] VARCHAR (1000) NULL,
    [TRV_DIMOL_VIGENTE]  VARCHAR (1)    NULL,
    CONSTRAINT [PK_TREEVIEW] PRIMARY KEY CLUSTERED ([TRV_TRVID] ASC),
    CONSTRAINT [FK_TREEVIEW_MENU_TREE_MENU] FOREIGN KEY ([TRV_MENID]) REFERENCES [dbo].[MENU] ([MEN_MENID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TREEVIEW]([TRV_TRVID] ASC);

