CREATE TABLE [dbo].[TREEVIEW_IDIOMAS] (
    [TVI_TRVID]   INT           NOT NULL,
    [TVI_IDID]    INT           NOT NULL,
    [TVI_IDIOMAS] VARCHAR (900) NOT NULL,
    CONSTRAINT [PK_TREEVIEW_IDIOMAS] PRIMARY KEY CLUSTERED ([TVI_TRVID] ASC, [TVI_IDID] ASC),
    CONSTRAINT [FK_TREEVIEW_IDIOMAS_T_IDIOMAS] FOREIGN KEY ([TVI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_TREEVIEW_TREEVIEW__TREEVIEW] FOREIGN KEY ([TVI_TRVID]) REFERENCES [dbo].[TREEVIEW] ([TRV_TRVID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TREEVIEW_IDIOMAS]([TVI_TRVID] ASC, [TVI_IDID] ASC);

