CREATE TABLE [dbo].[TRIBUNALES_A_PODER_JUDICIAL] (
    [CODEMP]      INT NOT NULL,
    [ID_TRIBUNAL] INT NOT NULL,
    [TRBID]       INT NOT NULL,
    CONSTRAINT [PK_TRIBUNALES_A_PODER_JUDICIAL] PRIMARY KEY CLUSTERED ([CODEMP] ASC, [ID_TRIBUNAL] ASC, [TRBID] ASC)
);

