CREATE TABLE [dbo].[TRIBUNALES] (
    [TRB_CODEMP]     INT           NOT NULL,
    [TRB_TRBID]      INT           NOT NULL,
    [TRB_RUT]        VARCHAR (20)  NOT NULL,
    [TRB_NOMBRE]     VARCHAR (800) NOT NULL,
    [TRB_TTBID]      INT           NOT NULL,
    [TRB_COMID]      INT           NULL,
    [TRB_DIRECCION]  VARCHAR (120) NOT NULL,
    [TRB_TELEFONO1]  VARCHAR (80)  NULL,
    [TRB_TELEFONO2]  VARCHAR (80)  NULL,
    [TRB_FAX]        VARCHAR (80)  NULL,
    [TRB_EMAIL]      VARCHAR (100) NULL,
    [TRB_BCOID]      INT           NULL,
    [TRB_CTACTE]     VARCHAR (20)  NULL,
    [ID_CORTE]       INT           NULL,
    [ID_COMPETENCIA] INT           NULL,
    CONSTRAINT [PK_TRIBUNALES] PRIMARY KEY CLUSTERED ([TRB_CODEMP] ASC, [TRB_TRBID] ASC),
    CONSTRAINT [FK_TRIBUNAL_BANCOS_TR_BANCOS] FOREIGN KEY ([TRB_CODEMP], [TRB_BCOID]) REFERENCES [dbo].[BANCOS] ([BCO_CODEMP], [BCO_BCOID]),
    CONSTRAINT [FK_TRIBUNAL_COMUNA_TR_COMUNA] FOREIGN KEY ([TRB_COMID]) REFERENCES [dbo].[COMUNA] ([COM_COMID]),
    CONSTRAINT [FK_TRIBUNAL_EMPRESA_T_EMPRESA] FOREIGN KEY ([TRB_CODEMP]) REFERENCES [dbo].[EMPRESA] ([EMP_CODEMP]),
    CONSTRAINT [FK_TRIBUNAL_TIPTRIB_T_TIPOS_TR] FOREIGN KEY ([TRB_CODEMP], [TRB_TTBID]) REFERENCES [dbo].[TIPOS_TRIBUNAL] ([TTB_CODEMP], [TTB_TTBID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[TRIBUNALES]([TRB_CODEMP] ASC, [TRB_TRBID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_RUT]
    ON [dbo].[TRIBUNALES]([TRB_RUT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_NOMBRE]
    ON [dbo].[TRIBUNALES]([TRB_CODEMP] ASC, [TRB_NOMBRE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tribunales de justicia
   ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TRIBUNALES';

