CREATE TABLE [dbo].[UNIDADES_MEDIDA_IDIOMAS] (
    [UMI_UNMID]  INT          NOT NULL,
    [UMI_IDIID]  INT          NOT NULL,
    [UMI_NOMBRE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_UNIDADES_MEDIDA_IDIOMAS] PRIMARY KEY NONCLUSTERED ([UMI_UNMID] ASC, [UMI_IDIID] ASC),
    CONSTRAINT [FK_UNIDADES_IDIOMAS_U_IDIOMAS] FOREIGN KEY ([UMI_IDIID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_UNIDADES_UNIMED_ID_UNIDADES] FOREIGN KEY ([UMI_UNMID]) REFERENCES [dbo].[UNIDADES_MEDIDA] ([UNM_UNMID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[UNIDADES_MEDIDA_IDIOMAS]([UMI_IDIID] ASC, [UMI_UNMID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos tipos de medida en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'UNIDADES_MEDIDA_IDIOMAS';

