CREATE TABLE [dbo].[USUARIOS_PROVCLI] (
    [USP_CODEMP] INT          NOT NULL,
    [USP_USRID]  INT          NOT NULL,
    [USP_PCLID]  NUMERIC (15) NOT NULL,
    CONSTRAINT [PK_USUARIOS_PROVCLI] PRIMARY KEY CLUSTERED ([USP_CODEMP] ASC, [USP_USRID] ASC, [USP_PCLID] ASC),
    CONSTRAINT [FK_USUARIOS_PROVCLI_U_PROVCLI] FOREIGN KEY ([USP_CODEMP], [USP_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_USUARIOS_USUAR_CLI_USUARIOS] FOREIGN KEY ([USP_CODEMP], [USP_USRID]) REFERENCES [dbo].[USUARIOS] ([USR_CODEMP], [USR_USRID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[USUARIOS_PROVCLI]([USP_CODEMP] ASC, [USP_USRID] ASC, [USP_PCLID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos clientes, que podra acceder dicho usuario', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'USUARIOS_PROVCLI';

