CREATE TABLE [dbo].[USUARIOS_PROVCLI_CODCARG] (
    [UPC_CODEMP] INT          NOT NULL,
    [UPC_USRID]  INT          NOT NULL,
    [UPC_PCLID]  NUMERIC (15) NOT NULL,
    [UPC_CODID]  INT          NOT NULL,
    CONSTRAINT [PK_USUARIOS_PROVCLI_CODCARG] PRIMARY KEY CLUSTERED ([UPC_CODEMP] ASC, [UPC_USRID] ASC, [UPC_PCLID] ASC, [UPC_CODID] ASC),
    CONSTRAINT [FK_USUARIOS_PROVCC_US_PROVCLI_] FOREIGN KEY ([UPC_CODEMP], [UPC_PCLID], [UPC_CODID]) REFERENCES [dbo].[PROVCLI_CODIGO_CARGA] ([PCC_CODEMP], [PCC_PCLID], [PCC_CODID]),
    CONSTRAINT [FK_USUARIOS_USU_PROCL_USUARIOS] FOREIGN KEY ([UPC_CODEMP], [UPC_USRID], [UPC_PCLID]) REFERENCES [dbo].[USUARIOS_PROVCLI] ([USP_CODEMP], [USP_USRID], [USP_PCLID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[USUARIOS_PROVCLI_CODCARG]([UPC_CODEMP] ASC, [UPC_USRID] ASC, [UPC_PCLID] ASC, [UPC_CODID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla indica, que codigo de carga en especial puede ver cada usuario', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'USUARIOS_PROVCLI_CODCARG';

