CREATE TABLE [dbo].[UTILITARIOS_IDIOMAS] (
    [UTI_CODEMP] INT           NOT NULL,
    [UTI_UTLID]  INT           NOT NULL,
    [UTI_IDID]   INT           NOT NULL,
    [UTI_NOMBRE] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_UTILITARIOS_IDIOMAS] PRIMARY KEY CLUSTERED ([UTI_CODEMP] ASC, [UTI_UTLID] ASC, [UTI_IDID] ASC),
    CONSTRAINT [FK_UTILITAR_IDIOMAS_U_IDIOMAS] FOREIGN KEY ([UTI_IDID]) REFERENCES [dbo].[IDIOMAS] ([IDI_IDID]),
    CONSTRAINT [FK_UTILITAR_UTI_IDIOM_UTILITAR] FOREIGN KEY ([UTI_CODEMP], [UTI_UTLID]) REFERENCES [dbo].[UTILITARIOS] ([UTL_CODEMP], [UTL_UTLID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[UTILITARIOS_IDIOMAS]([UTI_CODEMP] ASC, [UTI_UTLID] ASC, [UTI_IDID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena los distintos utilitarios en su respectivo idioma', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'UTILITARIOS_IDIOMAS';

