CREATE TABLE [dbo].[VENDEDORES_CARTERA] (
    [VDC_CODEMP]  INT          NOT NULL,
    [VDC_SUCID]   INT          NOT NULL,
    [VDC_VDEID]   INT          NOT NULL,
    [VDC_PCLID]   NUMERIC (15) NOT NULL,
    [VDC_FECASIG] DATETIME     NULL,
    CONSTRAINT [PK_VENDEDORES_CARTERA] PRIMARY KEY CLUSTERED ([VDC_CODEMP] ASC, [VDC_SUCID] ASC, [VDC_VDEID] ASC, [VDC_PCLID] ASC),
    CONSTRAINT [FK_VENDEDOR_PROVCLI_C_PROVCLI] FOREIGN KEY ([VDC_CODEMP], [VDC_PCLID]) REFERENCES [dbo].[PROVCLI] ([PCL_CODEMP], [PCL_PCLID]),
    CONSTRAINT [FK_VENDEDOR_VEND_CLIE_VENDEDOR] FOREIGN KEY ([VDC_CODEMP], [VDC_SUCID], [VDC_VDEID]) REFERENCES [dbo].[VENDEDORES] ([VDE_CODEMP], [VDE_SUCID], [VDE_VDEID])
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PRI1]
    ON [dbo].[VENDEDORES_CARTERA]([VDC_CODEMP] ASC, [VDC_SUCID] ASC, [VDC_VDEID] ASC, [VDC_PCLID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Esta tabla almacena la cartera asignada a cada vendedor', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VENDEDORES_CARTERA';

