CREATE TABLE [dbo].[VISITA_TERRENO_CARGA] (
    [IDCARGA]        INT           NOT NULL,
    [ARCHIVO]        VARCHAR (100) NOT NULL,
    [USRID_DESCARGA] INT           NOT NULL,
    [FEC_DESCARGA]   DATETIME      CONSTRAINT [DF_VISITA_TERRENO_CARGA_FEC_DESCARGA] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_CARGA] PRIMARY KEY CLUSTERED ([IDCARGA] ASC)
);

