CREATE TABLE [dbo].[VISITA_TERRENO_TIPO_ESTATUS_ESTADO] (
    [ID_ESTATUS] INT          NOT NULL,
    [ESTATUS]    VARCHAR (15) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_TIPO_ESTATUS_ESTADO] PRIMARY KEY CLUSTERED ([ID_ESTATUS] ASC)
);

