CREATE TABLE [dbo].[VISITA_TERRENO_FORMULARIO_SOLICITUD] (
    [FORMULARIOID] INT NOT NULL,
    [SOLICITUD_ID] INT NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_FORMULARIO_SOLICITUD] PRIMARY KEY CLUSTERED ([FORMULARIOID] ASC, [SOLICITUD_ID] ASC)
);

