CREATE TABLE [dbo].[VISITA_TERRENO_DETALLE_FOTOS] (
    [ID_VISITA_DETALLE] INT            NOT NULL,
    [ID_VISITA]         INT            NOT NULL,
    [ID_FOTO]           INT            NOT NULL,
    [RUTA_IMAGEN]       VARCHAR (1000) NOT NULL,
    [PATH_IMAGEN]       VARCHAR (1000) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_DETALLE_FOTOS] PRIMARY KEY CLUSTERED ([ID_VISITA_DETALLE] ASC, [ID_VISITA] ASC, [ID_FOTO] ASC),
    CONSTRAINT [FK_VISITA_TERRENO_DETALLE_VTDFOTOS] FOREIGN KEY ([ID_VISITA_DETALLE], [ID_VISITA]) REFERENCES [dbo].[VISITA_TERRENO_DETALLE] ([ID_VISITA_DETALLE], [ID_VISITA])
);

