CREATE TABLE [dbo].[VISITA_TERRENO_CARTERA_GESTOR] (
    [CARTERA_ID]     VARCHAR (100) NOT NULL,
    [GESID]          INT           NOT NULL,
    [CARTERA_NOMBRE] VARCHAR (100) NOT NULL,
    [DESCRIPCION]    VARCHAR (100) NULL,
    [USRID_REGISTRO] INT           NOT NULL,
    [FEC_REGISTRO]   DATETIME      CONSTRAINT [DF_FEC_REGISTRO_VISITA_TERRENO_CARTERA_GESTOR] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_CARTERA_GESTOR] PRIMARY KEY CLUSTERED ([CARTERA_ID] ASC)
);

