CREATE TABLE [dbo].[VISITA_TERRENO_FORMULARIO_FORMID] (
    [FORMID]       VARCHAR (500) NOT NULL,
    [FEC_REGISTRO] DATETIME      CONSTRAINT [DF_FEC_REGISTRO_VISITA_TERRENO_FORMULARIO_FORMID] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_FORMULARIO_FORMID] PRIMARY KEY CLUSTERED ([FORMID] ASC)
);

