CREATE TABLE [dbo].[VISITA_TERRENO_DETALLE_GPS] (
    [ID_VISITA_DETALLE] INT             NOT NULL,
    [ID_VISITA]         INT             NOT NULL,
    [LATITUD]           NUMERIC (12, 6) NOT NULL,
    [LONGITUD]          NUMERIC (12, 6) NOT NULL,
    [ALTITUD]           INT             NOT NULL,
    [DIRECCION]         VARCHAR (50)    NOT NULL,
    [COMUNA]            VARCHAR (50)    NOT NULL,
    [CIUDAD]            VARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_DETALLE_GPS] PRIMARY KEY CLUSTERED ([ID_VISITA_DETALLE] ASC, [ID_VISITA] ASC, [LATITUD] ASC, [LONGITUD] ASC, [ALTITUD] ASC),
    CONSTRAINT [FK_VISITA_TERRENO_DETALLE_VTDGPS] FOREIGN KEY ([ID_VISITA_DETALLE], [ID_VISITA]) REFERENCES [dbo].[VISITA_TERRENO_DETALLE] ([ID_VISITA_DETALLE], [ID_VISITA])
);

