CREATE TABLE [dbo].[VISITA_TERRENO] (
    [ID_VISITA]      INT      NOT NULL,
    [CTCID]          INT      NOT NULL,
    [SOLICITUD_ID]   INT      NOT NULL,
    [ID_ESTATUS]     INT      CONSTRAINT [DF_ID_ESTATUS] DEFAULT ((1)) NOT NULL,
    [FEC_CREACION]   DATETIME CONSTRAINT [DF_FEC_CREACION] DEFAULT (getdate()) NOT NULL,
    [USRID_CREACION] INT      NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO] PRIMARY KEY CLUSTERED ([ID_VISITA] ASC, [CTCID] ASC),
    CONSTRAINT [FK_ESTATUS_VISITA_TERRENO] FOREIGN KEY ([ID_ESTATUS]) REFERENCES [dbo].[VISITA_TERRENO_TIPO_ESTATUS_ESTADO] ([ID_ESTATUS]),
    CONSTRAINT [FK_SOLICITUD_ID] FOREIGN KEY ([SOLICITUD_ID]) REFERENCES [dbo].[VISITA_TERRENO_SOLICITUD] ([SOLICITUD_ID])
);

