CREATE TABLE [dbo].[VISITA_TERRENO_CREDENCIALES_GEOGESTION] (
    [USERGEO] VARCHAR (50) NOT NULL,
    [PASSGEO] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_CREDENCIALES_GEOGESTION] PRIMARY KEY CLUSTERED ([USERGEO] ASC)
);

