CREATE TABLE [dbo].[VISITA_TERRENO_CLIENTEPOINT_GESTOR] (
    [CLIENTEPOINT_ID] VARCHAR (100) NOT NULL,
    [SOLICITUD_ID]    INT           NOT NULL,
    [GESID]           INT           NOT NULL,
    [TELEFONO_IMEI]   VARCHAR (100) NOT NULL,
    [USRID_REGISTRO]  INT           NOT NULL,
    [FEC_REGISTRO]    DATETIME      CONSTRAINT [DF_VISITA_TERRENO_CLIENTEPOINT_GESTOR_FEC_REGISTRO] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_CLIENTEPOINT_GESTOR] PRIMARY KEY CLUSTERED ([CLIENTEPOINT_ID] ASC),
    CONSTRAINT [FK_VISITA_TERRENO_CLIENTEPOINT_GESTOR] FOREIGN KEY ([SOLICITUD_ID], [GESID], [TELEFONO_IMEI]) REFERENCES [dbo].[VISITA_TERRENO_SOLICITUD_GESTOR] ([SOLICITUD_ID], [GESID], [TELEFONO_IMEI])
);

