CREATE TABLE [dbo].[VISITA_TERRENO_DETALLE] (
    [ID_VISITA_DETALLE] INT            NOT NULL,
    [ID_VISITA]         INT            NOT NULL,
    [CTCID]             INT            NOT NULL,
    [ESTADO_VISITA]     INT            CONSTRAINT [DF_ESTADO_VISITA] DEFAULT ((1)) NOT NULL,
    [VISITA]            CHAR (1)       CONSTRAINT [DF_VISITA] DEFAULT ('P') NOT NULL,
    [COMENTARIOS]       VARCHAR (1000) NULL,
    [DIRECCIONACTUAL]   VARCHAR (1)    CONSTRAINT [DF_VISITA_TERRENO_DETALLE_DIRECCIONACTUAL] DEFAULT ('S') NOT NULL,
    [FEC_ENVIO]         DATETIME       CONSTRAINT [DF_FEC_ENVIO_VISITA_TERRENO_DETALLE] DEFAULT (getdate()) NOT NULL,
    [DIRECCIONENVIO]    VARCHAR (100)  NULL,
    [POSICIONENVIO]     VARCHAR (100)  NULL,
    CONSTRAINT [PK_VISITA_TERRENO_DETALLE] PRIMARY KEY CLUSTERED ([ID_VISITA_DETALLE] ASC, [ID_VISITA] ASC),
    CONSTRAINT [CKC_VISITA] CHECK ([VISITA]='N' OR [VISITA]='P'),
    CONSTRAINT [CKC_VISITA_TERRENO_DETALLE_DIRECCIONACTUAL] CHECK ([DIRECCIONACTUAL]='N' OR [DIRECCIONACTUAL]='S'),
    CONSTRAINT [FK_ESTADO_VISITA] FOREIGN KEY ([ESTADO_VISITA]) REFERENCES [dbo].[VISITA_TERRENO_DETALLE_TIPO_ESTADO_VISITA] ([ID_TIPO_ESTADO_VISITA]),
    CONSTRAINT [FK_VISITA_TERRENO_DETALLE_VT] FOREIGN KEY ([ID_VISITA], [CTCID]) REFERENCES [dbo].[VISITA_TERRENO] ([ID_VISITA], [CTCID])
);

