CREATE TABLE [dbo].[VISITA_TERRENO_DETALLE_TIPO_ESTADO_VISITA] (
    [ID_TIPO_ESTADO_VISITA] INT          NOT NULL,
    [ESTADO_VISITA]         VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_VISITA_TERRENO_DETALLE_TIPO_ESTADO_VISITA] PRIMARY KEY CLUSTERED ([ID_TIPO_ESTADO_VISITA] ASC)
);

